# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/__init__.py — do not edit.
"""Deterministic CODE-SYNTH v0 challenge generation."""

from .generator import (
    GeneratedChallenge,
    HiddenTestPlan,
    derive_instance_root,
    generate_challenge,
    generate_hidden_test_plan,
)
from .model import ChallengeContext, GenerationFailed, ReferenceEvaluationFailed

__all__ = [
    "ChallengeContext",
    "GeneratedChallenge",
    "GenerationFailed",
    "HiddenTestPlan",
    "ReferenceEvaluationFailed",
    "derive_instance_root",
    "generate_challenge",
    "generate_hidden_test_plan",
]
