# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/canonical.py — do not edit.
"""CODE-SYNTH compatibility adapter for shared canonical serialization."""

from __future__ import annotations

from ares_lite._core.canonical.codec import CanonicalEncodingError
from ares_lite._core.canonical.codec import encode as _shared_encode

from .model import GenerationFailed


MAX_CBOR_ARGUMENT = (1 << 64) - 1
MIN_CBOR_INTEGER = -(1 << 64)


def encode(value: object) -> bytes:
    """Encode a value under the restricted CODE-SYNTH Deterministic CBOR profile."""

    try:
        return _shared_encode(value)
    except CanonicalEncodingError as exc:
        raise GenerationFailed(str(exc)) from exc
