# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/evaluators.py — do not edit.
"""Pure reference evaluators for the three CODE-SYNTH v0 modes.

Expected outputs come from these deterministic algorithms, never from a miner,
model, provider, clock, or subjective judge. Each evaluator implements the
mode-specific objective and tie rule with mathematical integer intermediates and
an explicit step bound. Submitted WebAssembly execution and output comparison are
outside this module and remain P1-T04 work.
"""

from __future__ import annotations

from itertools import combinations

from .model import ReferenceEvaluationFailed


I64_MIN = -(1 << 63)
I64_MAX = (1 << 63) - 1
U64_MAX = (1 << 64) - 1


def reference_evaluate(
    task_spec: list[object],
    case_input: object,
    *,
    step_limit: int,
) -> list[object]:
    """Return the unique output selected by the frozen mode semantics."""

    if type(step_limit) is not int or step_limit <= 0:
        raise ReferenceEvaluationFailed("reference step limit must be positive")
    try:
        mode = task_spec[0]
        if mode == 0:
            return _evaluate_seq(task_spec, case_input, step_limit)
        if mode == 1:
            return _evaluate_graph(task_spec, case_input, step_limit)
        if mode == 2:
            return _evaluate_rule(task_spec, case_input, step_limit)
        raise ReferenceEvaluationFailed("unsupported CODE-SYNTH mode")
    except ReferenceEvaluationFailed:
        raise
    except (IndexError, TypeError, ValueError, OverflowError) as exc:
        raise ReferenceEvaluationFailed("malformed task specification or input") from exc


def _evaluate_seq(task: list[object], case_input: object, step_limit: int) -> list[object]:
    if len(task) != 10 or task[:2] != [0, 0] or not isinstance(case_input, list):
        raise ReferenceEvaluationFailed("invalid SEQ-DP task or input shape")
    length_min, length_max, value_min, value_max, count, gap_min, gap_max, penalty = task[2:]
    if not length_min <= len(case_input) <= length_max:
        raise ReferenceEvaluationFailed("SEQ-DP input length is out of range")
    if any(type(value) is not int or not value_min <= value <= value_max for value in case_input):
        raise ReferenceEvaluationFailed("SEQ-DP value is out of range")

    best: tuple[int, tuple[int, ...]] | None = None
    steps = 0
    for indices in combinations(range(len(case_input)), count):
        if any(not gap_min <= right - left <= gap_max for left, right in zip(indices, indices[1:])):
            continue
        steps += 1
        if steps > step_limit:
            raise ReferenceEvaluationFailed("SEQ-DP reference step limit exceeded")
        score = sum(case_input[index] for index in indices)
        score -= penalty * sum(right - left - gap_min for left, right in zip(indices, indices[1:]))
        if not I64_MIN <= score <= I64_MAX:
            raise ReferenceEvaluationFailed("SEQ-DP result is outside i64")
        candidate = (score, indices)
        if best is None or score > best[0] or (score == best[0] and indices < best[1]):
            best = candidate
    if best is None:
        raise ReferenceEvaluationFailed("SEQ-DP has no feasible selection")
    return [best[0], list(best[1])]


def _evaluate_graph(task: list[object], case_input: object, step_limit: int) -> list[object]:
    if len(task) != 13 or task[:2] != [1, 0] or not isinstance(case_input, list) or len(case_input) != 4:
        raise ReferenceEvaluationFailed("invalid GRAPH-ROUTE task or input shape")
    (
        vertex_min,
        vertex_max,
        edge_min,
        edge_max,
        cost_max,
        _resource_max,
        resource_budget,
        hop_limit,
        class_count,
        required_mask,
        forbidden_mask,
    ) = task[2:]
    vertex_count, edges, source, target = case_input
    if type(vertex_count) is not int or not vertex_min <= vertex_count <= vertex_max:
        raise ReferenceEvaluationFailed("GRAPH-ROUTE vertex count is out of range")
    if not isinstance(edges, list) or not edge_min <= len(edges) <= edge_max:
        raise ReferenceEvaluationFailed("GRAPH-ROUTE edge count is out of range")
    if (
        type(source) is not int
        or type(target) is not int
        or not 0 <= source < vertex_count
        or not 0 <= target < vertex_count
    ):
        raise ReferenceEvaluationFailed("GRAPH-ROUTE endpoint is out of range")
    if required_mask & forbidden_mask:
        raise ReferenceEvaluationFailed("GRAPH-ROUTE class masks overlap")

    seen_pairs: set[tuple[int, int]] = set()
    previous_edge: tuple[int, ...] | None = None
    outgoing: dict[int, list[int]] = {}
    for edge_index, edge in enumerate(edges):
        if not isinstance(edge, list) or len(edge) != 5 or any(type(value) is not int for value in edge):
            raise ReferenceEvaluationFailed("GRAPH-ROUTE edge is malformed")
        from_vertex, to_vertex, cost, resource, class_id = edge
        if not (0 <= from_vertex < vertex_count and 0 <= to_vertex < vertex_count and from_vertex != to_vertex):
            raise ReferenceEvaluationFailed("GRAPH-ROUTE edge endpoint is invalid")
        # Section 5.4 gives planted backbone edges the constructor-specific
        # range floor(resource_budget / backbone_length), which is authoritative
        # even when it exceeds the extra-edge resource_max value.
        if not (0 <= cost <= cost_max and 0 <= resource <= U64_MAX and 0 <= class_id < class_count):
            raise ReferenceEvaluationFailed("GRAPH-ROUTE edge attribute is invalid")
        pair = (from_vertex, to_vertex)
        if pair in seen_pairs:
            raise ReferenceEvaluationFailed("GRAPH-ROUTE contains a duplicate ordered pair")
        seen_pairs.add(pair)
        edge_tuple = tuple(edge)
        if previous_edge is not None and edge_tuple < previous_edge:
            raise ReferenceEvaluationFailed("GRAPH-ROUTE edges are not canonically sorted")
        previous_edge = edge_tuple
        outgoing.setdefault(from_vertex, []).append(edge_index)

    states: dict[tuple[int, int, int], tuple[int, tuple[int, ...]]] = {
        (source, 0, 0): (0, ())
    }
    best: tuple[int, tuple[int, ...]] | None = None
    steps = 0
    for _layer in range(1, hop_limit + 1):
        next_states: dict[tuple[int, int, int], tuple[int, tuple[int, ...]]] = {}
        for state_key in sorted(states):
            vertex, resource_used, seen_required = state_key
            current_cost, current_path = states[state_key]
            for edge_index in outgoing.get(vertex, ()):  # edge indices are already ascending
                steps += 1
                if steps > step_limit:
                    raise ReferenceEvaluationFailed("GRAPH-ROUTE reference step limit exceeded")
                _from_vertex, to_vertex, cost, resource, class_id = edges[edge_index]
                class_bit = 1 << class_id
                next_resource = resource_used + resource
                if class_bit & forbidden_mask or next_resource > resource_budget:
                    continue
                next_cost = current_cost + cost
                if next_cost > U64_MAX or next_resource > U64_MAX:
                    raise ReferenceEvaluationFailed("GRAPH-ROUTE total exceeds u64")
                next_mask = seen_required | (class_bit & required_mask)
                next_key = (to_vertex, next_resource, next_mask)
                next_value = (next_cost, current_path + (edge_index,))
                incumbent = next_states.get(next_key)
                if incumbent is None or next_value < incumbent:
                    next_states[next_key] = next_value
        states = next_states
        for (vertex, _resource, seen_required), candidate in states.items():
            if vertex == target and seen_required == required_mask and (best is None or candidate < best):
                best = candidate
    if best is None:
        raise ReferenceEvaluationFailed("GRAPH-ROUTE has no valid route")
    return [best[0], list(best[1])]


def _evaluate_rule(task: list[object], case_input: object, step_limit: int) -> list[object]:
    if len(task) != 10 or task[:2] != [2, 0] or not isinstance(case_input, list) or len(case_input) != 3:
        raise ReferenceEvaluationFailed("invalid RULE-STATE task or input shape")
    state_count, alphabet_size, register_count, event_min, event_max, value_min, value_max, transitions = task[2:]
    initial_state, registers, events = case_input
    if type(initial_state) is not int or not 0 <= initial_state < state_count:
        raise ReferenceEvaluationFailed("RULE-STATE initial state is invalid")
    if not isinstance(registers, list) or len(registers) != register_count:
        raise ReferenceEvaluationFailed("RULE-STATE register vector is invalid")
    if any(type(value) is not int or not value_min <= value <= value_max for value in registers):
        raise ReferenceEvaluationFailed("RULE-STATE register value is invalid")
    if not isinstance(events, list) or not event_min <= len(events) <= event_max:
        raise ReferenceEvaluationFailed("RULE-STATE event vector is invalid")
    if any(type(event) is not int or not 0 <= event < alphabet_size for event in events):
        raise ReferenceEvaluationFailed("RULE-STATE event value is invalid")

    rules: dict[tuple[int, int], list[list[object]]] = {}
    previous_key: tuple[int, int, int] | None = None
    for rule in transitions:
        if not isinstance(rule, list) or len(rule) != 7:
            raise ReferenceEvaluationFailed("RULE-STATE transition is malformed")
        current, event, guard_register, compare_op, constant, next_state, updates = rule
        key = (current, event, compare_op)
        if previous_key is not None and key <= previous_key:
            raise ReferenceEvaluationFailed("RULE-STATE transitions are not strictly ordered")
        previous_key = key
        if not (0 <= current < state_count and 0 <= event < alphabet_size):
            raise ReferenceEvaluationFailed("RULE-STATE transition key is invalid")
        if not (0 <= guard_register < register_count and 0 <= next_state < state_count):
            raise ReferenceEvaluationFailed("RULE-STATE transition target is invalid")
        if compare_op not in range(6) or not I64_MIN <= constant <= I64_MAX:
            raise ReferenceEvaluationFailed("RULE-STATE guard is invalid")
        if not isinstance(updates, list) or len(updates) != register_count:
            raise ReferenceEvaluationFailed("RULE-STATE updates are incomplete")
        for expected_index, update in enumerate(updates):
            if not isinstance(update, list) or len(update) != 4 or update[0] != expected_index:
                raise ReferenceEvaluationFailed("RULE-STATE updates are not canonical")
        rules.setdefault((current, event), []).append(rule)

    state = initial_state
    current_registers = list(registers)
    steps = 0
    for event in events:
        matching: list[list[object]] = []
        for rule in rules.get((state, event), ()):
            steps += 1
            if steps > step_limit:
                raise ReferenceEvaluationFailed("RULE-STATE reference step limit exceeded")
            _current, _event, guard_index, compare_op, constant, _next, _updates = rule
            if _compare(current_registers[guard_index], compare_op, constant):
                matching.append(rule)
        if len(matching) != 1:
            raise ReferenceEvaluationFailed("RULE-STATE transition coverage is not unique")
        rule = matching[0]
        next_registers: list[int] = []
        for register_index, multiplier, addend, event_multiplier in rule[6]:
            value = multiplier * current_registers[register_index] + addend + event_multiplier * event
            if not I64_MIN <= value <= I64_MAX:
                raise ReferenceEvaluationFailed("RULE-STATE update exceeds i64")
            next_registers.append(value)
        state = rule[5]
        current_registers = next_registers
    return [state, current_registers]


def _compare(left: int, operation: int, right: int) -> bool:
    if operation == 0:
        return left == right
    if operation == 1:
        return left != right
    if operation == 2:
        return left < right
    if operation == 3:
        return left <= right
    if operation == 4:
        return left > right
    return left >= right
