# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/generator.py — do not edit.
"""Ticket-specific deterministic generator for CODE-SYNTH v0.

The generator accepts finalized protocol inputs and never obtains entropy, time,
provider data, or network state on its own. Any invalid input, sampler failure,
coordinate reuse, evaluator failure, or postcondition violation fails closed;
callers must not reroll a finalized ticket.

This module owns family-local construction only: Instance Roots, mode and
parameter selection, public and solution-bound hidden cases, reference outputs,
and canonical Challenge artifacts. Ticket allocation, general protocol encoding,
commit/reveal, sandbox execution, rewards, and Difficulty control are separate
roadmap components. Extensions that alter observable bytes require a new family
version and conformance vectors rather than a conditional v0 code path.
"""

from __future__ import annotations

from dataclasses import dataclass

from ares_lite._core.canonical.domains import (
    CODE_SYNTH_CHALLENGE_ID,
    CODE_SYNTH_HIDDEN_CASE,
    CODE_SYNTH_INSTANCE_ROOT,
    CODE_SYNTH_PUBLIC_CASE,
    CODE_SYNTH_TEST_ROOT,
)

from .canonical import encode
from .evaluators import I64_MAX, reference_evaluate
from .model import ChallengeContext, GenerationFailed, ReferenceEvaluationFailed
from .primitives import CoordinateSampler, hash_bytes, u16_be, u32_be, u64_be


FAMILY_ID = "CODE-SYNTH"
FAMILY_VERSION = 0
MODE_VERSION = 0
EXECUTION_PROFILE_ID = 0
TEST_POLICY_ID = 0
SUPPORTED_DIFFICULTIES = (0, 1, 2)
REFERENCE_STEP_LIMITS = (1_000_000, 2_000_000, 4_000_000)
MODE_WEIGHTS = ((2, 1, 1), (1, 2, 1), (1, 1, 2))

MIN = "MIN"
MAX = "MAX"
RANDOM = "RANDOM"
ZERO = "ZERO"
ALT = "ALT"

INPUT_PROFILES: tuple[tuple[str, str, str], ...] = (
    (MIN, MIN, MIN),
    (MAX, MAX, MAX),
    (MIN, MAX, ALT),
    (MAX, MIN, ZERO),
    (MIN, RANDOM, MAX),
    (MAX, RANDOM, MIN),
    (RANDOM, MAX, ZERO),
    (RANDOM, MIN, ALT),
    (RANDOM, RANDOM, RANDOM),
    (RANDOM, RANDOM, RANDOM),
    (RANDOM, RANDOM, RANDOM),
    (RANDOM, RANDOM, RANDOM),
    (RANDOM, RANDOM, RANDOM),
    (RANDOM, RANDOM, RANDOM),
    (RANDOM, RANDOM, RANDOM),
    (RANDOM, RANDOM, RANDOM),
    (MIN, MAX, ZERO),
    (MAX, MAX, ALT),
    (RANDOM, MIN, MIN),
    (RANDOM, MAX, MAX),
    (RANDOM, RANDOM, RANDOM),
    (MAX, RANDOM, ALT),
)


@dataclass(frozen=True, slots=True)
class GeneratedChallenge:
    context: ChallengeContext
    challenge_seed: bytes
    instance_root: bytes
    mode_id: int
    task_spec: list[object]
    input_type: list[object]
    output_type: list[object]
    public_examples: list[list[object]]
    value: list[object]
    challenge_bytes: bytes
    challenge_id: bytes


@dataclass(frozen=True, slots=True)
class HiddenTestPlan:
    test_root: bytes
    cases: list[list[object]]
    plan_bytes: bytes


def derive_instance_root(context: ChallengeContext, challenge_seed: bytes) -> bytes:
    """Bind every finalized v0 context field to the 32-byte Challenge Seed."""

    _require_32_bytes(challenge_seed, "challenge_seed")
    return hash_bytes(
        CODE_SYNTH_INSTANCE_ROOT,
        (
            context.chain_id,
            u32_be(context.protocol_version),
            u16_be(context.family_version),
            u64_be(context.round_id),
            context.ticket_id,
            u64_be(context.adjustment_epoch),
            u32_be(context.difficulty_index),
            challenge_seed,
        ),
    )


def generate_challenge(context: ChallengeContext, challenge_seed: bytes) -> GeneratedChallenge:
    """Generate one canonical ticket-specific Challenge or fail without reroll."""

    instance_root = derive_instance_root(context, challenge_seed)
    if context.difficulty_index not in SUPPORTED_DIFFICULTIES:
        raise GenerationFailed("unsupported CODE-SYNTH difficulty", instance_root=instance_root)

    try:
        sampler = CoordinateSampler(instance_root)
        mode_id = _select_mode(sampler, context.adjustment_epoch)
        task_spec = _generate_task_spec(sampler, mode_id, context.difficulty_index)
        input_type, output_type = _types_for_task(task_spec)
        public_examples = _public_examples(
            mode_id,
            task_spec,
            instance_root,
            REFERENCE_STEP_LIMITS[context.difficulty_index],
        )
        value: list[object] = [
            0,
            FAMILY_ID,
            FAMILY_VERSION,
            context.chain_id,
            context.protocol_version,
            context.round_id,
            context.ticket_id,
            context.adjustment_epoch,
            context.difficulty_index,
            mode_id,
            MODE_VERSION,
            task_spec,
            input_type,
            output_type,
            public_examples,
            EXECUTION_PROFILE_ID,
            context.difficulty_index,
            TEST_POLICY_ID,
        ]
        challenge_bytes = encode(value)
        challenge_id = hash_bytes(CODE_SYNTH_CHALLENGE_ID, (challenge_bytes,))
        return GeneratedChallenge(
            context=context,
            challenge_seed=challenge_seed,
            instance_root=instance_root,
            mode_id=mode_id,
            task_spec=task_spec,
            input_type=input_type,
            output_type=output_type,
            public_examples=public_examples,
            value=value,
            challenge_bytes=challenge_bytes,
            challenge_id=challenge_id,
        )
    except GenerationFailed as exc:
        if exc.instance_root is None:
            exc.instance_root = instance_root
        raise
    except ReferenceEvaluationFailed as exc:
        raise GenerationFailed(str(exc), instance_root=instance_root) from exc


def generate_hidden_test_plan(
    challenge: GeneratedChallenge,
    verification_seed: bytes,
    solution_hash: bytes,
) -> HiddenTestPlan:
    """Derive the fixed Policy-0 test stream bound to one committed solution hash."""

    _validate_generated_challenge(challenge)
    _require_32_bytes(verification_seed, "verification_seed")
    _require_32_bytes(solution_hash, "solution_hash")
    test_root = hash_bytes(
        CODE_SYNTH_TEST_ROOT,
        (
            verification_seed,
            challenge.challenge_id,
            challenge.context.ticket_id,
            solution_hash,
            u16_be(TEST_POLICY_ID),
        ),
    )
    cases: list[list[object]] = []
    for ordinal in range(20):
        stratum_code, stratum_index = _hidden_stratum(ordinal)
        case_root = hash_bytes(
            CODE_SYNTH_HIDDEN_CASE,
            (test_root, u16_be(stratum_code), u32_be(stratum_index), u32_be(ordinal)),
        )
        case_input = construct_input(challenge.mode_id, challenge.task_spec, case_root, ordinal)
        expected = reference_evaluate(
            challenge.task_spec,
            case_input,
            step_limit=REFERENCE_STEP_LIMITS[challenge.context.difficulty_index],
        )
        cases.append([case_input, expected])
    return HiddenTestPlan(test_root=test_root, cases=cases, plan_bytes=encode(cases))


def construct_input(mode_id: int, task_spec: list[object], case_root: bytes, profile: int) -> object:
    """Construct one case using the frozen profile selectors and mode grammar."""

    _require_32_bytes(case_root, "case_root")
    if type(profile) is not int or not 0 <= profile < len(INPUT_PROFILES):
        raise GenerationFailed("input profile is out of range")
    try:
        sampler = CoordinateSampler(case_root)
        size_a, size_b, value_selector = INPUT_PROFILES[profile]
        if mode_id == 0:
            return _construct_seq(task_spec, sampler, size_a, value_selector)
        if mode_id == 1:
            return _construct_graph(task_spec, sampler, size_a, size_b, value_selector)
        if mode_id == 2:
            return _construct_rule(task_spec, sampler, size_a, size_b, value_selector)
        raise GenerationFailed("unsupported CODE-SYNTH mode")
    except GenerationFailed:
        raise
    except (IndexError, TypeError, ValueError, OverflowError) as exc:
        raise GenerationFailed("malformed task specification") from exc


def _select_mode(sampler: CoordinateSampler, adjustment_epoch: int) -> int:
    weights = MODE_WEIGHTS[adjustment_epoch % 3]
    draw = sampler.u("mode", 0, 0, sum(weights) - 1)
    if draw < weights[0]:
        return 0
    if draw < weights[0] + weights[1]:
        return 1
    return 2


def _generate_task_spec(sampler: CoordinateSampler, mode_id: int, difficulty: int) -> list[object]:
    if mode_id == 0:
        return _generate_seq_task(sampler, difficulty)
    if mode_id == 1:
        return _generate_graph_task(sampler, difficulty)
    if mode_id == 2:
        return _generate_rule_task(sampler, difficulty)
    raise GenerationFailed("unsupported CODE-SYNTH mode")


def _generate_seq_task(sampler: CoordinateSampler, difficulty: int) -> list[object]:
    selection_count = 2 + difficulty + sampler.u("seq/selection-count", 0, 0, 1)
    gap_min = 1 + sampler.u("seq/gap-min", 0, 0, difficulty)
    gap_max = gap_min + 1 + sampler.u("seq/gap-span", 0, 0, difficulty + 1)
    input_len_min = 1 + (selection_count - 1) * gap_min + sampler.u("seq/len-min-slack", 0, 1, 3)
    input_len_max = input_len_min + 4 + 2 * difficulty + sampler.u("seq/len-span", 0, 0, 3)
    value_min = -32 * (difficulty + 1)
    value_max = 32 * (difficulty + 1)
    gap_penalty = sampler.u("seq/gap-penalty", 0, 0, 8 * (difficulty + 1))
    bound = selection_count * max(abs(value_min), abs(value_max))
    bound += (selection_count - 1) * gap_penalty * (gap_max - gap_min)
    if bound > I64_MAX or input_len_min < 1 + (selection_count - 1) * gap_min:
        raise GenerationFailed("SEQ-DP feasibility or overflow postcondition failed")
    return [
        0,
        0,
        input_len_min,
        input_len_max,
        value_min,
        value_max,
        selection_count,
        gap_min,
        gap_max,
        gap_penalty,
    ]


def _generate_graph_task(sampler: CoordinateSampler, difficulty: int) -> list[object]:
    vertex_min = 4 + 2 * difficulty + sampler.u("graph/vertex-min", 0, 0, 2)
    vertex_max = vertex_min + 4 + 2 * difficulty
    edge_min = vertex_min - 1
    edge_max = min(vertex_max * (vertex_max - 1), 2 * vertex_max + 4 * (difficulty + 1))
    cost_max = 16 * (difficulty + 1)
    resource_max = 8 * (difficulty + 1)
    hop_limit = min(vertex_min - 1, 2 + difficulty + sampler.u("graph/hop-limit", 0, 0, 1))
    class_count = 3 + difficulty
    required_class = sampler.u("graph/required-class", 0, 0, class_count - 1)
    forbidden_class = (
        required_class
        + 1
        + sampler.u("graph/forbidden-offset", 0, 0, class_count - 2)
    ) % class_count
    required_mask = 1 << required_class
    forbidden_mask = 1 << forbidden_class
    resource_budget = hop_limit * max(1, resource_max // 2)
    return [
        1,
        0,
        vertex_min,
        vertex_max,
        edge_min,
        edge_max,
        cost_max,
        resource_max,
        resource_budget,
        hop_limit,
        class_count,
        required_mask,
        forbidden_mask,
    ]


def _generate_rule_task(sampler: CoordinateSampler, difficulty: int) -> list[object]:
    state_count = 2 + difficulty + sampler.u("rule/state-count", 0, 0, 2)
    alphabet_size = 2 + difficulty + sampler.u("rule/alphabet-size", 0, 0, 1)
    register_count = 1 + min(difficulty, 2)
    event_len_min = 4 + 2 * difficulty
    event_len_max = event_len_min + 4 + 2 * difficulty
    value_min = -64 * (difficulty + 1)
    value_max = 64 * (difficulty + 1)
    bound = max(abs(value_min), abs(value_max))
    bound += event_len_max * (2 * (difficulty + 1) + alphabet_size - 1)
    if bound > I64_MAX:
        raise GenerationFailed("RULE-STATE overflow postcondition failed")

    transitions: list[list[object]] = []
    for state in range(state_count):
        for event in range(alphabet_size):
            pair_index = state * alphabet_size + event
            if difficulty == 0:
                guard_register = 0
                branches = ((0, 5, -(1 << 63)),)
            else:
                guard_register = sampler.u("rule/guard-register", pair_index, 0, register_count - 1)
                branches = ((0, 2, 0), (1, 5, 0))
            for branch, compare_op, constant in branches:
                next_state = sampler.u(
                    "rule/next-state",
                    pair_index * 2 + branch,
                    0,
                    state_count - 1,
                )
                updates: list[list[int]] = []
                for register in range(register_count):
                    update_index = ((pair_index * 2 + branch) * register_count) + register
                    updates.append(
                        [
                            register,
                            sampler.s("rule/multiplier", update_index, -1, 1),
                            sampler.s("rule/addend", update_index, -2 * (difficulty + 1), 2 * (difficulty + 1)),
                            sampler.s("rule/event-multiplier", update_index, -1, 1),
                        ]
                    )
                transitions.append(
                    [state, event, guard_register, compare_op, constant, next_state, updates]
                )
    return [
        2,
        0,
        state_count,
        alphabet_size,
        register_count,
        event_len_min,
        event_len_max,
        value_min,
        value_max,
        transitions,
    ]


def _types_for_task(task: list[object]) -> tuple[list[object], list[object]]:
    if task[0] == 0:
        input_len_max, selection_count = task[3], task[6]
        return [4, 1, input_len_max], [5, 1, [4, 2, selection_count]]
    if task[0] == 1:
        edge_count_max, hop_limit = task[5], task[9]
        return [5, 2, [4, [5, 2, 2, 2, 2, 2], edge_count_max], 2, 2], [5, 2, [4, 2, hop_limit]]
    if task[0] == 2:
        register_count, event_len_max = task[4], task[6]
        return [5, 2, [4, 1, register_count], [4, 2, event_len_max]], [5, 2, [4, 1, register_count]]
    raise GenerationFailed("unsupported CODE-SYNTH mode")


def _public_examples(
    mode_id: int,
    task_spec: list[object],
    instance_root: bytes,
    step_limit: int,
) -> list[list[object]]:
    examples: list[list[object]] = []
    for index in range(2):
        case_root = hash_bytes(
            CODE_SYNTH_PUBLIC_CASE,
            (instance_root, u32_be(index)),
        )
        case_input = construct_input(mode_id, task_spec, case_root, 20 + index)
        expected = reference_evaluate(task_spec, case_input, step_limit=step_limit)
        examples.append([case_input, expected])
    return examples


def _construct_seq(
    task: list[object],
    sampler: CoordinateSampler,
    size_selector: str,
    value_selector: str,
) -> list[int]:
    if len(task) != 10 or task[:2] != [0, 0]:
        raise GenerationFailed("SEQ-DP task specification is malformed")
    length = _select_size(sampler, size_selector, "seq-input/size-a", task[2], task[3])
    return [
        _select_value(sampler, value_selector, "seq-input/value", index, task[4], task[5], signed=True)
        for index in range(length)
    ]


def _construct_rule(
    task: list[object],
    sampler: CoordinateSampler,
    size_a: str,
    size_b: str,
    value_selector: str,
) -> list[object]:
    if len(task) != 10 or task[:2] != [2, 0]:
        raise GenerationFailed("RULE-STATE task specification is malformed")
    state_count, alphabet_size, register_count = task[2:5]
    event_length = _select_size(sampler, size_a, "rule-input/size-a", task[5], task[6])
    initial_state = _select_size(sampler, size_b, "rule-input/state", 0, state_count - 1)
    registers = [
        _select_value(
            sampler,
            value_selector,
            "rule-input/register",
            index,
            task[7],
            task[8],
            signed=True,
        )
        for index in range(register_count)
    ]
    events = [
        _select_value(
            sampler,
            value_selector,
            "rule-input/event",
            index,
            0,
            alphabet_size - 1,
            signed=False,
        )
        for index in range(event_length)
    ]
    return [initial_state, registers, events]


def _construct_graph(
    task: list[object],
    sampler: CoordinateSampler,
    size_a: str,
    size_b: str,
    value_selector: str,
) -> list[object]:
    if len(task) != 13 or task[:2] != [1, 0]:
        raise GenerationFailed("GRAPH-ROUTE task specification is malformed")
    (
        vertex_min,
        vertex_max,
        edge_min,
        edge_max,
        cost_max,
        resource_max,
        resource_budget,
        hop_limit,
        class_count,
        required_mask,
        forbidden_mask,
    ) = task[2:]
    vertex_count = _select_size(sampler, size_a, "graph-input/size-a", vertex_min, vertex_max)
    backbone_max = min(hop_limit, vertex_count - 1)
    backbone_length = _select_size(
        sampler,
        size_b,
        "graph-input/backbone-length",
        1,
        backbone_max,
    )
    internal_vertices = sampler.permute(
        "graph-input/backbone-vertices",
        list(range(1, vertex_count - 1)),
    )[: backbone_length - 1]
    path_vertices = [0, *internal_vertices, vertex_count - 1]
    backbone_pairs = list(zip(path_vertices, path_vertices[1:]))

    edge_count_low = max(backbone_length, edge_min)
    edge_count_high = min(edge_max, vertex_count * (vertex_count - 1))
    target_edge_count = _select_size(
        sampler,
        size_b,
        "graph-input/edge-count",
        edge_count_low,
        edge_count_high,
    )
    backbone_set = set(backbone_pairs)
    remaining_pairs = [
        (from_vertex, to_vertex)
        for from_vertex in range(vertex_count)
        for to_vertex in range(vertex_count)
        if from_vertex != to_vertex and (from_vertex, to_vertex) not in backbone_set
    ]
    extra_pairs = sampler.permute("graph-input/extra-pairs", remaining_pairs)[
        : target_edge_count - backbone_length
    ]
    selected_pairs = [*backbone_pairs, *extra_pairs]
    if len(selected_pairs) != target_edge_count or len(set(selected_pairs)) != target_edge_count:
        raise GenerationFailed("GRAPH-ROUTE pair selection postcondition failed")

    required_class = _single_bit_index(required_mask, class_count, "required")
    _single_bit_index(forbidden_mask, class_count, "forbidden")
    non_forbidden_class = next(
        (class_id for class_id in range(class_count) if not (forbidden_mask & (1 << class_id))),
        None,
    )
    if non_forbidden_class is None:
        raise GenerationFailed("GRAPH-ROUTE has no non-forbidden class")
    backbone_positions = {pair: index for index, pair in enumerate(backbone_pairs)}
    edges: list[list[int]] = []
    for pair in selected_pairs:
        from_vertex, to_vertex = pair
        pair_rank = from_vertex * (vertex_count - 1) + (
            to_vertex if to_vertex < from_vertex else to_vertex - 1
        )
        backbone_position = backbone_positions.get(pair)
        resource_hi = (
            resource_budget // backbone_length
            if backbone_position is not None
            else resource_max
        )
        cost = _select_value(
            sampler,
            value_selector,
            "graph-input/cost",
            pair_rank,
            0,
            cost_max,
            signed=False,
        )
        resource = _select_value(
            sampler,
            value_selector,
            "graph-input/resource",
            pair_rank,
            0,
            resource_hi,
            signed=False,
        )
        class_id = _select_value(
            sampler,
            value_selector,
            "graph-input/class",
            pair_rank,
            0,
            class_count - 1,
            signed=False,
        )
        if backbone_position == 0:
            class_id = required_class
        elif backbone_position is not None:
            class_id = non_forbidden_class
        edges.append([from_vertex, to_vertex, cost, resource, class_id])
    edges.sort()
    return [vertex_count, edges, 0, vertex_count - 1]


def _select_size(
    sampler: CoordinateSampler,
    selector: str,
    label: str,
    minimum: int,
    maximum: int,
) -> int:
    if minimum > maximum:
        raise GenerationFailed("size selector range is empty")
    if selector == MIN:
        return minimum
    if selector == MAX:
        return maximum
    if selector == RANDOM:
        return sampler.u(label, 0, minimum, maximum)
    raise GenerationFailed("illegal size selector")


def _select_value(
    sampler: CoordinateSampler,
    selector: str,
    label: str,
    index: int,
    minimum: int,
    maximum: int,
    *,
    signed: bool,
) -> int:
    if minimum > maximum:
        raise GenerationFailed("value selector range is empty")
    if selector == MIN:
        return minimum
    if selector == MAX:
        return maximum
    if selector == ZERO:
        return min(max(0, minimum), maximum)
    if selector == ALT:
        return maximum if index % 2 == 0 else minimum
    if selector == RANDOM:
        return (
            sampler.s(label, index, minimum, maximum)
            if signed
            else sampler.u(label, index, minimum, maximum)
        )
    raise GenerationFailed("illegal value selector")


def _single_bit_index(mask: int, class_count: int, name: str) -> int:
    if type(mask) is not int or mask <= 0 or mask.bit_count() != 1:
        raise GenerationFailed(f"GRAPH-ROUTE {name} mask must contain one bit")
    index = mask.bit_length() - 1
    if index >= class_count:
        raise GenerationFailed(f"GRAPH-ROUTE {name} mask is out of range")
    return index


def _hidden_stratum(ordinal: int) -> tuple[int, int]:
    if ordinal < 4:
        return 0, ordinal
    if ordinal < 8:
        return 1, ordinal - 4
    if ordinal < 16:
        return 2, ordinal - 8
    return 3, ordinal - 16


def _require_32_bytes(value: bytes, name: str) -> None:
    if not isinstance(value, bytes) or len(value) != 32:
        raise GenerationFailed(f"{name} must contain exactly 32 bytes")


def _validate_generated_challenge(challenge: GeneratedChallenge) -> None:
    """Reject mutable-object drift before deriving solution-bound test cases."""

    if not isinstance(challenge, GeneratedChallenge):
        raise GenerationFailed("hidden tests require a generated challenge")
    if (
        challenge.context.difficulty_index not in SUPPORTED_DIFFICULTIES
        or challenge.mode_id not in (0, 1, 2)
    ):
        raise GenerationFailed("generated challenge uses an unsupported profile or mode")
    try:
        fields_match = (
            len(challenge.value) == 18
            and challenge.value[0] == 0
            and challenge.value[1] == FAMILY_ID
            and challenge.value[2] == FAMILY_VERSION
            and challenge.value[3] == challenge.context.chain_id
            and challenge.value[4] == challenge.context.protocol_version
            and challenge.value[5] == challenge.context.round_id
            and challenge.value[6] == challenge.context.ticket_id
            and challenge.value[7] == challenge.context.adjustment_epoch
            and challenge.value[8] == challenge.context.difficulty_index
            and challenge.value[9] == challenge.mode_id
            and challenge.value[10] == MODE_VERSION
            and challenge.value[11] == challenge.task_spec
            and challenge.value[12] == challenge.input_type
            and challenge.value[13] == challenge.output_type
            and challenge.value[14] == challenge.public_examples
            and challenge.value[15] == EXECUTION_PROFILE_ID
            and challenge.value[16] == challenge.context.difficulty_index
            and challenge.value[17] == TEST_POLICY_ID
        )
    except (IndexError, TypeError):
        fields_match = False
    if not fields_match:
        raise GenerationFailed("generated challenge fields are internally inconsistent")
    if encode(challenge.value) != challenge.challenge_bytes:
        raise GenerationFailed("generated challenge fields no longer match canonical bytes")
    expected_id = hash_bytes(
        CODE_SYNTH_CHALLENGE_ID,
        (challenge.challenge_bytes,),
    )
    if challenge.challenge_id != expected_id:
        raise GenerationFailed("generated challenge ID does not match canonical bytes")
    expected_root = derive_instance_root(challenge.context, challenge.challenge_seed)
    if challenge.instance_root != expected_root:
        raise GenerationFailed("generated challenge Instance Root is inconsistent")
    regenerated = generate_challenge(challenge.context, challenge.challenge_seed)
    if regenerated.challenge_bytes != challenge.challenge_bytes:
        raise GenerationFailed("generated challenge bytes do not reproduce from finalized inputs")
