# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/model.py — do not edit.
"""Consensus-observable CODE-SYNTH v0 value objects and failures.

The objects in this module carry already-finalized protocol context into the
family generator. Validation is intentionally limited to structural bounds;
ticket eligibility, Host finality, and seed authorization remain responsibilities
of later protocol layers. A new field or interpretation requires a new frozen
family schema rather than an optional value here.
"""

from __future__ import annotations

from dataclasses import dataclass


GENERATION_FAILED = "GENERATION_FAILED"


class GenerationFailed(Exception):
    """A deterministic generator failure for which no fallback is permitted."""

    code = GENERATION_FAILED

    def __init__(self, reason: str, *, instance_root: bytes | None = None) -> None:
        super().__init__(reason)
        self.reason = reason
        self.instance_root = instance_root


class ReferenceEvaluationFailed(Exception):
    """The frozen reference evaluator could not produce a bounded result."""


@dataclass(frozen=True, slots=True)
class ChallengeContext:
    """Finalized fields bound into a CODE-SYNTH Instance Root."""

    chain_id: bytes
    protocol_version: int
    family_version: int
    round_id: int
    ticket_id: bytes
    adjustment_epoch: int
    difficulty_index: int

    def __post_init__(self) -> None:
        if not isinstance(self.chain_id, bytes) or not 1 <= len(self.chain_id) <= 64:
            raise GenerationFailed("chain_id must contain 1 through 64 bytes")
        _require_uint(self.protocol_version, 32, "protocol_version")
        _require_uint(self.family_version, 16, "family_version")
        if self.family_version != 0:
            raise GenerationFailed("CODE-SYNTH v0 requires family_version 0")
        _require_uint(self.round_id, 64, "round_id")
        if not isinstance(self.ticket_id, bytes) or len(self.ticket_id) != 32:
            raise GenerationFailed("ticket_id must contain exactly 32 bytes")
        _require_uint(self.adjustment_epoch, 64, "adjustment_epoch")
        _require_uint(self.difficulty_index, 32, "difficulty_index")


def _require_uint(value: int, bits: int, name: str) -> None:
    if type(value) is not int or not 0 <= value < 1 << bits:
        raise GenerationFailed(f"{name} must be an unsigned {bits}-bit integer")
