# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/primitives.py — do not edit.
"""Domain-separated byte and sampling primitives for CODE-SYNTH v0.

SHA3-256 and SHAKE256 are fixed by the accepted family specification. Sampling
uses bounded rejection rather than modulo reduction, and labeled coordinates are
tracked during generation so one pseudorandom word cannot silently acquire two
semantic meanings. These primitives consume caller-supplied finalized seeds;
they do not obtain entropy or select a production randomness source.
"""

from __future__ import annotations

import hashlib
from collections.abc import Callable, Iterable, Sequence

from ares_lite._core.canonical.domains import CODE_SYNTH_XOF_WORD
from ares_lite._core.canonical.hashing import TranscriptHashingError
from ares_lite._core.canonical.hashing import frame as _shared_frame
from ares_lite._core.canonical.hashing import hash_bytes as _shared_hash_bytes
from ares_lite._core.canonical.hashing import u16_be as _shared_u16_be
from ares_lite._core.canonical.hashing import u32_be as _shared_u32_be
from ares_lite._core.canonical.hashing import u64_be as _shared_u64_be

from .model import GenerationFailed


UINT64_MAX = (1 << 64) - 1
UINT64_MODULUS = 1 << 64
XOF_WORD_DOMAIN = CODE_SYNTH_XOF_WORD


def u16_be(value: int) -> bytes:
    return _translate_hashing_error(_shared_u16_be, value)


def u32_be(value: int) -> bytes:
    return _translate_hashing_error(_shared_u32_be, value)


def u64_be(value: int) -> bytes:
    return _translate_hashing_error(_shared_u64_be, value)


def frame(domain: str, parts: Iterable[bytes]) -> bytes:
    """Frame a purpose domain and byte parts without ambiguous concatenation."""

    try:
        return _shared_frame(domain, parts)
    except TranscriptHashingError as exc:
        raise GenerationFailed(str(exc)) from exc


def hash_bytes(domain: str, parts: Iterable[bytes]) -> bytes:
    try:
        return _shared_hash_bytes(domain, parts)
    except TranscriptHashingError as exc:
        raise GenerationFailed(str(exc)) from exc


def word(root: bytes, label: str, index: int, retry: int) -> bytes:
    if not isinstance(root, bytes) or len(root) != 32:
        raise GenerationFailed("sampler root must contain exactly 32 bytes")
    try:
        encoded_label = label.encode("ascii", errors="strict")
    except (AttributeError, UnicodeEncodeError) as exc:
        raise GenerationFailed("sampler labels must be ASCII text") from exc
    payload = frame(
        XOF_WORD_DOMAIN,
        (root, encoded_label, u64_be(index), u16_be(retry)),
    )
    return hashlib.shake_256(payload).digest(8)


def sample_u(root: bytes, label: str, index: int, lo: int, hi: int) -> int:
    if type(lo) is not int or type(hi) is not int or not 0 <= lo <= hi <= UINT64_MAX:
        raise GenerationFailed("unsigned sampling range is invalid")
    width = hi - lo + 1
    limit = (UINT64_MODULUS // width) * width
    for retry in range(128):
        candidate = int.from_bytes(word(root, label, index, retry), "big")
        if candidate < limit:
            return lo + candidate % width
    raise GenerationFailed("unbiased range sampling exhausted 128 retries")


def sample_s(root: bytes, label: str, index: int, lo: int, hi: int) -> int:
    if type(lo) is not int or type(hi) is not int or not -(1 << 63) <= lo <= hi < 1 << 63:
        raise GenerationFailed("signed sampling range is invalid")
    return lo + sample_u(root, label, index, 0, hi - lo)


class CoordinateSampler:
    """Reject semantic reuse of a labeled sampler coordinate under one root.

    Reusing a coordinate would couple values that the specification treats as
    independent. The tracker turns that implementation error into a terminal
    generation failure instead of silently producing correlated challenges.
    """

    __slots__ = ("root", "_used")

    def __init__(self, root: bytes) -> None:
        if not isinstance(root, bytes) or len(root) != 32:
            raise GenerationFailed("sampler root must contain exactly 32 bytes")
        self.root = root
        self._used: set[tuple[str, int]] = set()

    def u(self, label: str, index: int, lo: int, hi: int) -> int:
        self._reserve(label, index)
        return sample_u(self.root, label, index, lo, hi)

    def s(self, label: str, index: int, lo: int, hi: int) -> int:
        self._reserve(label, index)
        return sample_s(self.root, label, index, lo, hi)

    def permute(self, label: str, values: Sequence[int | tuple[int, int]]) -> list[int | tuple[int, int]]:
        result = list(values)
        for index in range(len(result) - 1, 0, -1):
            swap_index = self.u(label, index, 0, index)
            result[index], result[swap_index] = result[swap_index], result[index]
        return result

    def _reserve(self, label: str, index: int) -> None:
        if type(index) is not int or not 0 <= index <= UINT64_MAX:
            raise GenerationFailed("sampler index must be a u64")
        coordinate = (label, index)
        if coordinate in self._used:
            raise GenerationFailed("sampler coordinate was reused")
        self._used.add(coordinate)


def _translate_hashing_error(function: Callable[[int], bytes], value: int) -> bytes:
    try:
        return function(value)
    except TranscriptHashingError as exc:
        raise GenerationFailed(str(exc)) from exc
