# GENERATED by lite/release/build_sdk.py from the frozen private module (SDK package root) — do not edit.
"""ARES Lite participant SDK — DEVNET / TEST-ONLY. Season Zero is POINTS-ONLY.

Everything a participant or an independent verifier needs to reproduce
challenge -> encoding -> commitment -> reveal -> score, without the private
ARES repository. See README.md and SPEC.md in the SDK root.
"""

from __future__ import annotations

from pathlib import Path

PACKAGE_ROOT = Path(__file__).resolve().parent
# The starter solver crate ships inside the package; build caches go to the user's cache dir.
LITE_ROOT = PACKAGE_ROOT
SDK_VERSION = "0.1.0"
PROFILE_STATUS = "DEVNET/TEST-ONLY"
