# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/leaderboard.py — do not edit.
"""Season Zero leaderboard + return-iteration metrics (NON-consensus; points only).

Rows are per reward address: rank, best score (integer basis points of
improvement over the baseline), submissions, history and voluntary metadata.
While the season runs, scores come from the public practice board (anyone can
reproduce it). After results are published, the FINAL hidden-case scores from
`results.json` replace them. Ranking: best score (higher is better), then the
earliest commit reaching it. Identical modules from many wallets do not help:
a revealed solution identical to an EARLIER commit from another address is
marked `duplicate_of` and earns no score or rank here; under a reward policy
equal scores rank by the earliest commit and only one winner is paid.
"""

from __future__ import annotations

from .metrics import season_metrics


def _bps(baseline: int, fuel: int) -> int:
    return (baseline - fuel) * 10_000 // baseline if baseline > 0 else 0


def build(commits: list[tuple[int, str]], revealed: set[int], practice_rows: list[dict], baseline_practice_fuel: int,
          results: dict | None, received: dict[int, int], metadata: dict[int, dict], b58=lambda h: h,
          solution_hashes: dict[int, str] | None = None) -> list[dict]:
    """`commits`: [(commit_seq, address_hex)]; `practice_rows`: practice_board() rows;
    `received`: commit_seq -> unix time the operator accepted it (non-consensus);
    `solution_hashes`: commit_seq -> revealed solution hash (copy detection)."""

    first_owner: dict[str, tuple[int, str]] = {}
    duplicate_of: dict[int, int] = {}
    for seq, address in sorted(commits):
        h = (solution_hashes or {}).get(seq)
        if h is None:
            continue
        owner = first_owner.setdefault(h, (seq, address))
        if owner[1] != address:
            duplicate_of[seq] = owner[0]

    final = None
    if results:
        base = results["baseline"]["fuel"]
        final = {r["commit_seq"]: (r["valid"], _bps(base, r["score"]) if r["valid"] else None) for r in results["score_table"]}
    practice = {r["commit_seq"]: (r["valid"], _bps(baseline_practice_fuel, r["practice_fuel"]) if r["valid"] else None)
                for r in practice_rows}
    rows: dict[str, dict] = {}
    for seq, address in sorted(commits):
        row = rows.setdefault(address, {"address": address, "address_b58": b58(address), "submissions": 0, "revealed": 0,
                                        "valid": 0, "best_score_bps": None, "best_commit_seq": None, "history": [],
                                        "first_commit_unix": received.get(seq), "last_commit_unix": None, "metadata": {}})
        valid, score = (final or practice).get(seq, (None, None))
        if seq in duplicate_of:
            score = None  # a copy of another address's earlier solution: no credit
        row["submissions"] += 1
        row["revealed"] += seq in revealed
        row["valid"] += bool(valid)
        row["last_commit_unix"] = received.get(seq)
        row["history"].append({"commit_seq": seq, "revealed": seq in revealed, "valid": valid, "score_bps": score,
                               "unix": received.get(seq), "solver": metadata.get(seq, {}).get("solver"),
                               "duplicate_of": duplicate_of.get(seq)})
        if score is not None and (row["best_score_bps"] is None or score > row["best_score_bps"]):
            row["best_score_bps"], row["best_commit_seq"] = score, seq
        for key in ("pool", "solver"):
            if metadata.get(seq, {}).get(key):
                row["metadata"][key] = metadata[seq][key]
        if metadata.get(seq, {}).get("ai_agents"):
            row["metadata"]["ai_agents"] = metadata[seq]["ai_agents"]
    ordered = sorted(rows.values(), key=lambda r: (r["best_score_bps"] is None, -(r["best_score_bps"] or 0),
                                                   r["best_commit_seq"] if r["best_commit_seq"] is not None else 1 << 62))
    for i, row in enumerate(ordered, 1):
        row["rank"] = i if row["best_score_bps"] is not None else None
        row["score_source"] = "final (hidden cases)" if final else "practice (public cases, live)"
    return ordered


def metrics(commits: list[tuple[int, str]], practice_rows: list[dict], baseline_practice_fuel: int, results: dict | None,
            metadata_rows: list[dict]) -> dict:
    """Return-iteration metrics; uses final results when published, else the live practice board."""

    if results is None:
        results = {"baseline": {"fuel": baseline_practice_fuel},
                   "score_table": [{"commit_seq": r["commit_seq"], "valid": r["valid"], "score": r["practice_fuel"]}
                                   for r in practice_rows]}
        source = "practice (live)"
    else:
        source = "final"
    out = season_metrics(commits, results, metadata_rows)
    out["score_source"] = source
    return out
