# GENERATED by lite/release/build_sdk.py from the frozen private module lite/cli/ares_lite.py — do not edit.
#!/usr/bin/env python3
"""ARES Lite command line (DEVNET/TEST-ONLY).

Operator flow:   new-season -> open -> [commit/reveal ...] -> close-commits
                 -> close-reveals -> finalize -> verify-season -> web
Participant:     build -> practice -> commit -> reveal -> claim
Chain (devnet or a local validator; mainnet endpoints are refused), program v4
(frozen economics: 100M fixed, founder vesting, 24 h epochs, remaining-reserve caps):
                 chain-genesis -> verify-fixed-supply -> chain-create-season (season id = epoch index)
                 -> [season] -> close-reveals -> chain-close (inside the epoch's close window:
                 pins log head + cap = floor(A * 379735 / 1e9))
                 -> finalize (reads the on-chain cap) -> verify-season -> chain-publish
                 -> [public verification window: anyone re-runs verify-season]
                 -> chain-finalize (permissionless) -> chain-claim;
                 chain-withdraw + chain-republish (ONE correction, only inside the window);
                 chain-expire (permissionless, after a missed deadline); release-vested;
                 supply; bounty-fund/award (5% recycled, no burn); season-metrics
Everything:      demo  (local, optional --rpc for a local validator / devnet)

Private keys are only ever read from / written to paths outside the repo
(default ~/.config/ares-lite/).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import sys
from pathlib import Path


from ares_lite import PROFILE_STATUS  # noqa: E402
from ares_lite import domains, solana_client as sc  # noqa: E402
from ares_lite.evaluation import benchmark_cases, evaluate  # noqa: E402
from ares_lite.pipeline import baseline_reveal, finalize, module_sha256, practice_board  # noqa: E402
from ares_lite.policies import POLICIES  # noqa: E402
from ares_lite.season import Beacon, RewardRules, SeasonManifest, practice_seed, season_challenge  # noqa: E402
from ares_lite.submission import CLOSE_REVEALS, canonical_solution, commitment_for, reveal_bytes_for  # noqa: E402
from ares_lite.tooling import Workdir, build_solver, source_sha256  # noqa: E402

KEY_HOME = Path(os.environ.get("ARES_LITE_KEYS", Path.home() / ".config" / "ares-lite"))


def _build_target(manifest) -> tuple[str, list[str]]:
    """(build.sh profile, implied cargo features) for a season."""

    if manifest.challenge_profile == "lite-L1":
        return "L1", ["scaled"]
    return str(manifest.difficulty_index), []


def _receipt_key(path):
    if not path:
        return None
    return sc.Keypair.load(Path(path))


def _signed(work, key, entry) -> dict | None:
    if key is None:
        return None
    from ares_lite.transparency import sign_receipt

    manifest = work.manifest()
    if manifest.receipt_signer and key.public.hex() != manifest.receipt_signer:
        raise SystemExit("receipt key does not match the manifest's receipt_signer")
    receipt = sign_receipt(key, manifest.manifest_hash(), entry).to_json()
    with open(work.path / "receipts_signed.jsonl", "a") as handle:
        handle.write(json.dumps(receipt, sort_keys=True) + "\n")
    return receipt


def _print(obj) -> None:
    print(json.dumps(obj, indent=2, sort_keys=True))


def _beacon(args, slot: int) -> Beacon:
    if getattr(args, "rpc", None):
        # The first produced block at/after the declared slot is the beacon.
        _, value = sc.Rpc(args.rpc).beacon(slot)
        return Beacon("solana-slot-blockhash", slot, value.hex())
    if not args.test_beacon:
        raise SystemExit("need --rpc (real beacon) or --test-beacon HEX (localnet only)")
    return Beacon("test-fixed", slot, args.test_beacon)


# ------------------------------------------------------------ operator


def cmd_new_season(args) -> None:
    manifest = SeasonManifest(
        schema=domains.SEASON_MANIFEST,
        season_id=args.season_id,
        name=args.name,
        network=args.network,
        chain_id=args.chain_id,
        protocol_version=1,
        difficulty_index=args.difficulty,
        adjustment_epoch=0,
        challenge_beacon_slot=args.beacon_slot,
        reward_beacon_delay_slots=args.delay,
        rewards=RewardRules(args.cap, args.threshold_bps, args.seeds, args.cases),
        baseline_source_sha256=source_sha256(),
        financial_value=False,
        notes=tuple(args.note or ()),
        challenge_profile=args.profile,
        scaled=tuple(int(x) for x in args.scaled.split(",")) if args.profile == "lite-L1" else (),
        reward_policy=args.policy,
        receipt_signer=sc.Keypair.load(Path(args.receipt_key)).public.hex() if args.receipt_key else "",
        reference_features=tuple(args.reference_features or ()),
    )
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(manifest.to_json())
    _print({"manifest": str(args.out), "manifest_hash": manifest.manifest_hash().hex()})


def _build_references(work: Workdir, manifest) -> dict:
    """Build the ratchet references for this season's constants (deterministic,
    like the baseline). Their hashes are published at open in references.json."""

    target, implied = _build_target(manifest)
    hashes = {}
    for name in manifest.reference_features:
        module = build_solver(target, work.season_rs_file.read_text(), implied + name.split("+"))
        work.references_dir.mkdir(exist_ok=True)
        (work.references_dir / f"{name}.wasm").write_bytes(module)
        hashes[name] = module_sha256(module).hex()
    if hashes:
        (work.path / "references.json").write_text(json.dumps(hashes, indent=2, sort_keys=True) + "\n")
    return hashes


def _check_references(work: Workdir) -> dict:
    """Independent check: rebuild every reference from the pinned source."""

    manifest = work.manifest()
    if not manifest.reference_features:
        return {}
    target, implied = _build_target(manifest)
    out = {}
    for name in manifest.reference_features:
        rebuilt = build_solver(target, work.season_rs_file.read_text(), implied + name.split("+"))
        out[name] = rebuilt == (work.references_dir / f"{name}.wasm").read_bytes()
    return out


def cmd_open(args) -> None:
    work = Workdir(args.workdir)
    work.path.mkdir(parents=True, exist_ok=True)
    manifest = SeasonManifest.load(args.manifest)
    if manifest.baseline_source_sha256 != source_sha256():
        raise SystemExit("starter solver source differs from the manifest pin")
    work.manifest_file.write_text(manifest.to_json())
    beacon = _beacon(args, manifest.challenge_beacon_slot)
    work.beacon_file.write_text(json.dumps(beacon.__dict__) + "\n")
    challenge = season_challenge(manifest, beacon)
    work.write_public_challenge(challenge)
    target, implied = _build_target(manifest)
    baseline = build_solver(target, work.season_rs_file.read_text(), implied)
    work.baseline_file.write_bytes(baseline)
    references = _build_references(work, manifest)
    log = work.log()
    log.open(beacon.bytes(), module_sha256(baseline))
    log.save(work.log_file)
    _print({
        "challenge_id": challenge.challenge_id.hex(),
        "task_spec": challenge.task_spec,
        "baseline_module_sha256": module_sha256(baseline).hex(),
        "reference_module_sha256s": references,
        "log_head": log.head.hex(),
    })


def cmd_close_commits(args) -> None:
    work = Workdir(args.workdir)
    log = work.log()
    entry = log.close_commits()
    log.save(work.log_file)
    _print({"seq": entry.seq, "head": entry.head.hex(), "receipt": _signed(work, _receipt_key(args.receipt_key), entry)})


def cmd_close_reveals(args) -> None:
    work = Workdir(args.workdir)
    log = work.log()
    slot = sc.Rpc(args.rpc).slot() if args.rpc else args.close_slot
    if slot is None:
        raise SystemExit("need --rpc or --close-slot")
    entry = log.close_reveals(slot)
    log.save(work.log_file)
    _signed(work, _receipt_key(args.receipt_key), entry)
    _print({"seq": entry.seq, "head": entry.head.hex(), "close_slot": slot,
            "reward_beacon_slot": slot + work.manifest().reward_beacon_delay_slots})


def _onchain_season(work: Workdir) -> dict | None:
    if not work.chain_file.exists():
        return None
    chain = _chain(work)
    account = sc.Rpc(chain["rpc"]).account(_lite(chain).season(work.manifest().season_id))
    return sc.parse_season(account["raw"]) if account else None


def _epoch_reward(work: Workdir, override: int | None) -> tuple[int | None, str]:
    """The allocation cap of this epoch. With a chain it is the season's
    on-chain close_cap (fixed at chain-close, = ARES unlocked by the schedule
    since the previous settlement, bounded by MAX_EPOCH_SECONDS); nobody
    chooses it. Off-chain runs may pass --epoch-reward explicitly."""

    season = _onchain_season(work)
    if season is not None:
        if season["status"] == "OPEN":
            raise SystemExit("run chain-close first: the epoch cap is fixed when the season is closed on-chain")
        log_head = work.log().entries[-1].head.hex()
        if season["log_head"] != log_head:
            raise SystemExit("on-chain pinned log head differs from the local receipt log")
        if override is not None and override != season["close_cap"]:
            raise SystemExit("--epoch-reward disagrees with the on-chain close_cap")
        return season["close_cap"], "on-chain season.close_cap"
    return override, "--epoch-reward" if override is not None else "manifest season_cap (no chain)"


def cmd_finalize(args) -> None:
    import time

    work = Workdir(args.workdir)
    manifest, log = work.manifest(), work.log()
    close_slot = log.entries[-1].fields[0]
    epoch_reward, source = _epoch_reward(work, args.epoch_reward)
    beacon = _beacon(args, close_slot + manifest.reward_beacon_delay_slots)
    work.reward_beacon_file.write_text(json.dumps(beacon.__dict__) + "\n")
    started = time.monotonic()
    result = finalize(manifest, work.challenge(), log, beacon, work.baseline_file.read_bytes(),
                      work.reference_modules(), epoch_reward)
    elapsed = time.monotonic() - started
    data = json.loads(result.table.to_json())
    data["epoch_reward_cap"] = epoch_reward
    data["epoch_reward_source"] = source
    data["evaluation_cost"] = {  # metadata only: not part of any digest
        "wall_seconds": round(elapsed, 3), "submissions": len(result.evaluations),
        "total_fuel": sum(ev.benchmark_fuel + sum(r.fuel_charged for r in ev.gate_results)
                          for _, _, _, ev in result.evaluations)}
    data["log_head"] = result.log_head.hex()
    data["baseline"] = {"fuel": result.baseline.benchmark_fuel, "evaluation_digest": result.baseline.digest().hex()}
    data["evaluations"] = [
        {"commit_seq": seq, "address": addr.hex(), "address_b58": sc.b58encode(addr), "solution_hash": sol.hex(),
         "valid": ev.valid, "reason": ev.reason, "benchmark_fuel": ev.benchmark_fuel,
         "gate_fuel": [r.fuel_charged for r in ev.gate_results], "evaluation_digest": ev.digest().hex()}
        for seq, addr, sol, ev in result.evaluations
    ]
    data["score_table_digest"] = result.score_digest.hex()
    data["score_table"] = [{"commit_seq": r.commit_seq, "address": r.address.hex(), "solution_hash": r.solution_hash.hex(),
                            "valid": r.valid, "score": r.score} for r in result.score_rows]
    if result.shadow is not None:
        data["shadow_telescoping_v0"] = {"totals": [list(t) for t in result.shadow.totals], "total": result.shadow.total,
                                         "note": "data only; order-dependent (lite/sim/results/reward_order.json)"}
    data["merkle_root"] = result.merkle_root.hex()
    data["profile"] = PROFILE_STATUS
    work.results_file.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n")
    _print({"merkle_root": data["merkle_root"], "total": result.table.total, "epoch_reward_cap": epoch_reward,
            "winners": [sc.b58encode(bytes.fromhex(a)) for a, _ in result.table.totals],
            "score_table_digest": data["score_table_digest"], "log_head": result.log_head.hex()})


def cmd_verify_season(args) -> None:
    """Independent recomputation from public artefacts only."""

    work = Workdir(args.workdir)
    published = json.loads(work.results_file.read_text())
    beacon = Beacon(**json.loads(work.reward_beacon_file.read_text()))
    epoch_reward, _ = _epoch_reward(work, published.get("epoch_reward_cap"))
    result = finalize(work.manifest(), work.challenge(), work.log(), beacon, work.baseline_file.read_bytes(),
                      work.reference_modules(), epoch_reward)
    from ares_lite.transparency import check_closed_log

    entries = [json.loads(line) for line in work.log_file.read_text().splitlines()]
    check_closed_log(entries)
    ok = (
        result.merkle_root.hex() == published["merkle_root"]
        and result.table.digest().hex() == published["table_digest"]
        and result.score_digest.hex() == published.get("score_table_digest", result.score_digest.hex())
        and published["log_head"] == entries[-1]["head"] == result.log_head.hex()
        and published.get("epoch_reward_cap") == epoch_reward
    )
    season = _onchain_season(work)
    if season is not None and season["status"] in ("PUBLISHED", "CORRECTED", "FINAL"):
        ok = ok and season["reward_root"] == result.merkle_root.hex() \
            and season["reward_total"] == result.table.total \
            and season["results_digest"] == result.score_digest.hex()
    references = {} if args.skip_rebuild else _check_references(work)
    ok = ok and all(references.values())
    _print({"reproduced": ok, "merkle_root": result.merkle_root.hex(), "epoch_reward_cap": epoch_reward,
            "references_rebuilt_identically": references or None})
    if not ok:
        raise SystemExit(1)


def cmd_board(args) -> None:
    work = Workdir(args.workdir)
    _print(practice_board(work.challenge(), work.log()))


# --------------------------------------------------------- participant


def cmd_build(args) -> None:
    work = Workdir(args.workdir)
    target, implied = _build_target(work.manifest())
    module = build_solver(target, work.season_rs_file.read_text(), sorted(set(implied + args.features)))
    Path(args.out).write_bytes(module)
    _print({"module": str(args.out), "bytes": len(module), "sha256": hashlib.sha256(module).hexdigest()})


def cmd_practice(args) -> None:
    """Self-test on PUBLIC practice seeds (not reward-critical)."""

    work = Workdir(args.workdir)
    manifest, challenge = work.manifest(), work.challenge()
    module = Path(args.module).read_bytes()
    reveal, record = baseline_reveal(manifest, challenge, module)
    cases = benchmark_cases(challenge, practice_seed(challenge, 1), args.cases)
    evaluation = evaluate(challenge, reveal, record, [practice_seed(challenge, 0)], cases)
    _print({"valid": evaluation.valid, "reason": evaluation.reason, "practice_fuel": evaluation.benchmark_fuel})


def _address(text: str) -> bytes:
    raw = sc.b58decode(text) if len(text) != 64 else bytes.fromhex(text)
    if len(raw) != 32:
        raise SystemExit("address must be a base58 Solana public key")
    return raw


def cmd_commit(args) -> None:
    work = Workdir(args.workdir)
    manifest, challenge = work.manifest(), work.challenge()
    module = Path(args.module).read_bytes()
    address = _address(args.address)
    salt = os.urandom(32)
    solution = canonical_solution(challenge, module)
    commitment = commitment_for(manifest, challenge, address, solution, salt)
    log = work.log()
    entry = log.commit(address, commitment)
    log.save(work.log_file)
    secret = Path(args.secret_out)
    if Path(__file__).resolve().parents[1] in secret.resolve().parents:
        raise SystemExit("keep the reveal secret outside the repository")
    secret.parent.mkdir(parents=True, exist_ok=True)
    receipt = _signed(work, _receipt_key(args.receipt_key), entry)
    secret.write_text(json.dumps({"commit_seq": entry.seq, "salt": salt.hex(), "module": str(Path(args.module).resolve()),
                                  "commit_receipt": receipt}))
    if args.pool or args.agent:
        # Optional, self-declared, never scored and never in the commitment.
        with work.metadata_file.open("a") as fh:
            fh.write(json.dumps({"commit_seq": entry.seq, "address": address.hex(), "pool": args.pool or "",
                                 "ai_agents": sorted(set(args.agent or ()))}, sort_keys=True) + "\n")
    _print({"commit_seq": entry.seq, "commitment": commitment.hex(), "head": entry.head.hex(), "receipt": receipt})


def cmd_reveal(args) -> None:
    work = Workdir(args.workdir)
    manifest, challenge = work.manifest(), work.challenge()
    secret = json.loads(Path(args.secret).read_text())
    module = Path(secret["module"]).read_bytes()
    raw = reveal_bytes_for(manifest, challenge, canonical_solution(challenge, module), bytes.fromhex(secret["salt"]))
    log = work.log()
    entry = log.reveal(secret["commit_seq"], raw)
    log.save(work.log_file)
    receipt = _signed(work, _receipt_key(args.receipt_key), entry)
    if receipt:
        secret["reveal_receipt"] = receipt
        Path(args.secret).write_text(json.dumps(secret))
    _print({"seq": entry.seq, "head": entry.head.hex(), "receipt": receipt})


def cmd_check_receipt(args) -> None:
    """Participant: prove the published log honours my signed receipt."""

    from ares_lite.transparency import SignedReceipt, TransparencyViolation, check_receipt_against_log

    work = Workdir(args.workdir)
    manifest = work.manifest()
    if not manifest.receipt_signer:
        raise SystemExit("this season has no receipt signer")
    secret = json.loads(Path(args.secret).read_text())
    entries = [json.loads(line) for line in work.log_file.read_text().splitlines()]
    report = {}
    for key in ("commit_receipt", "reveal_receipt"):
        if secret.get(key):
            try:
                check_receipt_against_log(bytes.fromhex(manifest.receipt_signer), SignedReceipt.from_json(secret[key]), entries)
                report[key] = "honoured"
            except TransparencyViolation as exc:
                report[key] = f"VIOLATION: {exc}"
    _print(report)


# --------------------------------------------------------------- chain


def _key(path: str | None, name: str) -> sc.Keypair:
    path = Path(path) if path else KEY_HOME / f"{name}.json"
    if not path.exists():
        kp = sc.Keypair.generate()
        kp.save(path)
        print(f"created {name} keypair at {path} (outside the repository)", file=sys.stderr)
    return sc.Keypair.load(path)


def _chain(work: Workdir) -> dict:
    return json.loads(work.chain_file.read_text())


def _lite(chain: dict) -> "sc.LiteProgram":
    return sc.LiteProgram(sc.b58decode(chain["program_id"]), sc.b58decode(chain["mint"]))


def genesis(rpc: "sc.Rpc", deployer: "sc.Keypair", program_id: bytes, founder_wallet: bytes,
            epoch_seconds: int = 86_400) -> dict:
    """Create the SPL mint and run the program's ATOMIC genesis:
    exactly 100M ARES; 10M -> founder VESTING vault (PDA); 90M -> mining vault (PDA);
    mint authority revoked (None); freeze authority never set."""

    from ares_lite import tokenomics as tk

    mint = sc.Keypair.generate()  # throwaway signer for the mint address only
    rpc.send(deployer, [
        sc.create_account_ix(deployer.public, mint.public, rpc.rent(82), 82, sc.TOKEN_PROGRAM),
        sc.initialize_mint_ix(mint.public, tk.DECIMALS, deployer.public),
    ], [mint])
    lite = sc.LiteProgram(program_id, mint.public)
    signature = rpc.send(deployer, [lite.initialize(deployer.public, founder_wallet, epoch_seconds)])
    return {"program_id": sc.b58encode(program_id), "mint": sc.b58encode(mint.public),
            "founder_wallet": sc.b58encode(founder_wallet),
            "founder_token_account": sc.b58encode(sc.associated_token_address(founder_wallet, mint.public)),
            "founder_vesting_vault": sc.b58encode(lite.founder_vault),
            "founder_vesting_authority_pda": sc.b58encode(lite.founder_authority),
            "config": sc.b58encode(lite.config), "reward_vault": sc.b58encode(lite.vault),
            "vault_authority_pda": sc.b58encode(lite.vault_authority), "admin": deployer.address,
            "genesis_signature": signature, "epoch_seconds": epoch_seconds}


def cmd_chain_genesis(args) -> None:
    rpc, work = sc.Rpc(args.rpc), Workdir(args.workdir)
    deployer = _key(args.admin_key, "admin")
    if args.airdrop:
        rpc.airdrop(deployer.public, 2_000_000_000)
    founder = sc.b58decode(args.founder_wallet)
    chain = genesis(rpc, deployer, sc.b58decode(args.program_id), founder, args.epoch_seconds)
    chain["rpc"] = args.rpc
    work.path.mkdir(parents=True, exist_ok=True)
    work.chain_file.write_text(json.dumps(chain, indent=2) + "\n")
    _print(chain)


def cmd_verify_fixed_supply(args) -> None:
    """Release gate: prints the supply facts and fails on any violation."""

    from ares_lite.supply import mint_death_test, snapshot, verify_fixed_supply

    chain = _chain(Workdir(args.workdir)) if args.workdir else {"rpc": args.rpc, "program_id": args.program_id, "mint": args.mint}
    rpc = sc.Rpc(args.rpc or chain["rpc"])
    program_id, mint = sc.b58decode(chain["program_id"]), sc.b58decode(chain["mint"])
    snap = snapshot(rpc, program_id, mint)
    passed = verify_fixed_supply(snap, at_genesis=args.at_genesis, production=args.production)
    report = {key: snap[key] for key in ("mint", "current_supply", "mint_authority", "freeze_authority",
                                         "founder_vault", "founder_vault_balance", "mining_vault",
                                         "mining_vault_balance", "available_reserve", "next_epoch_cap", "epoch_seconds")}
    report["checks_passed"] = passed
    if args.death_test_key:
        signers = {f"key:{Path(p).name}": sc.Keypair.load(Path(p)) for p in args.death_test_key}
        signers["random_attacker"] = sc.Keypair.generate()
        if args.airdrop_attacker:
            rpc.airdrop(signers["random_attacker"].public, 50_000_000)
        lite = sc.LiteProgram(program_id, mint)
        destination = sc.b58decode(snap["founder_token_account"])
        report["additional_mint_attempts"] = mint_death_test(
            rpc, mint, destination, signers,
            {"vault_authority_pda": lite.vault_authority, "founder_authority_pda": lite.founder_authority,
             "config_pda": lite.config},
            unsigned={"founder (unsigned simulation)": sc.b58decode(snap["founder"])})
    if args.simulate_bounty:
        from ares_lite.supply import simulate_bounty

        report["simulated_bounty"] = simulate_bounty(rpc, program_id, mint, sc.b58decode(args.simulate_bounty),
                                                     1_000 * 10**6, 2**63 + 1)
    _print(report)


def cmd_supply(args) -> None:
    from ares_lite.supply import snapshot

    chain = _chain(Workdir(args.workdir))
    snap = snapshot(sc.Rpc(args.rpc or chain["rpc"]), sc.b58decode(chain["program_id"]), sc.b58decode(chain["mint"]))
    snap["genesis_signature"] = chain.get("genesis_signature")
    if getattr(args, "html", None):
        from ares_lite.render import render_supply

        Path(args.html).write_text(render_supply(snap))
    _print(snap)


def cmd_chain_create_season(args) -> None:
    work = Workdir(args.workdir)
    chain, manifest = _chain(work), work.manifest()
    rpc, admin = sc.Rpc(chain["rpc"]), _key(args.admin_key, "admin")
    lite = _lite(chain)
    signature = rpc.send(admin, [lite.create_epoch(admin.public, manifest.season_id, manifest.manifest_hash())])
    _print({"epoch_pda": sc.b58encode(lite.epoch(manifest.season_id)), "epoch": manifest.season_id, "signature": signature})


def cmd_epoch_budget(args) -> None:
    """Reserve accounting right now: A = V - P - O and the cap the next close pins."""

    from ares_lite.supply import snapshot

    chain = _chain(Workdir(args.workdir))
    snap = snapshot(sc.Rpc(chain["rpc"]), sc.b58decode(chain["program_id"]), sc.b58decode(chain["mint"]))
    _print({key: snap[key] for key in ("mining_vault_balance", "pending_reserved", "outstanding_unclaimed",
                                       "available_reserve", "next_epoch_cap", "mining_awarded_total",
                                       "recycled_total", "last_closed_epoch", "current_epoch", "epoch_seconds")})


def cluster_time(rpc: "sc.Rpc") -> int:
    """The cluster clock (what the program sees), not this machine's clock."""

    return rpc.call("getBlockTime", [rpc.slot()]) or 0


def wait_for_close_window(rpc: "sc.Rpc", chain_config: dict, epoch: int, margin: int = 2) -> None:
    import time

    from ares_lite import tokenomics as tk

    opens, ends = tk.close_window(chain_config["genesis_ts"], epoch, chain_config["epoch_seconds"])
    now = cluster_time(rpc)
    if now >= ends:
        raise SystemExit(f"epoch {epoch}: close window already ended at {ends} (cluster time {now})")
    while cluster_time(rpc) < opens + margin:
        time.sleep(1)


def cmd_chain_close(args) -> None:
    """Pin the closed receipt-log head on-chain inside the epoch's close window;
    the program fixes cap = floor(A * 379,735 / 1e9) at this moment (R1: the
    whole cap is HELD until finalize/expire)."""

    work = Workdir(args.workdir)
    chain, manifest, log = _chain(work), work.manifest(), work.log()
    last = log.entries[-1]
    if log.phase != CLOSE_REVEALS:
        raise SystemExit("close-reveals first: only a closed receipt log can be pinned")
    rpc, admin = sc.Rpc(chain["rpc"]), _key(args.admin_key, "admin")
    lite = _lite(chain)
    if args.wait:
        wait_for_close_window(rpc, sc.parse_config(rpc.account(lite.config)["raw"]), manifest.season_id)
    signature = rpc.send(admin, [lite.close_epoch(admin.public, manifest.season_id, last.head, last.fields[0])])
    epoch = sc.parse_epoch(rpc.account(lite.epoch(manifest.season_id))["raw"])
    _print({"signature": signature, "log_head": epoch["log_head"], "close_slot": epoch["close_slot"],
            "epoch_reward_cap": epoch["cap"], "publish_deadline": epoch["deadline"]})


def _publish(args, correction: bool) -> None:
    work = Workdir(args.workdir)
    chain, manifest, results = _chain(work), work.manifest(), json.loads(work.results_file.read_text())
    rpc, admin = sc.Rpc(chain["rpc"]), _key(args.admin_key, "admin")
    lite = _lite(chain)
    build = lite.republish if correction else lite.publish
    signature = rpc.send(admin, [build(admin.public, manifest.season_id, bytes.fromhex(results["merkle_root"]),
                                       results["total"], bytes.fromhex(results["log_head"]),
                                       bytes.fromhex(results["score_table_digest"]))])
    epoch = sc.parse_epoch(rpc.account(lite.epoch(manifest.season_id))["raw"])
    _print({"signature": signature, "status": epoch["status"], "merkle_root": results["merkle_root"],
            "total": results["total"], "claim_open_ts": epoch["claim_open_ts"],
            "note": "verification window: anyone can run verify-season before claims open"})


def cmd_chain_publish(args) -> None:
    _publish(args, False)


def cmd_chain_republish(args) -> None:
    """R2: the ONE correction, after chain-withdraw and before the original claim_open_ts."""

    _publish(args, True)


def cmd_chain_withdraw(args) -> None:
    """R2: withdraw the published result once, strictly inside the verification
    window. The original root/total stay on-chain; the republish deadline is
    the original claim_open_ts; nothing is re-reserved."""

    work = Workdir(args.workdir)
    chain, manifest = _chain(work), work.manifest()
    rpc, admin = sc.Rpc(chain["rpc"]), _key(args.admin_key, "admin")
    lite = _lite(chain)
    signature = rpc.send(admin, [lite.withdraw(admin.public, manifest.season_id)])
    _print({"signature": signature, "epoch": sc.parse_epoch(rpc.account(lite.epoch(manifest.season_id))["raw"])})


def _permissionless(args, build, label) -> None:
    work = Workdir(args.workdir)
    chain, manifest = _chain(work), work.manifest()
    rpc, payer = sc.Rpc(chain["rpc"]), sc.Keypair.load(Path(args.key)) if args.key else _key(None, "admin")
    lite = _lite(chain)
    signature = rpc.send(payer, [build(lite)(manifest.season_id)])
    _print({label: signature, "epoch": sc.parse_epoch(rpc.account(lite.epoch(manifest.season_id))["raw"])})


def cmd_chain_finalize(args) -> None:
    _permissionless(args, lambda lite: lite.finalize, "finalize_signature")


def cmd_chain_expire(args) -> None:
    _permissionless(args, lambda lite: lite.expire, "expire_signature")


def cmd_chain_season(args) -> None:
    work = Workdir(args.workdir)
    season = _onchain_season(work)
    if season is None:
        raise SystemExit("season account not found")
    _print(season)


def cmd_chain_verify(args) -> None:
    """Clean-client check: season account and supply invariants == published artefacts."""

    from ares_lite.supply import snapshot, verify_fixed_supply

    work = Workdir(args.workdir)
    chain, manifest = _chain(work), work.manifest()
    results = json.loads(work.results_file.read_text())
    rpc = sc.Rpc(args.rpc or chain["rpc"])
    lite = _lite(chain)
    account = rpc.account(lite.season(manifest.season_id))
    if account is None:
        raise SystemExit("season account not found")
    season = sc.parse_season(account["raw"])
    checks = {
        "season_owner_is_program": account["owner"] == chain["program_id"],
        "status_published_or_final": season["status"] in ("PUBLISHED", "CORRECTED", "FINAL"),
        "season_id": season["season_id"] == manifest.season_id,
        "manifest_hash": season["manifest_hash"] == manifest.manifest_hash().hex(),
        "reward_root": season["reward_root"] == results["merkle_root"],
        "reward_total": season["reward_total"] == results["total"],
        "log_head": season["log_head"] == results["log_head"],
        "results_digest": season["results_digest"] == results["score_table_digest"],
        "total_le_epoch_cap": season["reward_total"] <= season["close_cap"],
        "epoch_cap_matches_results": season["close_cap"] == results.get("epoch_reward_cap"),
        "claimed_le_total": season["claimed"] <= results["total"],
    }
    snap = snapshot(rpc, sc.b58decode(chain["program_id"]), sc.b58decode(chain["mint"]))
    try:
        for name in verify_fixed_supply(snap):
            checks[name] = True
    except Exception as exc:  # noqa: BLE001 - reported as a failed check
        checks[f"fixed_supply: {exc}"] = False
    _print({"checks": checks, "all_ok": all(checks.values())})
    if not all(checks.values()):
        raise SystemExit(1)


def cmd_chain_negative(args) -> None:
    """Real-RPC negative checks; every attempt must FAIL on-chain."""

    work = Workdir(args.workdir)
    chain, manifest, results = _chain(work), work.manifest(), json.loads(work.results_file.read_text())
    rpc, admin = sc.Rpc(chain["rpc"]), _key(args.admin_key, "admin")
    mint = sc.b58decode(chain["mint"])
    lite = _lite(chain)
    victim_hex, amount = results["totals"][0]
    proof = [bytes.fromhex(p) for p in results["proofs"][victim_hex]]
    attacker = sc.Keypair.generate()
    # Exact need: its token-account rent + the ATA-create and cleanup fees. Every
    # attack below is rejected at preflight, which charges no fee.
    # (+ the wallet's own rent-exempt minimum while it is non-empty; all returned by the final sweep).
    rpc.airdrop(attacker.public, rpc.rent(sc.TOKEN_ACCOUNT_LEN) + rpc.rent(0) + 3 * sc.LAMPORTS_PER_SIGNATURE)
    rpc.send(attacker, [sc.create_ata_idempotent_ix(attacker.public, attacker.public, mint)])
    attacker_ata = sc.associated_token_address(attacker.public, mint)
    outcome = {}

    def expect_failure(label, payer, ixs, signers=()):
        """Must be rejected BY THE PROGRAM (or SPL Token), not for lack of fees or accounts."""
        try:
            rpc.send(payer, ixs, list(signers))
            outcome[label] = "UNEXPECTED SUCCESS"
        except RuntimeError as exc:
            text = str(exc)
            found = re.search(r"Error processing Instruction \d+: ([^'\"]+)", text)
            outcome[label] = f"rejected: {found.group(1).strip()}" if found else f"WRONG REASON: {text[:160]}"

    expect_failure("wrong_wallet", attacker, [lite.claim(attacker.public, manifest.season_id, amount, proof, attacker_ata)])
    expect_failure("forged_amount", attacker, [lite.claim(attacker.public, manifest.season_id, amount + 1, proof, attacker_ata)])
    # A scratch epoch far in the future: created (OPEN), never closable now.
    other = args.scratch_season if args.scratch_season is not None else manifest.season_id + 100_000
    rpc.send(admin, [lite.create_epoch(admin.public, other, bytes(32))])
    expect_failure("publish_before_close", admin, [lite.publish(admin.public, other, bytes(32), 0, bytes(32), bytes(32))])
    expect_failure("close_outside_window", admin, [lite.close_epoch(admin.public, other, bytes(32), 1)])
    expect_failure("non_admin_close", attacker, [lite.close_epoch(attacker.public, manifest.season_id, bytes(32), 1)])
    expect_failure("non_admin_withdraw", attacker, [lite.withdraw(attacker.public, manifest.season_id)])
    expect_failure("withdraw_after_claims_open", admin, [lite.withdraw(admin.public, manifest.season_id)])
    expect_failure("wrong_season", attacker, [lite.claim(attacker.public, other, amount, proof, attacker_ata)])
    if args.winner_key:
        winner = sc.Keypair.load(Path(args.winner_key))
        w_amount = dict(results["totals"])[winner.public.hex()]
        w_proof = [bytes.fromhex(p) for p in results["proofs"][winner.public.hex()]]
        expect_failure("double_claim", winner, [lite.claim(winner.public, manifest.season_id, w_amount, w_proof,
                                                           sc.associated_token_address(winner.public, mint))])
        expect_failure("claim_to_foreign_token_account", winner, [lite.claim(winner.public, manifest.season_id, w_amount,
                                                                             w_proof, attacker_ata)])
    expect_failure("root_replacement", admin, [lite.publish(admin.public, manifest.season_id, bytes(32), 0,
                                                            bytes.fromhex(results["log_head"]), bytes(32))])
    expect_failure("republish_without_withdraw", admin, [lite.republish(admin.public, manifest.season_id, bytes(32), 0,
                                                                        bytes.fromhex(results["log_head"]), bytes(32))])
    expect_failure("non_admin_create_epoch", attacker, [lite.create_epoch(attacker.public, other + 2, bytes(32))])
    expect_failure("attacker_releases_founder_vesting", attacker, [lite.release_vested(attacker.public, attacker_ata)])
    expect_failure("mint_by_former_authority", admin, [sc.mint_to_ix(mint, attacker_ata, admin.public, 1)])
    expect_failure("mint_by_attacker", attacker, [sc.mint_to_ix(mint, attacker_ata, attacker.public, 1)])
    vault_drain = sc.Ix(sc.TOKEN_PROGRAM, (sc.Meta(lite.vault, False, True), sc.Meta(attacker_ata, False, True),
                                           sc.Meta(admin.public, True, False)), bytes([3]) + (1).to_bytes(8, "little"))
    expect_failure("admin_drains_vault", admin, [vault_drain])
    founder_drain = sc.Ix(sc.TOKEN_PROGRAM, (sc.Meta(lite.founder_vault, False, True), sc.Meta(attacker_ata, False, True),
                                             sc.Meta(admin.public, True, False)), bytes([3]) + (1).to_bytes(8, "little"))
    expect_failure("admin_drains_founder_vesting_vault", admin, [founder_drain])
    outcome["attacker_balance"] = sc.token_balance(rpc, attacker_ata)
    if outcome["attacker_balance"] == 0:  # clean up: close the empty ATA, return all SOL to the payer of the run
        rpc.send(attacker, [sc.close_token_account_ix(attacker_ata, attacker.public, attacker.public)])
        outcome["attacker_sol_returned"] = rpc.sweep(attacker, admin.public)
    _print(outcome)
    if any(str(v).startswith(("UNEXPECTED SUCCESS", "WRONG REASON")) for v in outcome.values()) or outcome["attacker_balance"]:
        raise SystemExit(1)


def cmd_chain_claim(args) -> None:
    work = Workdir(args.workdir)
    chain, manifest, results = _chain(work), work.manifest(), json.loads(work.results_file.read_text())
    rpc = sc.Rpc(chain["rpc"])
    claimant = sc.Keypair.load(Path(args.key))
    mint = sc.b58decode(chain["mint"])
    if args.airdrop:  # exact need: receipt PDA + ATA rent + one fee (if the ATA does not exist yet)
        need = rpc.rent(sc.CLAIM_RECEIPT_LEN) + sc.LAMPORTS_PER_SIGNATURE  # ends at exactly 0 lamports (allowed)
        if rpc.account(sc.associated_token_address(claimant.public, mint)) is None:
            need += rpc.rent(sc.TOKEN_ACCOUNT_LEN)
        if rpc.balance(claimant.public) < need:
            rpc.airdrop(claimant.public, need - rpc.balance(claimant.public))
    amounts = dict((address, amount) for address, amount in results["totals"])
    amount = amounts.get(claimant.public.hex())
    if not amount:
        raise SystemExit("no reward for this address")
    proof = [bytes.fromhex(p) for p in results["proofs"][claimant.public.hex()]]
    season = _onchain_season(work)
    if not args.skip_window_check and season and season["status"] != "FINAL" and cluster_time(rpc) < season["claim_open_ts"]:
        raise SystemExit(f"verification window: claims open at unix {season['claim_open_ts']}")
    ata = sc.associated_token_address(claimant.public, mint)
    ixs = [sc.create_ata_idempotent_ix(claimant.public, claimant.public, mint)]
    if season and season["status"] in ("PUBLISHED", "CORRECTED") and not args.skip_finalize:
        ixs.append(_lite(chain).finalize(manifest.season_id))  # permissionless; same transaction
    ixs.append(_lite(chain).claim(claimant.public, manifest.season_id, amount, proof, ata))
    signature = rpc.send(claimant, ixs)
    _print({"signature": signature, "amount": amount, "token_account": sc.b58encode(ata), "balance": sc.token_balance(rpc, ata)})


def cmd_bounty_fund(args) -> None:
    """Fund a bounty from your own tokens: 5% is recycled into the mining vault, 95% escrowed, nothing burned."""

    from ares_lite import tokenomics as tk

    chain = _chain(Workdir(args.workdir))
    rpc, funder = sc.Rpc(chain["rpc"]), sc.Keypair.load(Path(args.key))
    mint = sc.b58decode(chain["mint"])
    lite = _lite(chain)
    ata = sc.associated_token_address(funder.public, mint)
    supply_before = sc.parse_mint(rpc.account(mint)["raw"])["supply"]
    vault_before = sc.token_balance(rpc, lite.vault)
    signature = rpc.send(funder, [lite.fund_bounty(funder.public, ata, args.bounty_id, args.amount)])
    fee, escrow = tk.bounty_split(args.amount)
    _print({"signature": signature, "amount": args.amount, "recycled_fee": fee, "escrowed": escrow,
            "escrow_balance": sc.token_balance(rpc, lite.escrow(args.bounty_id)),
            "mining_vault_delta": sc.token_balance(rpc, lite.vault) - vault_before,
            "supply_before": supply_before, "supply_after": sc.parse_mint(rpc.account(mint)["raw"])["supply"]})


def cmd_release_vested(args) -> None:
    """Founder only: release vested(now) - released from the vesting vault."""

    from ares_lite import tokenomics as tk

    chain = _chain(Workdir(args.workdir))
    rpc, founder = sc.Rpc(chain["rpc"]), sc.Keypair.load(Path(args.key))
    mint = sc.b58decode(chain["mint"])
    lite = _lite(chain)
    ata = sc.associated_token_address(founder.public, mint)
    config = sc.parse_config(rpc.account(lite.config)["raw"])
    signature = rpc.send(founder, [sc.create_ata_idempotent_ix(founder.public, founder.public, mint),
                                   lite.release_vested(founder.public, ata)])
    after = sc.parse_config(rpc.account(lite.config)["raw"])
    _print({"signature": signature, "released": after["founder_claimed"] - config["founder_claimed"],
            "founder_released_total": after["founder_claimed"], "founder_balance": sc.token_balance(rpc, ata),
            "founder_vault_balance": sc.token_balance(rpc, lite.founder_vault),
            "vested_formula_now": tk.vested(after["genesis_ts"], cluster_time(rpc), after["epoch_seconds"])})


def cmd_bounty_award(args) -> None:
    chain = _chain(Workdir(args.workdir))
    rpc, admin = sc.Rpc(chain["rpc"]), _key(args.admin_key, "admin")
    mint = sc.b58decode(chain["mint"])
    winner = sc.b58decode(args.winner)
    rpc.send(admin, [sc.create_ata_idempotent_ix(admin.public, winner, mint)])
    destination = sc.associated_token_address(winner, mint)
    signature = rpc.send(admin, [_lite(chain).award_bounty(admin.public, args.bounty_id, destination)])
    _print({"signature": signature, "winner_token_account": sc.b58encode(destination),
            "winner_balance": sc.token_balance(rpc, destination)})


def cmd_season_metrics(args) -> None:
    from ares_lite.metrics import season_metrics
    from ares_lite.submission import COMMIT

    work = Workdir(args.workdir)
    commits = [(e.seq, e.fields[0].hex()) for e in work.log().entries if e.kind == COMMIT]
    results = json.loads(work.results_file.read_text())
    metadata = [json.loads(line) for line in work.metadata_file.read_text().splitlines()] if work.metadata_file.exists() else []
    _print(season_metrics(commits, results, metadata))


# ---------------------------------------------------------------- main


def main(argv=None) -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="command", required=True)

    p = sub.add_parser("new-season")
    p.add_argument("--out", required=True)
    p.add_argument("--season-id", type=int, default=0)
    p.add_argument("--name", default="Season Zero")
    p.add_argument("--network", default="solana-devnet", choices=["solana-devnet", "localnet"])
    p.add_argument("--chain-id", default="ares-lite-solana-devnet")
    p.add_argument("--difficulty", type=int, default=2)
    p.add_argument("--cap", type=int, default=1_000_000 * 10**6)
    p.add_argument("--threshold-bps", type=int, default=100)
    p.add_argument("--seeds", type=int, default=2)
    p.add_argument("--cases", type=int, default=64)
    p.add_argument("--beacon-slot", type=int, required=True)
    p.add_argument("--delay", type=int, default=150)
    p.add_argument("--note", action="append")
    p.add_argument("--profile", default="code-synth-v0", choices=["code-synth-v0", "lite-L1"])
    p.add_argument("--scaled", default="24,32,130,32,8,8,5,30000000,50000000",
                   help="lite-L1 ScaledConfig: vmin,vmax,edge_max,cost_max,resource_max,hops,classes,fuel/test,ref_steps")
    p.add_argument("--policy", default="telescoping_v0", choices=sorted(POLICIES))
    p.add_argument("--receipt-key", help="operator receipt keypair (outside the repo); its pubkey is pinned")
    p.add_argument("--reference-features", action="append",
                   help="public solver variant(s) (e.g. compact, memo+bound) that must be beaten: ratchet baseline")
    p.set_defaults(func=cmd_new_season)

    for name, func in (("open", cmd_open), ("finalize", cmd_finalize)):
        p = sub.add_parser(name)
        p.add_argument("--workdir", required=True)
        if name == "open":
            p.add_argument("--manifest", required=True)
        else:
            p.add_argument("--epoch-reward", type=int, help="off-chain runs only; with a chain the on-chain close_cap is used")
        p.add_argument("--rpc")
        p.add_argument("--test-beacon")
        p.set_defaults(func=func)

    for name, func in (("close-commits", cmd_close_commits), ("verify-season", cmd_verify_season), ("board", cmd_board)):
        p = sub.add_parser(name)
        p.add_argument("--workdir", required=True)
        if name == "close-commits":
            p.add_argument("--receipt-key")
        if name == "verify-season":
            p.add_argument("--skip-rebuild", action="store_true", help="do not rebuild the ratchet references")
        p.set_defaults(func=func)

    p = sub.add_parser("check-receipt")
    p.add_argument("--workdir", required=True)
    p.add_argument("--secret", required=True)
    p.set_defaults(func=cmd_check_receipt)

    p = sub.add_parser("close-reveals")
    p.add_argument("--workdir", required=True)
    p.add_argument("--rpc")
    p.add_argument("--close-slot", type=int)
    p.add_argument("--receipt-key")
    p.set_defaults(func=cmd_close_reveals)

    p = sub.add_parser("build")
    p.add_argument("--workdir", required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--features", nargs="*", default=[])
    p.set_defaults(func=cmd_build)

    p = sub.add_parser("practice")
    p.add_argument("--workdir", required=True)
    p.add_argument("--module", required=True)
    p.add_argument("--cases", type=int, default=16)
    p.set_defaults(func=cmd_practice)

    p = sub.add_parser("commit")
    p.add_argument("--workdir", required=True)
    p.add_argument("--module", required=True)
    p.add_argument("--address", required=True)
    p.add_argument("--secret-out", required=True)
    p.add_argument("--receipt-key", help="operator receipt key (operator-run CLI only)")
    p.add_argument("--pool", help="optional, self-declared pool name (metadata, never scored)")
    p.add_argument("--agent", action="append", help="optional, self-declared AI agent/tool used (metadata, never scored)")
    p.set_defaults(func=cmd_commit)

    p = sub.add_parser("reveal")
    p.add_argument("--workdir", required=True)
    p.add_argument("--secret", required=True)
    p.add_argument("--receipt-key", help="operator receipt key (operator-run CLI only)")
    p.set_defaults(func=cmd_reveal)

    p = sub.add_parser("chain-genesis", help="create mint + atomic fixed-supply genesis (devnet/local)")
    p.add_argument("--workdir", required=True)
    p.add_argument("--rpc", required=True)
    p.add_argument("--program-id", required=True)
    p.add_argument("--founder-wallet", required=True,
                   help="founder beneficiary (base58): 10M ARES vest to it (1-year cliff, linear to year 5)")
    p.add_argument("--admin-key")
    p.add_argument("--airdrop", action="store_true")
    p.add_argument("--epoch-seconds", type=int, default=86_400,
                   help="86400 in production; shorter values only on the devnet-time-scale build")
    p.set_defaults(func=cmd_chain_genesis)

    p = sub.add_parser("verify-fixed-supply", help="release gate: fixed-supply invariants + mint death test")
    p.add_argument("--workdir")
    p.add_argument("--rpc")
    p.add_argument("--program-id")
    p.add_argument("--mint")
    p.add_argument("--at-genesis", action="store_true")
    p.add_argument("--death-test-key", action="append", help="keypair files to attempt (simulated) minting with")
    p.add_argument("--airdrop-attacker", action="store_true")
    p.add_argument("--simulate-bounty", metavar="FUNDER", help="simulate a 1,000 ARES bounty from FUNDER (commits nothing)")
    p.add_argument("--production", action="store_true", help="also require 24 h epochs (mainnet gate)")
    p.set_defaults(func=cmd_verify_fixed_supply)

    for name, func in (("supply", cmd_supply), ("epoch-budget", cmd_epoch_budget)):
        p = sub.add_parser(name)
        p.add_argument("--workdir", required=True)
        p.add_argument("--rpc")
        if name == "supply":
            p.add_argument("--html", help="also write the ARES Supply page")
        p.set_defaults(func=func)

    for name, func in (("chain-create-season", cmd_chain_create_season), ("chain-publish", cmd_chain_publish),
                       ("chain-close", cmd_chain_close), ("chain-withdraw", cmd_chain_withdraw),
                       ("chain-republish", cmd_chain_republish), ("chain-season", cmd_chain_season)):
        p = sub.add_parser(name)
        p.add_argument("--workdir", required=True)
        p.add_argument("--admin-key")
        if name == "chain-close":
            p.add_argument("--wait", action="store_true", help="wait (cluster clock) for the epoch's close window")
        p.set_defaults(func=func)

    for name, func in (("chain-finalize", cmd_chain_finalize), ("chain-expire", cmd_chain_expire)):
        p = sub.add_parser(name, help="permissionless")
        p.add_argument("--workdir", required=True)
        p.add_argument("--key", help="any fee payer")
        p.set_defaults(func=func)

    p = sub.add_parser("release-vested", help="founder: release the vested amount")
    p.add_argument("--workdir", required=True)
    p.add_argument("--key", required=True)
    p.set_defaults(func=cmd_release_vested)

    p = sub.add_parser("chain-negative")
    p.add_argument("--workdir", required=True)
    p.add_argument("--admin-key")
    p.add_argument("--winner-key")
    p.add_argument("--scratch-season", type=int, help="unused season id for negative tests")
    p.set_defaults(func=cmd_chain_negative)

    p = sub.add_parser("chain-verify")
    p.add_argument("--workdir", required=True)
    p.add_argument("--rpc")
    p.set_defaults(func=cmd_chain_verify)

    p = sub.add_parser("chain-claim")
    p.add_argument("--workdir", required=True)
    p.add_argument("--key", required=True)
    p.add_argument("--airdrop", action="store_true")
    p.add_argument("--skip-window-check", action="store_true", help="send anyway (to show the on-chain rejection)")
    p.add_argument("--skip-finalize", action="store_true", help="do not prepend the permissionless finalize")
    p.set_defaults(func=cmd_chain_claim)

    p = sub.add_parser("season-metrics", help="Season Zero product metrics (return iterations etc.)")
    p.add_argument("--workdir", required=True)
    p.set_defaults(func=cmd_season_metrics)

    p = sub.add_parser("bounty-fund")
    p.add_argument("--workdir", required=True)
    p.add_argument("--key", required=True)
    p.add_argument("--bounty-id", type=int, required=True)
    p.add_argument("--amount", type=int, required=True, help="base units (6 decimals)")
    p.set_defaults(func=cmd_bounty_fund)

    p = sub.add_parser("bounty-award")
    p.add_argument("--workdir", required=True)
    p.add_argument("--bounty-id", type=int, required=True)
    p.add_argument("--winner", required=True)
    p.add_argument("--admin-key")
    p.set_defaults(func=cmd_bounty_award)

    args = parser.parse_args(argv)
    args.func(args)


if __name__ == "__main__":
    main()
