# GENERATED by lite/release/build_sdk.py from the frozen private module lite/backend/server.py — do not edit.
#!/usr/bin/env python3
"""Minimal ARES Lite operator HTTP backend (stdlib only, single-threaded).

    python3 lite/backend/server.py --workdir SEASON [--port 8787]

GET  /                season page (rendered on request)
GET  /challenge       public challenge JSON
GET  /manifest        season manifest JSON
GET  /beacon          challenge beacon (lets clients recompute the challenge)
GET  /season.rs       solver constants for the starter kit
GET  /baseline.wasm   the season baseline module
GET  /agent.md        brief to hand to an AI coding agent
GET  /supply          ARES Supply page (from on-chain state; needs chain.json)
GET  /supply.json     the same as JSON
GET  /log             receipt log (JSON lines, with chain heads)
GET  /head            current log head
GET  /board           live practice board (public seeds, NOT reward-critical)
GET  /status          phase (OPEN / CLOSE_COMMITS / CLOSE_REVEALS), head, counts, results availability
GET  /leaderboard     per-address rank, best score (bps vs baseline), submissions, history, metadata
GET  /metrics         Season Zero return-iteration metrics (points only)
GET  /results.json    published results (after finalize)      GET /reward_beacon.json
GET  /references.json reference module hashes; GET /references/<name>.wasm
POST /commit          {"address": base58|hex, "commitment": hex, ["pool": str, "ai_agents": [str], "solver": str]}  (metadata optional, never scored)
POST /reveal          {"commit_seq": int, "reveal": hex canonical reveal bytes}

With --receipt-key, every accepted entry returns an Ed25519-signed receipt over
(manifest_hash, seq, head); signed receipts are also appended to
receipts_signed.jsonl for periodic publication as checkpoints.

The server holds no keys. Every accepted request is appended to the receipt
log; the returned head is the participant's receipt. Rejections append
nothing. Limits are deliberately small (body size, one request at a time).
"""

from __future__ import annotations

import argparse
import json
import time
import sys
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path


from ares_lite import solana_client as sc  # noqa: E402
from ares_lite.pipeline import practice_board  # noqa: E402
from ares_lite.submission import SubmissionRejected  # noqa: E402
from ares_lite.tooling import Workdir  # noqa: E402

MAX_BODY = 200_000  # reveal hex of a 128 KiB profile-2 module plus envelope


def make_handler(work: Workdir, receipt_key=None):
    board_cache: dict[str, object] = {}

    def baseline_practice_fuel() -> int:
        if "baseline_fuel" not in board_cache:
            from ares_lite.evaluation import benchmark_cases, evaluate
            from ares_lite.pipeline import baseline_reveal
            from ares_lite.season import practice_seed

            challenge = work.challenge()
            reveal, record = baseline_reveal(work.manifest(), challenge, work.baseline_file.read_bytes())
            cases = benchmark_cases(challenge, practice_seed(challenge, 1), 16)
            board_cache["baseline_fuel"] = evaluate(challenge, reveal, record, [practice_seed(challenge, 0)], cases).benchmark_fuel
        return board_cache["baseline_fuel"]

    def received() -> dict[int, int]:
        path = work.path / "received.jsonl"
        if not path.exists():
            return {}
        return {row["seq"]: row["unix"] for row in map(json.loads, path.read_text().splitlines()) if row.get("kind") == "commit"}

    def metadata_rows() -> list[dict]:
        if not work.metadata_file.exists():
            return []
        return [json.loads(line) for line in work.metadata_file.read_text().splitlines() if line.strip()]

    def results() -> dict | None:
        return json.loads(work.results_file.read_text()) if work.results_file.exists() else None

    def commits_and_revealed(log) -> tuple[list[tuple[int, str]], set[int]]:
        from ares_lite.submission import COMMIT

        commits = [(e.seq, e.fields[0].hex()) for e in log.entries if e.kind == COMMIT]
        return commits, set(log.reveals)

    def board() -> list:
        # Practice evaluation is expensive (seconds per solver for lite-L1):
        # recompute only when the log head changes.
        log = work.log()
        key = log.head.hex()
        if board_cache.get("head") != key:
            board_cache["head"], board_cache["rows"] = key, practice_board(work.challenge(), log)
        return board_cache["rows"]

    class Handler(BaseHTTPRequestHandler):
        server_version = "ares-lite/0"

        def _send(self, status: int, body: bytes, ctype: str = "application/json") -> None:
            self.send_response(status)
            self.send_header("Content-Type", ctype)
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)

        def _json(self, status: int, obj) -> None:
            self._send(status, (json.dumps(obj, indent=2) + "\n").encode())

        def do_GET(self) -> None:  # noqa: N802
            try:
                if self.path == "/":
                    from ares_lite.render import render

                    self._send(200, render(work).encode(), "text/html; charset=utf-8")
                elif self.path == "/challenge":
                    self._send(200, work.challenge_file.read_bytes())
                elif self.path == "/beacon":
                    self._send(200, work.beacon_file.read_bytes())
                elif self.path == "/season.rs":
                    self._send(200, work.season_rs_file.read_bytes(), "text/plain; charset=utf-8")
                elif self.path == "/baseline.wasm":
                    self._send(200, work.baseline_file.read_bytes(), "application/wasm")
                elif self.path == "/agent.md":
                    from ares_lite.render import agent_brief

                    self._send(200, agent_brief(work).encode(), "text/markdown; charset=utf-8")
                elif self.path in ("/supply", "/supply.json") and work.chain_file.exists():
                    from ares_lite.supply import snapshot
                    from ares_lite import solana_client as client

                    chain = json.loads(work.chain_file.read_text())
                    snap = snapshot(client.Rpc(chain["rpc"]), client.b58decode(chain["program_id"]), client.b58decode(chain["mint"]))
                    if self.path == "/supply.json":
                        self._json(200, snap)
                    else:
                        from ares_lite.render import render_supply

                        self._send(200, render_supply(snap).encode(), "text/html; charset=utf-8")
                elif self.path == "/manifest":
                    self._send(200, work.manifest_file.read_bytes())
                elif self.path == "/log":
                    self._send(200, work.log_file.read_bytes(), "application/x-ndjson")
                elif self.path == "/head":
                    self._json(200, {"head": work.log().head.hex(), "entries": len(work.log().entries)})
                elif self.path == "/board":
                    self._json(200, board())
                elif self.path == "/status":
                    log = work.log()
                    manifest = work.manifest()
                    commits, revealed = commits_and_revealed(log)
                    self._json(200, {"season": manifest.name, "season_id": manifest.season_id, "network": manifest.network,
                                     "phase": ("OPEN", "OPEN", "OPEN", "CLOSE_COMMITS", "CLOSE_REVEALS")[log.phase],
                                     "phase_code": log.phase, "head": log.head.hex(), "entries": len(log.entries),
                                     "commits": len(commits), "reveals": len(revealed),
                                     "results_published": work.results_file.exists(),
                                     "manifest_hash": manifest.manifest_hash().hex(),
                                     "points_only": manifest.reward_policy == "season_zero_points_v0",
                                     "reward_policy": manifest.reward_policy,
                                     "status": "DEVNET / TEST-ONLY"})
                elif self.path in ("/leaderboard", "/metrics"):
                    from ares_lite import leaderboard

                    log = work.log()
                    commits, revealed = commits_and_revealed(log)
                    meta = metadata_rows()
                    if self.path == "/leaderboard":
                        self._json(200, leaderboard.build(commits, revealed, board(), baseline_practice_fuel(), results(), received(),
                                                          {m["commit_seq"]: m for m in meta},
                                                          lambda h: sc.b58encode(bytes.fromhex(h))))
                    else:
                        self._json(200, leaderboard.metrics(commits, board(), baseline_practice_fuel(), results(), meta))
                elif self.path in ("/results.json", "/reward_beacon.json", "/references.json"):
                    path = work.path / self.path.lstrip("/")
                    if not path.exists():
                        self._json(404, {"error": "not published yet"})
                    else:
                        self._send(200, path.read_bytes())
                elif self.path.startswith("/references/") and self.path.endswith(".wasm"):
                    name = self.path[len("/references/"):-len(".wasm")]
                    if name not in work.manifest().reference_features:  # allowlist: no path traversal
                        self._json(404, {"error": "not found"})
                    else:
                        self._send(200, (work.references_dir / f"{name}.wasm").read_bytes(), "application/wasm")
                else:
                    self._json(404, {"error": "not found"})
            except Exception as exc:  # pragma: no cover - operational guard
                self._json(500, {"error": type(exc).__name__})

        def do_POST(self) -> None:  # noqa: N802
            length = int(self.headers.get("Content-Length", "0"))
            if not 0 < length <= MAX_BODY:
                self._json(413, {"error": "body size"})
                return
            try:
                body = json.loads(self.rfile.read(length))
                log = work.log()
                if self.path == "/commit":
                    text = body["address"]
                    address = bytes.fromhex(text) if len(text) == 64 else sc.b58decode(text)
                    entry = log.commit(address, bytes.fromhex(body["commitment"]))
                    pool, agents, solver = body.get("pool", ""), body.get("ai_agents", []), body.get("solver", "")
                    if not isinstance(agents, list):
                        agents = []
                    if pool or agents or solver:  # optional self-declared metadata; never scored
                        meta = {"commit_seq": entry.seq, "address": address.hex(), "pool": str(pool)[:64],
                                "ai_agents": sorted({str(a)[:64] for a in agents[:16]}), "solver": str(solver)[:64]}
                        with work.metadata_file.open("a") as handle:
                            handle.write(json.dumps(meta, sort_keys=True) + "\n")
                elif self.path == "/reveal":
                    entry = log.reveal(int(body["commit_seq"]), bytes.fromhex(body["reveal"]))
                else:
                    self._json(404, {"error": "not found"})
                    return
                log.save(work.log_file)
                with (work.path / "received.jsonl").open("a") as handle:  # non-consensus acceptance time
                    handle.write(json.dumps({"seq": entry.seq, "kind": self.path.strip("/"), "unix": int(time.time())}) + "\n")
                receipt = None
                if receipt_key is not None:
                    from ares_lite.transparency import sign_receipt

                    receipt = sign_receipt(receipt_key, work.manifest().manifest_hash(), entry).to_json()
                    with open(work.path / "receipts_signed.jsonl", "a") as handle:
                        handle.write(json.dumps(receipt, sort_keys=True) + "\n")
                self._json(200, {"seq": entry.seq, "head": entry.head.hex(), "receipt": receipt})
            except SubmissionRejected as exc:
                self._json(400, {"error": str(exc)})
            except (KeyError, ValueError, TypeError) as exc:
                self._json(400, {"error": f"malformed request: {type(exc).__name__}"})

        def log_message(self, *args) -> None:
            pass

    return Handler


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workdir", required=True)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=8787)
    parser.add_argument("--receipt-key", help="Ed25519 keypair file (outside the repo) pinned in the manifest")
    args = parser.parse_args()
    work = Workdir(Path(args.workdir))
    key = sc.Keypair.load(Path(args.receipt_key)) if args.receipt_key else None
    if key is not None and work.manifest().receipt_signer != key.public.hex():
        raise SystemExit("receipt key does not match the manifest's receipt_signer")
    server = HTTPServer((args.host, args.port), make_handler(work, key))
    print(f"ARES Lite backend on http://{args.host}:{args.port} (DEVNET/TEST-ONLY)")
    server.serve_forever()


if __name__ == "__main__":
    main()
