# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/pipeline.py — do not edit.
"""Season finalisation: seeds -> evaluations -> reward table -> audit bundle.

Everything here is a pure function of public artefacts (manifest, beacons,
receipt log, baseline module), so any third party can recompute the reward
root bit-for-bit with `ares_lite.py verify-season`.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from .evaluation import Evaluation, benchmark_cases, evaluate
from .policies import POLICIES, ScoreRow, score_table_digest
from .rewards import RewardTable, compute, from_allocation
from .season import (
    Beacon,
    SeasonManifest,
    benchmark_seed,
    practice_seed,
    verification_seeds,
)
from .submission import (
    CLOSE_REVEALS,
    ReceiptLog,
    canonical_solution,
    reveal_bytes_for,
)
from ares_lite._core.code_synth.generator import GeneratedChallenge
from ares_lite._core.commit_reveal import RevealRecord
from ares_lite._core.commit_reveal.transcripts import parse_reveal_submission, reveal_hash, solution_hash

BASELINE_ADDRESS = bytes(32)
BASELINE_SALT = bytes(32)


@dataclass(frozen=True)
class SeasonResult:
    log_head: bytes
    baseline: Evaluation
    evaluations: tuple[tuple[int, bytes, bytes, Evaluation], ...]
    table: RewardTable
    score_rows: tuple[ScoreRow, ...] = ()
    score_digest: bytes = bytes(32)
    shadow: RewardTable | None = None  # telescoping_v0, data only, when not the active policy

    @property
    def merkle_root(self) -> bytes:
        return self.table.merkle()[0] if self.table.totals else bytes(32)


def baseline_reveal(manifest: SeasonManifest, challenge: GeneratedChallenge, module: bytes):
    solution = canonical_solution(challenge, module)
    raw = reveal_bytes_for(manifest, challenge, solution, BASELINE_SALT)
    reveal = parse_reveal_submission(raw)
    record = RevealRecord(challenge.context.ticket_id, challenge.challenge_id, reveal_hash(raw), solution_hash(solution), 0)
    return reveal, record


def module_sha256(module: bytes) -> bytes:
    return hashlib.sha256(module).digest()


def finalize(
    manifest: SeasonManifest,
    challenge: GeneratedChallenge,
    log: ReceiptLog,
    reward_beacon: Beacon,
    baseline_module: bytes,
    reference_modules: list[bytes] = (),
    epoch_reward: int | None = None,
) -> SeasonResult:
    """Deterministic finalisation. Same inputs -> same scores -> same winner ->
    same amount -> same Merkle root, for any client.

    `reference_modules`: builds of the manifest's `reference_features` for this
    season (one per feature set, built like the baseline from the pinned
    source; anyone can rebuild and compare). The effective baseline is the
    best valid of starter + references.
    `epoch_reward`: the on-chain close_cap of the season (read from Solana);
    the allocation cap is min(manifest season_cap, epoch_reward).
    """
    if log.phase != CLOSE_REVEALS:
        raise ValueError("the receipt log must be closed before finalisation")
    open_entry = log.entries[0]
    if open_entry.fields[3] != module_sha256(baseline_module):
        raise ValueError("baseline module differs from the one fixed at season open")
    close_slot = log.entries[-1].fields[0]
    if reward_beacon.slot != close_slot + manifest.reward_beacon_delay_slots:
        raise ValueError("reward beacon slot must equal close_slot + reward_beacon_delay_slots")
    head = log.head
    gate_seeds = verification_seeds(manifest, challenge, head, reward_beacon)
    cases = benchmark_cases(challenge, benchmark_seed(manifest, challenge, head, reward_beacon), manifest.rewards.benchmark_cases)
    reveal, record = baseline_reveal(manifest, challenge, baseline_module)
    baseline = evaluate(challenge, reveal, record, gate_seeds, cases)
    if not baseline.valid:
        raise ValueError(f"baseline failed evaluation: {baseline.reason}")
    if len(reference_modules) != len(manifest.reference_features):
        raise ValueError("one reference module per manifest reference feature set is required")
    for module in reference_modules:
        ref_reveal, ref_record = baseline_reveal(manifest, challenge, module)
        ref = evaluate(challenge, ref_reveal, ref_record, gate_seeds, cases)
        if ref.valid and ref.benchmark_fuel < baseline.benchmark_fuel:
            baseline = ref  # ratchet: copying a known solver cannot beat this
    evaluations = []
    for commit_seq, address, reveal, record in log.revealed():
        evaluations.append((commit_seq, address, record.solution_hash, evaluate(challenge, reveal, record, gate_seeds, cases)))
    # 1) SCORE: technical quality only, independent of any reward policy.
    rows = tuple(
        ScoreRow(seq, address, sol, ev.valid, ev.benchmark_fuel if ev.valid else 0)
        for seq, address, sol, ev in evaluations
    )
    digest = score_table_digest(list(rows), baseline.benchmark_fuel)
    # 2) ALLOCATION: a separate, swappable economic policy over the score table.
    cap, theta = manifest.rewards.season_cap, manifest.rewards.improvement_threshold_bps
    if epoch_reward is not None:
        cap = min(cap, epoch_reward)
    if cap <= 0:
        # Nothing unlocked since the previous settlement: the epoch pays 0,
        # the score table is still produced and published for transparency.
        table = from_allocation(manifest.season_id, 0, theta, baseline.benchmark_fuel, {}, manifest.reward_policy)
        return SeasonResult(head, baseline, tuple(evaluations), table, rows, digest, None)
    telescoping = compute(manifest.season_id, cap, theta, baseline.benchmark_fuel, evaluations)
    if manifest.reward_policy == "telescoping_v0":
        return SeasonResult(head, baseline, tuple(evaluations), telescoping, rows, digest, None)
    allocation = POLICIES[manifest.reward_policy](list(rows), baseline.benchmark_fuel, cap, theta)
    table = from_allocation(manifest.season_id, cap, theta, baseline.benchmark_fuel, allocation, manifest.reward_policy)
    return SeasonResult(head, baseline, tuple(evaluations), table, rows, digest, telescoping)


def practice_board(
    challenge: GeneratedChallenge,
    log: ReceiptLog,
    baseline: tuple | None = None,
    case_count: int = 16,
) -> list[dict]:
    """Live, NON-reward-critical board on public practice seeds.

    Everyone can reproduce and overfit it; it exists for feedback only.
    """

    seed = practice_seed(challenge, 0)
    cases = benchmark_cases(challenge, practice_seed(challenge, 1), case_count)
    rows = []
    for commit_seq, address, reveal, record in log.revealed():
        evaluation = evaluate(challenge, reveal, record, [seed], cases)
        rows.append(
            {
                "commit_seq": commit_seq,
                "address": address.hex(),
                "valid": evaluation.valid,
                "reason": evaluation.reason,
                "practice_fuel": evaluation.benchmark_fuel,
            }
        )
    rows.sort(key=lambda row: (not row["valid"], row["practice_fuel"], row["commit_seq"]))
    return rows
