# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/policies.py — do not edit.
"""Reward / points policies: a pure function of a frozen SCORE TABLE.

Separation of concerns (docs/ares_lite/SCORE_VS_REWARD.md):

- SOLVER SCORE (verifier + scoring): technical quality of a solver. A row is
  (commit_seq, address, solution_hash, valid, score). It never depends on
  tokenomics and is digested independently (`score_table_digest`).
- ALLOCATION POLICY (this module): economic policy mapping a score table to
  amounts/points. Changing a policy never touches the verifier, the scoring,
  or the score table.

Token seasons (Lite economics v0) use `winner_takes_epoch_v0`; points-only
Season Zero may use `best_per_address_points_v0`. Telescoping is kept as a
SHADOW for data only, because it is order-dependent
(lite/sim/results/reward_order.json).
"""

from __future__ import annotations

from dataclasses import dataclass

from . import domains
from ares_lite._core.canonical import encode, hash_bytes

SCORE_TABLE = "ARES-LITE/SCORE-TABLE/v0"


@dataclass(frozen=True)
class ScoreRow:
    commit_seq: int
    address: bytes
    solution_hash: bytes
    valid: bool
    score: int  # lower is better; 0 if invalid


def score_table_digest(rows: list[ScoreRow], baseline_score: int) -> bytes:
    value = [0, baseline_score, [[r.commit_seq, r.address, r.solution_hash, int(r.valid), r.score] for r in rows]]
    return hash_bytes(SCORE_TABLE, (encode(value),))


def telescoping_v0(rows: list[ScoreRow], baseline: int, cap: int, threshold_bps: int) -> dict[bytes, int]:
    """Improvement over best-so-far in commit order (order-dependent)."""

    best, out = baseline, {}
    for row in sorted(rows, key=lambda r: r.commit_seq):
        if not row.valid or row.score >= best or row.score * 10_000 > best * (10_000 - threshold_bps):
            continue
        amount = cap * (best - row.score) // baseline
        best = row.score
        if amount:
            out[row.address] = out.get(row.address, 0) + amount
    return out


def best_per_address_points_v0(rows: list[ScoreRow], baseline: int, cap: int, threshold_bps: int) -> dict[bytes, int]:
    """Order-independent points: each address's best valid score that beats
    the baseline by >= threshold earns points proportional to its improvement
    over the baseline, normalised so the total is at most `cap`.

    Exact duplicates (same solution hash) count once, for the earliest commit
    (the only place order enters). Sybil identities submitting *different*
    solvers are NOT neutralised by this policy (see reward_order.json); this is
    acceptable for points, not for money.
    """

    seen_solutions: set[bytes] = set()
    best: dict[bytes, int] = {}
    for row in sorted(rows, key=lambda r: r.commit_seq):
        if not row.valid or row.solution_hash in seen_solutions:
            continue
        seen_solutions.add(row.solution_hash)
        if row.score * 10_000 > baseline * (10_000 - threshold_bps):
            continue
        if row.address not in best or row.score < best[row.address]:
            best[row.address] = row.score
    gains = {a: baseline - s for a, s in best.items()}
    total_gain = sum(gains.values())
    if not total_gain:
        return {}
    # Pool = cap scaled by the best improvement achieved (unachieved part unminted).
    pool = cap * max(gains.values()) // baseline
    return {a: pool * g // total_gain for a, g in gains.items() if pool * g // total_gain}


def winner_takes_epoch_v0(rows: list[ScoreRow], baseline: int, cap: int, threshold_bps: int) -> dict[bytes, int]:
    """Lite economics v0 (Bitcoin-like): the single best valid solver of the
    epoch receives the whole epoch budget `cap`, provided it beats the
    baseline by >= threshold. Ties (equal score) go to the earliest commit,
    so a copied or re-submitted equal solver never wins. Extra wallets or
    identities add nothing: only the best solver is paid, whoever holds it.
    Small participants smooth variance by joining pools (the reward address
    may be a pool). No winner -> nothing is committed; the unlocked budget
    stays available for later epochs.
    """

    best: ScoreRow | None = None
    for row in sorted(rows, key=lambda r: r.commit_seq):
        if not row.valid or row.score * 10_000 > baseline * (10_000 - threshold_bps):
            continue
        if best is None or row.score < best.score:
            best = row
    return {best.address: cap} if best is not None and cap > 0 else {}


def season_zero_points_v0(rows: list[ScoreRow], baseline: int, cap: int, threshold_bps: int) -> dict[bytes, int]:
    """Season Zero: POINTS ONLY. No token amount is ever allocated, whatever
    the epoch cap is (the on-chain result is published with total 0, which
    releases the whole reservation: no depletion of the mining reserve).
    Ranks and points come from the published score table, whose digest is
    still pinned on-chain. Pinned in the manifest hash, so anyone can check a
    season is points-only before joining."""

    return {}


POLICIES = {
    "season_zero_points_v0": season_zero_points_v0,
    "winner_takes_epoch_v0": winner_takes_epoch_v0,
    "telescoping_v0": telescoping_v0,
    "best_per_address_points_v0": best_per_address_points_v0,
}

_ = domains
