# GENERATED by lite/release/build_sdk.py from the frozen private module lite/web/render.py — do not edit.
#!/usr/bin/env python3
"""Render a static, functional Season page from a season workdir.

No JavaScript, no external assets: rules, challenge, baseline, starter kit,
submission flow, live practice board, final results, progression graph and
reproduction instructions. Branding never touches correctness; this page only
displays artefacts that `ares_lite.py verify-season` can recompute.
"""

from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path


from ares_lite.pipeline import practice_board  # noqa: E402
from ares_lite.tooling import Workdir  # noqa: E402

CSS = """
:root{--bg:#fff;--fg:#1b1b1b;--muted:#5d5d5d;--line:#d9d9d9;--accent:#0b5cad;--ok:#1b7f3b;--bad:#a12020}
@media (prefers-color-scheme:dark){:root{--bg:#121212;--fg:#e8e8e8;--muted:#a5a5a5;--line:#333;--accent:#6aa9ff;--ok:#5fcf86;--bad:#ff7b7b}}
body{background:var(--bg);color:var(--fg);font:15px/1.5 system-ui,sans-serif;max-width:960px;margin:0 auto;padding:16px}
h1{margin:.2em 0}h2{border-bottom:1px solid var(--line);padding-bottom:4px;margin-top:2em}
code,pre{font-family:ui-monospace,monospace;font-size:13px}pre{overflow-x:auto;border:1px solid var(--line);padding:8px}
table{border-collapse:collapse;width:100%;font-size:14px}td,th{border-bottom:1px solid var(--line);padding:4px 6px;text-align:left}
.tag{display:inline-block;border:1px solid var(--bad);color:var(--bad);padding:0 6px;font-size:12px}
.muted{color:var(--muted)}.ok{color:var(--ok)}.bad{color:var(--bad)}.wrap{overflow-x:auto}
svg text{fill:var(--fg);font-size:11px}svg .axis{stroke:var(--line)}svg .line{stroke:var(--accent);fill:none;stroke-width:2}
"""


def esc(value) -> str:
    return html.escape(str(value))


def short(hexstr: str, n: int = 10) -> str:
    return hexstr[:n] + "…" if len(hexstr) > n else hexstr


def progression_svg(baseline: int, awards: list[dict]) -> str:
    points = [(0, baseline)] + [(i + 1, a["new_best"]) for i, a in enumerate(awards)]
    width, height, pad = 640, 220, 40
    top = max(p[1] for p in points)
    xs = max(1, len(points) - 1)
    coords = [
        (pad + (width - 2 * pad) * x / xs, height - pad - (height - 2 * pad) * y / top) for x, y in points
    ]
    path = " ".join(f"{'M' if i == 0 else 'L'}{x:.1f},{y:.1f}" for i, (x, y) in enumerate(coords))
    labels = "".join(f'<text x="{x:.1f}" y="{y - 6:.1f}">{v:,}</text>' for (x, y), (_, v) in zip(coords, points))
    return (
        f'<svg viewBox="0 0 {width} {height}" width="100%" role="img" aria-label="best fuel over accepted improvements">'
        f'<line class="axis" x1="{pad}" y1="{height - pad}" x2="{width - pad}" y2="{height - pad}"/>'
        f'<line class="axis" x1="{pad}" y1="{pad}" x2="{pad}" y2="{height - pad}"/>'
        f'<path class="line" d="{path}"/>{labels}'
        f'<text x="{pad}" y="{height - 10}">baseline → improvements (commit order); y = benchmark fuel, lower is better</text></svg>'
    )


def render_supply(snap: dict) -> str:
    """ARES Supply page: every number is read from on-chain state (supply.snapshot)."""

    unit = 10**6

    def ares(v: int) -> str:
        return f"{v / unit:,.6f}".rstrip("0").rstrip(".") + " ARES"

    rows = [
        ("Total supply (fixed forever)", ares(snap["current_supply"])),
        ("Mint authority", str(snap["mint_authority"]) + "  (None = no one can ever mint)"),
        ("Freeze authority", str(snap["freeze_authority"])),
        ("Mining allocation (90%, at genesis)", ares(snap["mining_allocation"])),
        ("Mining vault balance V", ares(snap["mining_vault_balance"])),
        ("Held for epochs in verification P", ares(snap["pending_reserved"])),
        ("Awarded, not yet claimed O", ares(snap["outstanding_unclaimed"])),
        ("Available reserve A = V - P - O", ares(snap["available_reserve"])),
        ("Next epoch cap = floor(A x 379,735 / 10^9)", ares(snap["next_epoch_cap"])),
        ("Awarded to miners (all time)", ares(snap["mining_awarded_total"])),
        ("Claimed by miners (all time)", ares(snap["mining_claimed_total"])),
        ("Recycled bounty fees (5%)", ares(snap["recycled_total"])),
        ("Epoch length", f"{snap['epoch_seconds']} s"),
        ("Current epoch / last closed", f"{snap['current_epoch']} / {snap['last_closed_epoch']}"),
        ("Genesis", snap["genesis_utc"]),
        ("Mint address", snap["mint"]),
        ("Mining vault", snap["mining_vault"]),
        ("Program", snap["program_id"]),
    ]
    body = "".join(f"<tr><th>{esc(k)}</th><td><code>{esc(v)}</code></td></tr>" for k, v in rows)
    creator = [
        ("Founder beneficiary", snap["founder_beneficiary"]),
        ("Founder vesting vault (PDA)", snap["founder_vault"]),
        ("Founder allocation (10%)", f"{ares(snap['founder_allocation'])} ({snap['founder_allocation']} base units)"),
        ("Vesting", "1-year cliff, then linear until year 5; non-revocable; no admin path"),
        ("Cliff / end", f"{snap['vesting_cliff_utc']} / {snap['vesting_end_utc']}"),
        ("Vested now", ares(snap["founder_vested_now"])),
        ("Released to the founder", ares(snap["founder_released"])),
        ("Still in the vesting vault", ares(snap["founder_vault_balance"])),
        ("Genesis transaction", str(snap.get("genesis_signature") or "see chain.json / RELEASE.json")),
    ]
    creator_body = "".join(f"<tr><th>{esc(k)}</th><td><code>{esc(v)}</code></td></tr>" for k, v in creator)
    return (
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        f"<title>ARES Supply</title><style>{CSS}</style></head><body>"
        "<h1>ARES Supply</h1>"
        "<p>Fixed supply of 100,000,000 ARES · epoch rewards decay with the remaining reserve "
        "(half-life: 1,825 successful 24 h epochs) · 5% of bounties recycled to miners · no burn. "
        "All values are read from on-chain state and can be reproduced with "
        "<code>ares_lite.py supply</code>. This page makes no statement about price, returns or value.</p>"
        f"<div class='wrap'><table>{body}</table></div>"
        "<h2>Founder allocation disclosure</h2>"
        "<p>10% of the fixed supply was minted into a program-owned vesting vault in the same atomic genesis "
        "transaction that minted the 90% mining reserve to the program vault and revoked the mint authority. "
        "Only the founder beneficiary can release vested tokens; nobody (admin, multisig, founder) can withdraw "
        "from the mining vault except through claims against a capped, published epoch result.</p>"
        f"<div class='wrap'><table>{creator_body}</table></div></body></html>"
    )


def agent_brief(work: Workdir) -> str:
    """A self-contained brief a participant can hand to any AI coding agent."""

    manifest = work.manifest()
    challenge = json.loads(work.challenge_file.read_text())
    task = dict(zip(challenge["task_spec_fields"], challenge["task_spec"]))
    return f"""# ARES Lite {manifest.name} — solver brief (points only, no token)

Goal: make `lite/solvers/graph_route/src/lib.rs` use LESS deterministic fuel
than the baseline while staying exactly correct. Correctness is all-or-nothing.

## Problem (GRAPH-ROUTE)
Input (canonical CBOR): `[vertex_count, edges, source, target]`, each edge
`[from, to, cost, resource, class]`, edges sorted ascending.
Output (canonical CBOR): `[min_cost, [edge_index, ...]]` — the
lexicographically smallest `(cost, edge-index path)` over walks of
1..hop_limit edges from source to target that never use the forbidden class,
keep total resource <= resource_budget, and use the required class at least once.
Walks may revisit vertices. Constants (also in season.rs): {json.dumps(task)}

## Rules
- Rust `no_std` -> WebAssembly: export `solve(input_ptr, input_len, output_ptr, output_cap) -> i32`
  (bytes written, or -1), import memory `ares.memory`; integers only, no floats, no data
  section (avoid panics: they embed static data), no bulk-memory/sign-ext instructions.
- Memory is fresh and zeroed for every test case. Fuel = executed instructions.
- Profile: {challenge.get("profile")}; fuel per test case is capped.

## Loop
    python3 lite/cli/play.py build [--features ...]
    python3 lite/cli/play.py score       # must say VALID and show the gain
    python3 lite/cli/play.py submit

Existing variants: `--features memo` (state dominance), `bound` (admissible
bounds), `compact` (narrow fields), combinations. Invent better ones.
"""


def render(work: Workdir) -> str:
    manifest = work.manifest()
    challenge = json.loads(work.challenge_file.read_text())
    log_entries = [json.loads(line) for line in work.log_file.read_text().splitlines()]
    results = json.loads(work.results_file.read_text()) if work.results_file.exists() else None
    chain = json.loads(work.chain_file.read_text()) if work.chain_file.exists() else None
    board = practice_board(work.challenge(), work.log())
    r = manifest.rewards
    parts = [
        "<!doctype html><html lang='en'><head><meta charset='utf-8'>"
        "<meta name='viewport' content='width=device-width,initial-scale=1'>"
        f"<title>ARES Lite {esc(manifest.name)}</title><style>{CSS}</style></head><body>",
        f"<p><span class='tag'>DEVNET / TEST-ONLY · no financial value · no airdrop promise</span></p>",
        f"<h1>ARES Lite — {esc(manifest.name)}</h1>",
        "<p style='font-size:1.15em'><b>Build a better algorithm. Beat the baseline.</b></p>"
        "<p>Write a small program that finds the cheapest valid route in a graph. Every submission runs on "
        "the same hidden test graphs; the score is how much computation (fuel) it needs, lower is better, "
        "and it must be exactly correct. You, an AI agent, or both can write it — only the program is "
        "scored. Points only: no token, no value, no airdrop.</p>"
        "<h2>Start (5 commands)</h2><pre>git clone https://github.com/gasangalimov/ARES-PROTOCOL &amp;&amp; cd ARES-PROTOCOL\n"
        "pip install httpx==0.28.1 pycryptodome==3.23.0     # Python 3.12+, Rust + wasm32-unknown-unknown\n"
        "python3 lite/cli/play.py join --server SERVER_URL\n"
        "python3 lite/cli/play.py build &amp;&amp; python3 lite/cli/play.py score\n"
        "python3 lite/cli/play.py submit                       # then edit lib.rs and repeat</pre>"
        "<p>Using an AI agent? Give it <code>season-play/AGENT_BRIEF.md</code> (also served at <code>/agent.md</code>).</p>",
        "<h2>Rules</h2><ul>",
        f"<li>Challenge: CODE-SYNTH v0 <b>GRAPH-ROUTE</b>, difficulty profile {manifest.difficulty_index}. "
        "Task: lexicographically smallest (cost, edge path) walk of ≤ hop_limit edges from source to target "
        "that avoids the forbidden class, stays within the resource budget and uses the required class.</li>",
        f"<li>Correctness gate: frozen <code>verify_reveal</code> must return TEST_VALID on all 20 solution-bound "
        f"hidden tests for each of {r.seed_count} post-close seeds.</li>",
        f"<li>Score: total fuel over {r.benchmark_cases} shared hidden cases derived from the post-close beacon "
        "(same cases for everyone). Lower is better.</li>",
        f"<li>Rewards (devnet units): in commit order, a valid solver whose score beats the best so far by at least "
        f"{r.improvement_threshold_bps / 100:.2f}% earns season_cap × (previous best − score) / baseline. "
        f"Season cap {r.season_cap:,}. Copies and equal scores earn 0; splitting an improvement never pays more.</li>",
        "<li>Practice board below uses <i>public</i> seeds: useful feedback, never used for rewards.</li></ul>",
        "<h2>Challenge</h2><div class='wrap'><table>",
        f"<tr><th>challenge_id</th><td><code>{esc(challenge['challenge_id'])}</code></td></tr>",
        f"<tr><th>manifest hash</th><td><code>{esc(manifest.manifest_hash().hex())}</code></td></tr>",
        "".join(f"<tr><th>{esc(k)}</th><td>{esc(v)}</td></tr>" for k, v in zip(challenge["task_spec_fields"], challenge["task_spec"])),
        "</table></div>",
        f"<details><summary>public examples ({len(challenge['public_examples'])})</summary><pre>{esc(json.dumps(challenge['public_examples']))}</pre></details>",
        "<h2>Starter kit &amp; baseline</h2>",
        "<p>The baseline is the pinned generic source <code>lite/solvers/graph_route/src/lib.rs</code> "
        f"(sha256 <code>{esc(short(manifest.baseline_source_sha256, 16))}</code>) plus the season constants below. "
        "It enumerates every walk; <code>--features bnb</code> adds branch-and-bound, <code>lean</code> shrinks the workspace.</p>",
        f"<pre>{esc(work.season_rs_file.read_text())}</pre>",
        "<pre>python3 lite/cli/ares_lite.py build    --workdir SEASON --out my.wasm [--features bnb lean]\n"
        "python3 lite/cli/ares_lite.py practice --workdir SEASON --module my.wasm\n"
        "python3 lite/cli/ares_lite.py commit   --workdir SEASON --module my.wasm --address YOUR_SOLANA_PUBKEY \\\n"
        "                                       --secret-out ~/.config/ares-lite/my.secret\n"
        "python3 lite/cli/ares_lite.py reveal   --workdir SEASON --secret ~/.config/ares-lite/my.secret</pre>",
        "<h2>Submission flow</h2><ol><li>Commit: only a hash binding (solution, salt, your reward address) enters the "
        "public receipt log; the log sequence is your priority.</li><li>Reveal before the reveal window closes; the "
        "operator checks the reveal opens your commitment.</li><li>After close the beacon fixes the hidden seeds; "
        "anyone can recompute every score and the reward root.</li><li>Claim with your wallet on Solana devnet.</li></ol>",
        "<h2>Live practice board <span class='muted'>(public seeds, not reward-critical)</span></h2><div class='wrap'><table>",
        "<tr><th>#</th><th>commit</th><th>address</th><th>status</th><th>practice fuel</th></tr>",
        "".join(
            f"<tr><td>{i + 1}</td><td>{row['commit_seq']}</td><td><code>{esc(short(row['address']))}</code></td>"
            f"<td class='{'ok' if row['valid'] else 'bad'}'>{esc(row['reason'])}</td><td>{row['practice_fuel']:,}</td></tr>"
            for i, row in enumerate(board)
        ),
        "</table></div>",
    ]
    if results:
        awards = results["awards"]
        parts += [
            "<h2>Final results</h2>",
            f"<p>Baseline fuel {results['baseline']['fuel']:,}. Total awarded {results['total']:,} of cap "
            f"{results['season_cap']:,} (the remainder is never minted). Merkle root "
            f"<code>{esc(results['merkle_root'])}</code>, receipt-log head <code>{esc(results['log_head'])}</code>.</p>",
            progression_svg(results["baseline"]["fuel"], awards),
            "<div class='wrap'><table><tr><th>commit</th><th>address</th><th>valid</th><th>benchmark fuel</th><th>reason</th></tr>",
            "".join(
                f"<tr><td>{e['commit_seq']}</td><td><code>{esc(e['address_b58'])}</code></td>"
                f"<td class='{'ok' if e['valid'] else 'bad'}'>{e['valid']}</td><td>{e['benchmark_fuel']:,}</td><td>{esc(e['reason'])}</td></tr>"
                for e in results["evaluations"]
            ),
            "</table></div>",
            f"<h3>Allocation: <code>{esc(results.get('policy', 'telescoping_v0'))}</code> (separate from the score)</h3>"
            "<div class='wrap'><table><tr><th>address</th><th>points / devnet units</th></tr>",
            "".join(f"<tr><td><code>{esc(short(a, 16))}</code></td><td>{v:,}</td></tr>" for a, v in results["totals"]),
            "</table></div>",
            "<p class='muted'>Points are informational, not convertible to any token. "
            "A telescoping shadow allocation is published in results.json as research data.</p>"
            if results.get("shadow_telescoping_v0") else "",
            "<h3>Why each telescoping award</h3><div class='wrap'><table>"
            "<tr><th>commit</th><th>address</th><th>previous best</th><th>new best</th><th>amount</th></tr>",
            "".join(
                f"<tr><td>{a['commit_seq']}</td><td><code>{esc(short(a['reward_address']))}</code></td>"
                f"<td>{a['previous_best']:,}</td><td>{a['new_best']:,}</td><td>{a['amount']:,}</td></tr>"
                for a in awards
            ),
            "</table></div>",
        ]
    if chain:
        parts += [
            "<h2>On-chain (Solana devnet)</h2><div class='wrap'><table>",
            "".join(f"<tr><th>{esc(k)}</th><td><code>{esc(v)}</code></td></tr>" for k, v in chain.items()),
            "</table></div>",
        ]
    parts += [
        "<h2>Reproduce</h2><pre>python3 lite/cli/ares_lite.py verify-season --workdir SEASON</pre>"
        "<p>Recomputes the challenge from the manifest and beacon, re-verifies every revealed solver with the frozen "
        "verifier, re-derives the shared benchmark and the reward table, and checks the Merkle root.</p>",
        f"<h2>Receipt log</h2><p class='muted'>{len(log_entries)} entries, head <code>{esc(log_entries[-1]['head'] if log_entries else '')}</code></p>",
        "</body></html>",
    ]
    return "\n".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--workdir", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    (out / "index.html").write_text(render(Workdir(Path(args.workdir))))
    print(out / "index.html")


if __name__ == "__main__":
    main()
