# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/rewards.py — do not edit.
"""Deterministic Lite reward table: telescoping improvement in commit order.

Let B0 be the baseline fuel and walk valid submissions in receipt-log commit
order with a running best B (initially B0). A submission with fuel F earns

    floor(season_cap * (B - F) / B0)     if F * 10000 <= B * (10000 - threshold_bps)

and then B := F. Otherwise it earns 0. Properties (tested in lite/tests):

- Total payout <= season_cap * (B0 - B_final) / B0 < season_cap: the season
  can never mint its cap, and the unawarded remainder is never minted.
- Splitting one improvement into k steps never earns more than taking it at
  once (floors only lose); with the threshold it usually earns less, so
  drip-feeding is not profitable.
- Copies, Sybil identities and equivalent re-submissions earn 0: only a strict
  improvement over everything committed before them pays.
- Model, vendor, identity and wall-clock time never enter the formula.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass

from . import domains, merkle
from .evaluation import Evaluation
from ares_lite._core.canonical import encode, hash_bytes

U64_MAX = (1 << 64) - 1


@dataclass(frozen=True)
class Award:
    commit_seq: int
    reward_address: str  # hex
    solution_hash: str  # hex
    evaluation_digest: str  # hex
    previous_best: int
    new_best: int
    amount: int


@dataclass(frozen=True)
class RewardTable:
    season_id: int
    season_cap: int
    threshold_bps: int
    baseline_fuel: int
    awards: tuple[Award, ...]
    totals: tuple[tuple[str, int], ...]  # (address hex, amount), sorted by address
    total: int
    policy: str = "telescoping_v0"

    def digest(self) -> bytes:
        value = [
            0,
            self.season_id,
            self.season_cap,
            self.threshold_bps,
            self.baseline_fuel,
            [[a.commit_seq, bytes.fromhex(a.reward_address), bytes.fromhex(a.solution_hash),
              bytes.fromhex(a.evaluation_digest), a.previous_best, a.new_best, a.amount] for a in self.awards],
            [[bytes.fromhex(address), amount] for address, amount in self.totals],
            self.total,
            self.policy,
        ]
        return hash_bytes(domains.REWARD_TABLE, (encode(value),))

    def merkle(self) -> tuple[bytes, dict[str, list[bytes]]]:
        leaves = [merkle.leaf_hash(self.season_id, bytes.fromhex(a), amount) for a, amount in self.totals]
        root, proofs = merkle.build(leaves)
        return root, {address: proof for (address, _), proof in zip(self.totals, proofs)}

    def to_json(self) -> str:
        data = asdict(self)
        data["totals"] = [list(item) for item in self.totals]
        data["table_digest"] = self.digest().hex()
        if self.totals:
            root, proofs = self.merkle()
            data["merkle_root"] = root.hex()
            data["proofs"] = {a: [p.hex() for p in proof] for a, proof in proofs.items()}
        return json.dumps(data, indent=2, sort_keys=True) + "\n"


def compute(
    season_id: int,
    season_cap: int,
    threshold_bps: int,
    baseline_fuel: int,
    ordered: list[tuple[int, bytes, bytes, Evaluation]],
) -> RewardTable:
    """`ordered` = [(commit_seq, reward_address, solution_hash, evaluation)] in commit order."""

    if baseline_fuel <= 0:
        raise ValueError("baseline must be a valid solver with positive fuel")
    if not 0 < season_cap <= U64_MAX:
        raise ValueError("season_cap must be a positive u64")
    best = baseline_fuel
    awards: list[Award] = []
    totals: dict[bytes, int] = {}
    last_seq = -1
    for commit_seq, address, sol_hash, evaluation in ordered:
        if commit_seq <= last_seq:
            raise ValueError("submissions must be in strictly increasing commit order")
        last_seq = commit_seq
        if not evaluation.valid:
            continue
        fuel = evaluation.benchmark_fuel
        if fuel >= best or fuel * 10_000 > best * (10_000 - threshold_bps):
            continue
        amount = season_cap * (best - fuel) // baseline_fuel
        awards.append(
            Award(commit_seq, address.hex(), sol_hash.hex(), evaluation.digest().hex(), best, fuel, amount)
        )
        best = fuel
        if amount:
            totals[address] = totals.get(address, 0) + amount
    total = sum(totals.values())
    if total > season_cap:  # unreachable by construction; defence in depth
        raise AssertionError("reward table exceeds the season cap")
    return RewardTable(
        season_id,
        season_cap,
        threshold_bps,
        baseline_fuel,
        tuple(awards),
        tuple(sorted((a.hex(), v) for a, v in totals.items())),
        total,
    )


def from_allocation(
    season_id: int,
    season_cap: int,
    threshold_bps: int,
    baseline_fuel: int,
    allocation: dict[bytes, int],
    policy: str,
) -> RewardTable:
    """Reward table for any policy in ares_lite.policies (no per-step awards)."""

    totals = tuple(sorted((a.hex(), v) for a, v in allocation.items() if v > 0))
    total = sum(v for _, v in totals)
    if total > season_cap or any(v > U64_MAX for _, v in totals):
        raise ValueError("allocation exceeds the season cap")
    return RewardTable(season_id, season_cap, threshold_bps, baseline_fuel, (), totals, total, policy)
