# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/scaled.py — do not edit.
"""ARES Lite scaled GRAPH-ROUTE configuration (Lite profile "L1").

The frozen CODE-SYNTH v0 generator only offers difficulty profiles 0-2, whose
graphs are so small that constant-factor engineering dominates algorithmic
ideas (see docs/ares_lite/SEASON_ZERO.md). Canonical GRAPH-ROUTE is NOT
changed. Instead, Lite defines its own task parameters and resource profile
and drives the *frozen* functions with them:

- `construct_input` (frozen GRAPH-ROUTE input grammar, any task_spec),
- `reference_evaluate` (frozen exact reference semantics, explicit step limit),
- the frozen ARES-WASM-V0 static passes and metered interpreter `execute`
  with a Lite `ResourceProfile` (more memory and fuel).

Because the canonical `verify_reveal` regenerates the challenge with the
canonical generator, it cannot verify a scaled challenge. Correctness for L1
is therefore exact output on every shared post-close case (gate cases plus
benchmark cases) after the frozen static validation passes. This is a Lite
configuration, not CODE-SYNTH v0 conformance.
"""

from __future__ import annotations

from dataclasses import dataclass

from . import domains
from ares_lite._core.canonical import encode, hash_bytes, u32_be
from ares_lite._core.code_synth.evaluators import reference_evaluate
from ares_lite._core.code_synth.generator import construct_input
from ares_lite._core.code_synth.model import GenerationFailed, ReferenceEvaluationFailed
from ares_lite._core.code_synth.primitives import CoordinateSampler
from ares_lite._core.code_synth.verifier.model import ResourceProfile
from ares_lite._core.code_synth.verifier.runtime import RuntimeFailure, execute
from ares_lite._core.code_synth.verifier.wasm_binary import WasmStructuralError, decode_module, encode_module
from ares_lite._core.code_synth.verifier.wasm_validation import (
    WasmCoreValidationError,
    WasmFeatureError,
    WasmHostSurfaceError,
    WasmResourceError,
    validate_core,
    validate_feature_profile,
    validate_host_surface,
    validate_resources,
)

SCALED_CHALLENGE_ID = "ARES-LITE/SCALED-CHALLENGE-ID/v0"
SCALED_INSTANCE_ROOT = "ARES-LITE/SCALED-INSTANCE-ROOT/v0"
SCALED_CASE = "ARES-LITE/SCALED-CASE/v0"
HIDDEN_PROFILE_COUNT = 20


def lite_profile(fuel_per_test: int, reference_steps: int) -> ResourceProfile:
    """Frozen profile-2 limits except memory (16 pages), input size and fuel."""

    return ResourceProfile(
        profile_id=2,
        module_bytes=131_072,
        memory_pages=16,
        type_count=128,
        function_count=128,
        global_count=64,
        locals_per_function=1_024,
        control_nesting=128,
        static_value_stack=2_048,
        runtime_calls=128,
        decoded_instructions=200_000,
        input_bytes=32_768,
        output_bytes=4_096,
        fuel_per_test=fuel_per_test,
        fuel_per_reveal=fuel_per_test * 1_024,
        reference_steps=reference_steps,
    )


@dataclass(frozen=True)
class ScaledConfig:
    vertex_min: int
    vertex_max: int
    edge_max: int
    cost_max: int
    resource_max: int
    hop_limit: int
    class_count: int
    fuel_per_test: int = 30_000_000
    reference_steps: int = 50_000_000

    def validate(self) -> None:
        if not 4 <= self.vertex_min <= self.vertex_max <= 64:
            raise ValueError("vertex range must lie in [4, 64]")
        if not self.vertex_max <= self.edge_max <= 512:
            raise ValueError("edge_max must lie in [vertex_max, 512]")
        if not 2 <= self.hop_limit <= min(16, self.vertex_min - 1):
            raise ValueError("hop_limit must lie in [2, min(16, vertex_min - 1)]")
        if not 3 <= self.class_count <= 8 or not 1 <= self.cost_max <= 1_000 or not 1 <= self.resource_max <= 64:
            raise ValueError("class/cost/resource parameters out of range")

    def as_list(self) -> list[int]:
        return [self.vertex_min, self.vertex_max, self.edge_max, self.cost_max, self.resource_max,
                self.hop_limit, self.class_count, self.fuel_per_test, self.reference_steps]


@dataclass(frozen=True)
class _Context:
    ticket_id: bytes
    difficulty_index: int = 2


@dataclass(frozen=True)
class ScaledChallenge:
    config: ScaledConfig
    instance_root: bytes
    task_spec: list[int]
    public_examples: list[list[object]]
    challenge_id: bytes
    ticket_id: bytes = bytes(32)
    mode_id: int = 1
    is_scaled: bool = True

    @property
    def profile(self) -> ResourceProfile:
        return lite_profile(self.config.fuel_per_test, self.config.reference_steps)

    @property
    def context(self) -> _Context:
        return _Context(self.ticket_id)


def scaled_task_spec(config: ScaledConfig, instance_root: bytes) -> list[int]:
    config.validate()
    sampler = CoordinateSampler(instance_root)
    required = sampler.u("lite/required-class", 0, 0, config.class_count - 1)
    forbidden = (required + 1 + sampler.u("lite/forbidden-offset", 0, 0, config.class_count - 2)) % config.class_count
    budget = config.hop_limit * max(1, config.resource_max // 2)
    return [1, 0, config.vertex_min, config.vertex_max, config.vertex_min - 1, config.edge_max,
            config.cost_max, config.resource_max, budget, config.hop_limit, config.class_count,
            1 << required, 1 << forbidden]


def scaled_challenge(config: ScaledConfig, instance_root: bytes, ticket_id: bytes = bytes(32)) -> ScaledChallenge:
    task = scaled_task_spec(config, instance_root)
    examples = []
    for index in range(2):
        root = hash_bytes(SCALED_CASE, (instance_root, b"public", u32_be(index)))
        case_input = construct_input(1, task, root, 20 + index)
        examples.append([case_input, reference_evaluate(task, case_input, step_limit=config.reference_steps)])
    challenge_id = hash_bytes(
        SCALED_CHALLENGE_ID, (encode([0, "GRAPH-ROUTE-L1", config.as_list(), task, examples, ticket_id]),)
    )
    return ScaledChallenge(config, instance_root, task, examples, challenge_id, ticket_id)


@dataclass(frozen=True)
class Case:
    ordinal: int
    input_bytes: bytes
    expected_bytes: bytes


def scaled_cases(challenge: ScaledChallenge, seed: bytes, count: int) -> list[Case]:
    cases: list[Case] = []
    ordinal = 0
    while len(cases) < count and ordinal < 4 * count:
        root = hash_bytes(SCALED_CASE, (seed, challenge.challenge_id, u32_be(ordinal)))
        try:
            case_input = construct_input(1, challenge.task_spec, root, ordinal % HIDDEN_PROFILE_COUNT)
            expected = reference_evaluate(challenge.task_spec, case_input, step_limit=challenge.config.reference_steps)
        except (GenerationFailed, ReferenceEvaluationFailed):
            ordinal += 1
            continue
        data = encode(case_input)
        if len(data) <= challenge.profile.input_bytes:
            cases.append(Case(ordinal, data, encode(expected)))
        ordinal += 1
    if len(cases) != count:
        raise ValueError("could not generate the requested number of scaled cases")
    return cases


def static_check(module_bytes: bytes, profile: ResourceProfile) -> tuple[str, object, int]:
    """Frozen static passes (canonical module, features, host surface, core, resources)."""

    if len(module_bytes) > profile.module_bytes:
        return "MODULE_TOO_LARGE", None, -1
    try:
        module = decode_module(module_bytes)
    except WasmStructuralError:
        return "MALFORMED_WASM", None, -1
    if encode_module(module) != module_bytes:
        return "NON_CANONICAL_WASM", None, -1
    try:
        validate_feature_profile(module)
        solve_index = validate_host_surface(module, profile)
        validate_resources(module, validate_core(module), profile)
    except WasmFeatureError:
        return "DISALLOWED_FEATURE", None, -1
    except WasmHostSurfaceError:
        return "INVALID_IMPORT_EXPORT", None, -1
    except WasmCoreValidationError:
        return "MALFORMED_WASM", None, -1
    except WasmResourceError:
        return "RESOURCE_PROFILE_VIOLATION", None, -1
    return "OK", module, solve_index


@dataclass(frozen=True)
class RunResult:
    valid: bool
    reason: str
    fuel: int
    per_case_fuel: tuple[int, ...]


def run_cases(
    challenge: ScaledChallenge,
    module_bytes: bytes,
    cases: list[Case],
    exhaustion_penalty: int | None = None,
) -> RunResult:
    """Run shared cases. By default any runtime failure invalidates the solver.

    `exhaustion_penalty` (PROPOSAL, not used by any season unless a manifest
    opts in): a case that exhausts the per-test fuel cap is charged this many
    fuel units instead of invalidating the solver ("time limit exceeded").
    Wrong or malformed output, traps and every other failure still invalidate.
    """

    from ares_lite._core.code_synth.verifier import VerifierError

    profile = challenge.profile
    reason, module, solve_index = static_check(module_bytes, profile)
    if reason != "OK":
        return RunResult(False, reason, 0, ())
    remaining = profile.fuel_per_reveal
    per_case = []
    for case in cases:
        output_ptr = 16 * ((len(case.input_bytes) + 15) // 16)
        output_cap = min(profile.output_bytes, profile.memory_pages * 65_536 - output_ptr)
        try:
            run = execute(module, solve_index, profile, case.input_bytes, output_ptr, output_cap, remaining)
        except RuntimeFailure as failure:
            if exhaustion_penalty is not None and failure.error is VerifierError.FUEL_EXHAUSTED:
                per_case.append(exhaustion_penalty)
                remaining -= failure.fuel_charged
                continue
            return RunResult(False, f"{failure.error.name}@{case.ordinal}", sum(per_case) + failure.fuel_charged, tuple(per_case))
        per_case.append(run.fuel_charged)
        remaining = run.reveal_fuel_remaining
        returned = run.return_value - (1 << 32) if run.return_value >= 1 << 31 else run.return_value
        if not 0 <= returned <= output_cap:
            return RunResult(False, f"INVALID_RETURN@{case.ordinal}", sum(per_case), tuple(per_case))
        if run.memory[output_ptr : output_ptr + returned] != case.expected_bytes:
            return RunResult(False, f"WRONG_OUTPUT@{case.ordinal}", sum(per_case), tuple(per_case))
    return RunResult(True, "OK", sum(per_case), tuple(per_case))


def instance_root_for(manifest_hash: bytes, beacon: bytes) -> bytes:
    return hash_bytes(SCALED_INSTANCE_ROOT, (manifest_hash, beacon))


def solver_constants_rs(challenge: ScaledChallenge) -> str:
    task = challenge.task_spec
    return "\n".join([
        "// Generated for the ARES Lite scaled GRAPH-ROUTE configuration (L1).",
        f"// challenge_id = {challenge.challenge_id.hex()}",
        f"// task_spec = {task}",
        f"pub const HOP_LIMIT: u64 = {task[9]};",
        f"pub const RESOURCE_BUDGET: u64 = {task[8]};",
        f"pub const REQUIRED_MASK: u64 = {task[11]};",
        f"pub const FORBIDDEN_MASK: u64 = {task[12]};",
    ]) + "\n"


_ = domains  # Lite domain registry is shared; scaled-specific domains are above.
