# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/season.py — do not edit.
"""Season manifest and deterministic Season challenge derivation.

A Season is one fixed CODE-SYNTH v0 GRAPH-ROUTE challenge plus fixed scoring
and reward rules. The manifest is published (and its hash committed on
Solana) before the challenge beacon exists; the challenge is then a pure
function of the manifest and the beacon, so the operator has no free choice.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from pathlib import Path

from . import domains
from ares_lite._core.canonical import encode, hash_bytes, u32_be
from ares_lite._core.code_synth import ChallengeContext, GenerationFailed, generate_challenge
from ares_lite._core.code_synth.generator import GeneratedChallenge

GRAPH_ROUTE_MODE = 1
FAMILY_ID = "CODE-SYNTH"
MAX_TICKET_COUNTER = 4096
BEACON_KINDS = ("solana-slot-blockhash", "test-fixed")


class SeasonError(ValueError):
    """A manifest or beacon violates the Lite season rules."""


# Algorithmic/engineering variants of the starter crate that may serve as ratchet references.
REFERENCE_FEATURES = ("bound", "compact", "lb", "memo")


@dataclass(frozen=True)
class Beacon:
    """A public randomness value fixed after the event it must follow.

    `solana-slot-blockhash`: the blockhash of the first confirmed block at or
    after `slot` on `cluster`, read by anyone over RPC. `test-fixed` is only
    for local tests and is rejected for any manifest whose network is not
    `localnet`.
    """

    kind: str
    slot: int
    value: str  # 32-byte hex

    def bytes(self) -> bytes:
        raw = bytes.fromhex(self.value)
        if len(raw) != 32:
            raise SeasonError("beacon value must be 32 bytes")
        return raw


@dataclass(frozen=True)
class RewardRules:
    season_cap: int  # base units the program may ever mint for this season
    improvement_threshold_bps: int  # minimum relative improvement to earn
    seed_count: int  # independent post-close verification seeds (K) for the gate
    benchmark_cases: int  # shared post-close benchmark cases scored by fuel

    def validate(self) -> None:
        if not 0 < self.season_cap < 1 << 64:
            raise SeasonError("season_cap must be a positive u64")
        if not 0 <= self.improvement_threshold_bps < 10_000:
            raise SeasonError("improvement_threshold_bps must be in [0, 10000)")
        if not 1 <= self.seed_count <= 64:
            raise SeasonError("seed_count must be in [1, 64]")
        if not 1 <= self.benchmark_cases <= 1024:
            raise SeasonError("benchmark_cases must be in [1, 1024]")


@dataclass(frozen=True)
class SeasonManifest:
    schema: str
    season_id: int
    name: str
    network: str  # "solana-devnet" | "localnet"
    chain_id: str  # ASCII, becomes the CODE-SYNTH chain_id bytes
    protocol_version: int
    difficulty_index: int
    adjustment_epoch: int
    challenge_beacon_slot: int  # beacon slot strictly after manifest commitment
    reward_beacon_delay_slots: int  # verification beacon slot = close slot + delay
    rewards: RewardRules
    # SHA-256 of the generic starter solver source (solvers/graph_route/src/lib.rs).
    # The baseline is that source plus constants derived from the challenge, so
    # the operator cannot pick a weak baseline after seeing the challenge.
    baseline_source_sha256: str
    financial_value: bool = False
    notes: tuple[str, ...] = field(default_factory=tuple)
    # "code-synth-v0": frozen CODE-SYNTH v0 GRAPH-ROUTE at `difficulty_index`.
    # "lite-L1": ARES Lite scaled GRAPH-ROUTE (ares_lite.scaled), `scaled` holds
    # ScaledConfig.as_list(). Not CODE-SYNTH v0 conformance.
    challenge_profile: str = "code-synth-v0"
    scaled: tuple[int, ...] = ()
    # Allocation policy applied to the score table (ares_lite.policies).
    reward_policy: str = "telescoping_v0"
    # Ed25519 public key (hex) that signs receipts for this season; "" = none.
    receipt_signer: str = ""
    # Publicly known solver variants ("compact", "memo+bound", ...) of the
    # pinned starter source. They are built for THIS season's constants at
    # open, exactly like the baseline, and the effective baseline is the best
    # of all of them on the same hidden cases ("ratchet"): building a known
    # public variant and committing it first can never win the epoch.
    reference_features: tuple[str, ...] = ()

    def validate(self) -> None:
        if self.schema != domains.SEASON_MANIFEST:
            raise SeasonError("unknown manifest schema")
        if not 0 <= self.season_id < 1 << 64:
            raise SeasonError("season_id must be u64")
        if self.network not in ("solana-devnet", "localnet"):
            raise SeasonError("ARES Lite only targets solana-devnet or localnet")
        if self.financial_value:
            raise SeasonError("Lite seasons in this profile carry no financial value")
        if self.difficulty_index not in (0, 1, 2):
            raise SeasonError("difficulty_index must select a frozen profile")
        if self.challenge_profile not in ("code-synth-v0", "lite-L1"):
            raise SeasonError("unknown challenge profile")
        if (self.challenge_profile == "lite-L1") != bool(self.scaled):
            raise SeasonError("lite-L1 requires scaled parameters (and only lite-L1 may have them)")
        if self.scaled:
            from .scaled import ScaledConfig

            ScaledConfig(*self.scaled).validate()
        from .policies import POLICIES

        if self.reward_policy not in POLICIES:
            raise SeasonError("unknown reward policy")
        if self.receipt_signer and len(bytes.fromhex(self.receipt_signer)) != 32:
            raise SeasonError("receipt_signer must be a 32-byte Ed25519 public key (hex)")
        for ref in self.reference_features:
            parts = ref.split("+")
            if not ref or any(part not in REFERENCE_FEATURES for part in parts) or parts != sorted(set(parts)):
                raise SeasonError(f"reference feature set {ref!r}: sorted '+'-joined subset of {REFERENCE_FEATURES}")
        if len(set(self.reference_features)) != len(self.reference_features):
            raise SeasonError("duplicate reference feature set")
        self.rewards.validate()
        ChallengeContext(
            chain_id=self.chain_id.encode("ascii"),
            protocol_version=self.protocol_version,
            family_version=0,
            round_id=self.season_id,
            ticket_id=bytes(32),
            adjustment_epoch=self.adjustment_epoch,
            difficulty_index=self.difficulty_index,
        )

    def canonical_value(self) -> list[object]:
        return [
            0,
            self.schema,
            self.season_id,
            self.name,
            self.network,
            self.chain_id,
            self.protocol_version,
            self.difficulty_index,
            self.adjustment_epoch,
            self.challenge_beacon_slot,
            self.reward_beacon_delay_slots,
            [
                self.rewards.season_cap,
                self.rewards.improvement_threshold_bps,
                self.rewards.seed_count,
                self.rewards.benchmark_cases,
            ],
            self.baseline_source_sha256,
            int(self.financial_value),
            list(self.notes),
            self.challenge_profile,
            list(self.scaled),
            self.reward_policy,
            self.receipt_signer,
        ] + ([list(self.reference_features)] if self.reference_features else [])

    def manifest_hash(self) -> bytes:
        self.validate()
        return hash_bytes(domains.SEASON_MANIFEST, (encode(self.canonical_value()),))

    def lane_round_key(self) -> tuple[object, ...]:
        return (0, self.chain_id.encode("ascii"), self.protocol_version, self.season_id, FAMILY_ID, 0)

    def to_json(self) -> str:
        data = asdict(self)
        data["notes"] = list(self.notes)
        data["scaled"] = list(self.scaled)
        data["reference_features"] = list(self.reference_features)
        return json.dumps(data, indent=2, sort_keys=True) + "\n"

    @classmethod
    def from_json(cls, text: str) -> "SeasonManifest":
        data = json.loads(text)
        data["rewards"] = RewardRules(**data["rewards"])
        data["notes"] = tuple(data.get("notes", ()))
        data["scaled"] = tuple(data.get("scaled", ()))
        data["reference_features"] = tuple(data.get("reference_features", ()))
        manifest = cls(**data)
        manifest.validate()
        return manifest

    @classmethod
    def load(cls, path: Path) -> "SeasonManifest":
        return cls.from_json(Path(path).read_text())


def check_beacon(manifest: SeasonManifest, beacon: Beacon) -> None:
    if beacon.kind not in BEACON_KINDS:
        raise SeasonError("unknown beacon kind")
    if beacon.kind == "test-fixed" and manifest.network != "localnet":
        raise SeasonError("test-fixed beacons are only valid on localnet")
    beacon.bytes()


def season_challenge(manifest: SeasonManifest, challenge_beacon: Beacon) -> GeneratedChallenge:
    """Derive the unique Season challenge.

    The ticket counter starts at 0 and the first counter whose frozen
    generator output is a GRAPH-ROUTE challenge is selected. The rule is fixed
    in advance and leaves no operator choice; generation failures are skipped
    the same way for everybody.
    """

    check_beacon(manifest, challenge_beacon)
    if challenge_beacon.slot != manifest.challenge_beacon_slot:
        raise SeasonError("challenge beacon slot differs from the manifest")
    manifest_hash = manifest.manifest_hash()
    challenge_seed = hash_bytes(
        domains.CHALLENGE_SEED, (manifest_hash, challenge_beacon.bytes())
    )
    if manifest.challenge_profile == "lite-L1":
        from .scaled import ScaledConfig, scaled_challenge

        ticket_id = hash_bytes(domains.SEASON_TICKET, (manifest_hash, u32_be(0)))
        return scaled_challenge(ScaledConfig(*manifest.scaled), challenge_seed, ticket_id)
    for counter in range(MAX_TICKET_COUNTER):
        ticket_id = hash_bytes(domains.SEASON_TICKET, (manifest_hash, u32_be(counter)))
        context = ChallengeContext(
            chain_id=manifest.chain_id.encode("ascii"),
            protocol_version=manifest.protocol_version,
            family_version=0,
            round_id=manifest.season_id,
            ticket_id=ticket_id,
            adjustment_epoch=manifest.adjustment_epoch,
            difficulty_index=manifest.difficulty_index,
        )
        try:
            challenge = generate_challenge(context, challenge_seed)
        except GenerationFailed:
            continue
        if challenge.mode_id == GRAPH_ROUTE_MODE:
            return challenge
    raise SeasonError("no GRAPH-ROUTE challenge within the counter bound")


def family_config_ref(manifest: SeasonManifest) -> bytes:
    return hash_bytes(domains.FAMILY_CONFIG_REF, (manifest.manifest_hash(),))


def practice_seed(challenge: GeneratedChallenge, index: int) -> bytes:
    """Public seeds for local self-testing and the live validation board.

    Practice results are never reward-critical: they are known to everybody
    and can be overfit, which is exactly why rewards use post-close seeds.
    """

    return hash_bytes(domains.PRACTICE_SEED, (challenge.challenge_id, u32_be(index)))


def verification_seeds(
    manifest: SeasonManifest,
    challenge: GeneratedChallenge,
    log_head: bytes,
    reward_beacon: Beacon,
) -> list[bytes]:
    """K reward-critical verification seeds fixed after the reveal log closes."""

    check_beacon(manifest, reward_beacon)
    return [
        hash_bytes(
            domains.VERIFICATION_SEED,
            (
                manifest.manifest_hash(),
                challenge.challenge_id,
                log_head,
                reward_beacon.bytes(),
                u32_be(index),
            ),
        )
        for index in range(manifest.rewards.seed_count)
    ]


def benchmark_seed(
    manifest: SeasonManifest,
    challenge: GeneratedChallenge,
    log_head: bytes,
    reward_beacon: Beacon,
) -> bytes:
    """The single shared benchmark seed, fixed after the reveal log closes."""

    check_beacon(manifest, reward_beacon)
    return hash_bytes(
        domains.BENCHMARK_SEED,
        (manifest.manifest_hash(), challenge.challenge_id, log_head, reward_beacon.bytes()),
    )


def solver_constants(challenge: GeneratedChallenge) -> dict[str, int]:
    task = challenge.task_spec
    if challenge.mode_id != GRAPH_ROUTE_MODE or len(task) != 13:
        raise SeasonError("solver constants exist only for GRAPH-ROUTE")
    return {
        "HOP_LIMIT": task[9],
        "RESOURCE_BUDGET": task[8],
        "REQUIRED_MASK": task[11],
        "FORBIDDEN_MASK": task[12],
    }


def render_solver_constants(challenge) -> str:
    if getattr(challenge, "is_scaled", False):
        from .scaled import solver_constants_rs

        return solver_constants_rs(challenge)
    constants = solver_constants(challenge)
    lines = [
        "// Generated by `lite/cli/ares_lite.py starter-kit`. Do not edit by hand.",
        f"// challenge_id = {challenge.challenge_id.hex()}",
        f"// task_spec = {challenge.task_spec}",
        f"pub const HOP_LIMIT: u64 = {constants['HOP_LIMIT']};",
        f"pub const RESOURCE_BUDGET: u64 = {constants['RESOURCE_BUDGET']};",
        f"pub const REQUIRED_MASK: u64 = {constants['REQUIRED_MASK']};",
        f"pub const FORBIDDEN_MASK: u64 = {constants['FORBIDDEN_MASK']};",
    ]
    return "\n".join(lines) + "\n"
