# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/submission.py — do not edit.
"""Season submissions: frozen P0-T03 commitments plus a hash-chained receipt log.

Commitments use the frozen `commitment_artifacts` construction unchanged. The
Lite ticket binding maps:

- `lane_round_key`  -> (0, chain_id, protocol_version, season_id, CODE-SYNTH, 0)
- `ticket_id`       -> the Season ticket id (one per Season, not per miner)
- `reward_address`  -> the participant's 32-byte Solana public key
- `mining_key_ref`  -> H(ARES-LITE/MINING-KEY-REF/v0, reward_address)
- `family_config_ref` -> H(ARES-LITE/FAMILY-CONFIG-REF/v0, manifest_hash)

so a revealed solution can only be credited to the address bound into its
commitment. Ordering ("who was first") is the receipt-log sequence assigned by
the operator; the log is a public hash chain whose head is published and
finally committed on Solana together with the reward root.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from . import domains
from .season import SeasonManifest, family_config_ref
from ares_lite._core.canonical import encode, hash_bytes, u64_be
from ares_lite._core.code_synth.generator import GeneratedChallenge
from ares_lite._core.commit_reveal import RevealRecord, TicketBinding
from ares_lite._core.commit_reveal.transcripts import (
    RevealSubmission,
    commitment_artifacts,
    encode_reveal_submission,
    parse_reveal_submission,
    reveal_hash,
    solution_hash,
)

OPEN, COMMIT, REVEAL, CLOSE_COMMITS, CLOSE_REVEALS = range(5)
KIND_NAMES = ("OPEN", "COMMIT", "REVEAL", "CLOSE_COMMITS", "CLOSE_REVEALS")
GENESIS_HEAD = bytes(32)


class SubmissionRejected(ValueError):
    """The operator must refuse this request; nothing is appended."""


def canonical_solution(challenge: GeneratedChallenge, module_bytes: bytes) -> bytes:
    """Frozen CODE-SYNTH v0 solution envelope (Section 7.2)."""

    return encode([0, "CODE-SYNTH", 0, challenge.challenge_id, 0, module_bytes])


def binding_for(
    manifest: SeasonManifest, challenge: GeneratedChallenge, reward_address: bytes
) -> TicketBinding:
    if not isinstance(reward_address, bytes) or len(reward_address) != 32:
        raise SubmissionRejected("reward address must be a 32-byte Solana public key")
    return TicketBinding(
        lane_round_key=manifest.lane_round_key(),
        ticket_id=challenge.context.ticket_id,
        mining_key_ref=hash_bytes(domains.MINING_KEY_REF, (reward_address,)),
        reward_address=reward_address,
        family_config_ref=family_config_ref(manifest),
        difficulty_index=manifest.difficulty_index,
    )


def commitment_for(
    manifest: SeasonManifest,
    challenge: GeneratedChallenge,
    reward_address: bytes,
    solution_bytes: bytes,
    salt: bytes,
) -> bytes:
    return commitment_artifacts(
        binding_for(manifest, challenge, reward_address),
        challenge.challenge_id,
        solution_bytes,
        salt,
    ).commitment


def reveal_bytes_for(
    manifest: SeasonManifest, challenge: GeneratedChallenge, solution_bytes: bytes, salt: bytes
) -> bytes:
    return encode_reveal_submission(
        manifest.lane_round_key(),
        challenge.context.ticket_id,
        challenge.challenge_id,
        solution_bytes,
        salt,
    )


@dataclass(frozen=True)
class Entry:
    seq: int
    kind: int
    fields: tuple  # canonical CBOR values
    head: bytes  # hash chain head after this entry

    def to_json(self) -> dict:
        return {
            "seq": self.seq,
            "kind": KIND_NAMES[self.kind],
            "fields": [f.hex() if isinstance(f, bytes) else f for f in self.fields],
            "head": self.head.hex(),
        }


def _entry_head(prev: bytes, seq: int, kind: int, fields: tuple) -> bytes:
    return hash_bytes(domains.RECEIPT, (prev, u64_be(seq), encode([kind, list(fields)])))


@dataclass
class ReceiptLog:
    """Append-only operator log. Phase transitions are entries, not clocks."""

    manifest: SeasonManifest
    challenge: GeneratedChallenge
    entries: list[Entry] = field(default_factory=list)
    commits: dict[int, tuple[bytes, bytes]] = field(default_factory=dict)  # seq -> (address, commitment)
    reveals: dict[int, bytes] = field(default_factory=dict)  # commit seq -> raw reveal bytes
    _commitments: set[bytes] = field(default_factory=set)

    @property
    def head(self) -> bytes:
        return self.entries[-1].head if self.entries else GENESIS_HEAD

    @property
    def phase(self) -> int:
        kinds = {entry.kind for entry in self.entries}
        if CLOSE_REVEALS in kinds:
            return CLOSE_REVEALS
        if CLOSE_COMMITS in kinds:
            return CLOSE_COMMITS
        if OPEN in kinds:
            return OPEN
        return -1

    def _append(self, kind: int, fields: tuple) -> Entry:
        seq = len(self.entries)
        entry = Entry(seq, kind, fields, _entry_head(self.head, seq, kind, fields))
        self.entries.append(entry)
        return entry

    def open(self, challenge_beacon_value: bytes, baseline_module_hash: bytes) -> Entry:
        if self.entries:
            raise SubmissionRejected("season already opened")
        return self._append(
            OPEN,
            (
                self.manifest.manifest_hash(),
                self.challenge.challenge_id,
                challenge_beacon_value,
                baseline_module_hash,
            ),
        )

    def commit(self, reward_address: bytes, commitment: bytes) -> Entry:
        if self.phase != OPEN:
            raise SubmissionRejected("commits are not open")
        if not isinstance(reward_address, bytes) or len(reward_address) != 32:
            raise SubmissionRejected("reward address must be 32 bytes")
        if not isinstance(commitment, bytes) or len(commitment) != 32:
            raise SubmissionRejected("commitment must be 32 bytes")
        if commitment in self._commitments:
            raise SubmissionRejected("duplicate commitment")
        entry = self._append(COMMIT, (reward_address, commitment))
        self.commits[entry.seq] = (reward_address, commitment)
        self._commitments.add(commitment)
        return entry

    def reveal(self, commit_seq: int, raw_reveal: bytes) -> Entry:
        if self.phase not in (OPEN, CLOSE_COMMITS):
            raise SubmissionRejected("reveals are closed")
        if commit_seq not in self.commits:
            raise SubmissionRejected("unknown commit")
        if commit_seq in self.reveals:
            raise SubmissionRejected("commit already revealed")
        try:
            reveal = parse_reveal_submission(raw_reveal)
        except ValueError as exc:
            raise SubmissionRejected(f"malformed reveal: {exc}") from exc
        if encode(reveal.canonical_value) != raw_reveal:
            raise SubmissionRejected("reveal is not canonical")
        if (
            reveal.ticket_id != self.challenge.context.ticket_id
            or reveal.challenge_id != self.challenge.challenge_id
            or reveal.lane_round_key != self.manifest.lane_round_key()
        ):
            raise SubmissionRejected("reveal is bound to another season or challenge")
        address, commitment = self.commits[commit_seq]
        recomputed = commitment_for(
            self.manifest, self.challenge, address, reveal.canonical_solution_bytes, reveal.salt
        )
        if recomputed != commitment:
            raise SubmissionRejected("reveal does not open the commitment")
        entry = self._append(REVEAL, (commit_seq, reveal_hash(raw_reveal)))
        self.reveals[commit_seq] = raw_reveal
        return entry

    def close_commits(self) -> Entry:
        if self.phase != OPEN:
            raise SubmissionRejected("commits already closed")
        return self._append(CLOSE_COMMITS, ())

    def close_reveals(self, close_slot: int) -> Entry:
        """Close the log at a host slot. The reward beacon is the blockhash at
        close_slot + reward_beacon_delay_slots, so it is unknown when the
        closed head is published."""

        if self.phase != CLOSE_COMMITS:
            raise SubmissionRejected("close commits first")
        if type(close_slot) is not int or not 0 <= close_slot < 1 << 63:
            raise SubmissionRejected("close slot must be a u63")
        return self._append(CLOSE_REVEALS, (close_slot,))

    def revealed(self) -> list[tuple[int, bytes, RevealSubmission, RevealRecord]]:
        """Revealed submissions in commit order with frozen verifier records."""

        out = []
        for commit_seq in sorted(self.reveals):
            raw = self.reveals[commit_seq]
            reveal = parse_reveal_submission(raw)
            record = RevealRecord(
                reveal.ticket_id,
                reveal.challenge_id,
                reveal_hash(raw),
                solution_hash(reveal.canonical_solution_bytes),
                commit_seq,
            )
            out.append((commit_seq, self.commits[commit_seq][0], reveal, record))
        return out

    # Persistence: JSON lines, each carrying its own chain head so any reader
    # can re-verify the chain with `verify_chain`.
    def save(self, path: Path) -> None:
        lines = []
        for entry in self.entries:
            data = entry.to_json()
            if entry.kind == REVEAL:
                data["reveal"] = self.reveals[entry.fields[0]].hex()
            lines.append(json.dumps(data, sort_keys=True))
        Path(path).write_text("\n".join(lines) + ("\n" if lines else ""))

    @classmethod
    def load(cls, path: Path, manifest: SeasonManifest, challenge: GeneratedChallenge) -> "ReceiptLog":
        log = cls(manifest, challenge)
        for line in Path(path).read_text().splitlines():
            data = json.loads(line)
            kind = KIND_NAMES.index(data["kind"])
            fields = [bytes.fromhex(f) if isinstance(f, str) else f for f in data["fields"]]
            if kind == OPEN:
                entry = log.open(fields[2], fields[3])
            elif kind == COMMIT:
                entry = log.commit(fields[0], fields[1])
            elif kind == REVEAL:
                entry = log.reveal(fields[0], bytes.fromhex(data["reveal"]))
            elif kind == CLOSE_COMMITS:
                entry = log.close_commits()
            else:
                entry = log.close_reveals(fields[0])
            if entry.head.hex() != data["head"] or entry.seq != data["seq"]:
                raise SubmissionRejected(f"receipt chain mismatch at seq {data['seq']}")
        return log


def verify_chain(entries: list[dict]) -> bytes:
    """Recompute a published chain from its JSON entries; returns the head."""

    head = GENESIS_HEAD
    for index, data in enumerate(entries):
        if data["seq"] != index:
            raise ValueError("sequence gap")
        kind = KIND_NAMES.index(data["kind"])
        fields = tuple(bytes.fromhex(f) if isinstance(f, str) else f for f in data["fields"])
        head = _entry_head(head, index, kind, fields)
        if head.hex() != data["head"]:
            raise ValueError(f"head mismatch at {index}")
    return head
