# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/supply.py — do not edit.
"""Supply dashboard and frozen-economics release checks (from on-chain state only)."""

from __future__ import annotations

import time

from . import solana_client as sc
from . import tokenomics as tk


class ReleaseCheckFailed(RuntimeError):
    """A fixed-supply invariant does not hold; release must stop."""


def snapshot(rpc: "sc.Rpc", program_id: bytes, mint: bytes, now_ts: int | None = None) -> dict:
    """Supply and reserve facts, read from on-chain state only."""

    lite = sc.LiteProgram(program_id, mint)
    mint_info, config_info = rpc.account(mint), rpc.account(lite.config)
    vault_info, fvault_info = rpc.account(lite.vault), rpc.account(lite.founder_vault)
    if not (mint_info and config_info and vault_info and fvault_info):
        raise ReleaseCheckFailed("mint, config, mining vault or founder vault account missing")
    mint_state = sc.parse_mint(mint_info["raw"])
    config = sc.parse_config(config_info["raw"])
    vault_balance = int.from_bytes(vault_info["raw"][64:72], "little")
    founder_vault_balance = int.from_bytes(fvault_info["raw"][64:72], "little")
    now_ts = now_ts if now_ts is not None else int(time.time())
    e = config["epoch_seconds"]
    avail = vault_balance - config["pending_reserved"] - config["outstanding_unclaimed"]
    vested = tk.vested(config["genesis_ts"], now_ts, e)
    return {
        "mint": sc.b58encode(mint),
        "program_id": sc.b58encode(program_id),
        "program_version": config["version"],
        "decimals": mint_state["decimals"],
        "mint_authority": mint_state["mint_authority"],
        "freeze_authority": mint_state["freeze_authority"],
        "max_supply": tk.MAX_SUPPLY,
        "current_supply": mint_state["supply"],
        "founder_allocation": tk.FOUNDER_ALLOCATION,
        "founder_beneficiary": config["founder_beneficiary"],
        "founder_vault": sc.b58encode(lite.founder_vault),
        "founder_vault_balance": founder_vault_balance,
        "founder_vested_now": vested,
        "founder_released": config["founder_claimed"],
        "founder_unvested": tk.FOUNDER_ALLOCATION - vested,
        "mining_allocation": tk.MINING_ALLOCATION,
        "mining_vault": sc.b58encode(lite.vault),
        "mining_vault_balance": vault_balance,
        "pending_reserved": config["pending_reserved"],
        "outstanding_unclaimed": config["outstanding_unclaimed"],
        "available_reserve": avail,
        "next_epoch_cap": tk.epoch_cap(max(avail, 0)),
        "mining_awarded_total": config["mining_awarded_total"],
        "mining_claimed_total": config["mining_claimed_total"],
        "recycled_total": config["recycled_total"],
        "bounty_escrowed": config["bounty_escrowed"],
        "last_closed_epoch": config["last_closed_epoch"],
        "current_epoch": tk.epoch_index(config["genesis_ts"], now_ts, e),
        "epoch_seconds": e,
        "genesis_ts": config["genesis_ts"],
        "genesis_utc": tk.iso(config["genesis_ts"]),
        "vesting_cliff_utc": tk.iso(config["genesis_ts"] + tk.YEAR_EPOCHS * e),
        "vesting_end_utc": tk.iso(config["genesis_ts"] + 5 * tk.YEAR_EPOCHS * e),
        "admin": config["admin"],
        "founder_token_account": sc.b58encode(sc.associated_token_address(sc.b58decode(config["founder_beneficiary"]), mint)),
        "founder": config["founder_beneficiary"],
    }


def verify_fixed_supply(snap: dict, at_genesis: bool = False, production: bool = False) -> list[str]:
    """Frozen-economics invariant checks; returns the passed checks or raises."""

    checks = {
        "inv1_mint_authority_is_None": snap["mint_authority"] is None,
        "inv1_freeze_authority_is_None": snap["freeze_authority"] is None,
        "inv1_supply_is_exactly_100M": snap["current_supply"] == tk.MAX_SUPPLY,
        "decimals_is_6": snap["decimals"] == tk.DECIMALS,
        "program_version_4": snap["program_version"] == 4,
        "inv3_vault_covers_P_plus_O": snap["mining_vault_balance"] >= snap["pending_reserved"] + snap["outstanding_unclaimed"],
        "inv5_exact_vault_ledger": snap["mining_vault_balance"] + snap["mining_claimed_total"] >= tk.MINING_ALLOCATION + snap["recycled_total"],
        "inv9_founder_released_le_vested": snap["founder_released"] <= snap["founder_vested_now"] <= tk.FOUNDER_ALLOCATION,
        "founder_vault_is_allocation_minus_released": snap["founder_vault_balance"] == tk.FOUNDER_ALLOCATION - snap["founder_released"],
        # with D = direct donations = V + claimed - MINING - recycled (>= 0 by inv5):
        # A = MINING + recycled + D - awarded - P  <=>  O == awarded - claimed  (inv12)
        "inv12_only_awards_deplete": snap["outstanding_unclaimed"] == snap["mining_awarded_total"] - snap["mining_claimed_total"],
        "founder_allocation_is_10pct": tk.FOUNDER_ALLOCATION * 10 == tk.MAX_SUPPLY,
    }
    if production:
        checks["production_epoch_is_24h"] = snap["epoch_seconds"] == tk.DAY
    if at_genesis:
        checks["G1_founder_vault_exactly_10M"] = snap["founder_vault_balance"] == tk.FOUNDER_ALLOCATION
        checks["G1_mining_vault_exactly_90M"] = snap["mining_vault_balance"] == tk.MINING_ALLOCATION
        checks["G1_P_O_zero"] = snap["pending_reserved"] == snap["outstanding_unclaimed"] == 0
        checks["G1_no_epoch_closed"] = snap["last_closed_epoch"] is None
    failed = [name for name, ok in checks.items() if not ok]
    if failed:
        raise ReleaseCheckFailed(f"frozen-economics invariants failed: {failed}")
    return list(checks)


def mint_death_test(rpc: "sc.Rpc", mint: bytes, destination: bytes, signers: dict[str, "sc.Keypair"],
                    pda_authorities: dict[str, bytes], unsigned: dict[str, bytes] | None = None,
                    fee_payer: "sc.Keypair | None" = None) -> dict:
    """Simulate MintTo by every candidate authority; every one must FAIL.

    Simulation commits nothing, so this is safe on mainnet. A funded
    `fee_payer` (default: the first signer) pays, and the candidate signs as
    the mint authority, so an unfunded candidate cannot "fail" for the wrong
    reason. Only a rejection by the token program itself (InstructionError)
    counts; any other error (missing payer, bad blockhash) aborts the test.
    PDAs are tried as (non-signing) authorities; a PDA can only sign inside
    its program, which has no mint instruction.
    """

    payer = fee_payer or next(iter(signers.values()))

    def verdict(name: str, result: dict) -> str:
        err = result.get("err")
        if not err:
            return "SUCCEEDED (BAD)"
        if not (isinstance(err, dict) and "InstructionError" in err):
            raise ReleaseCheckFailed(f"mint death test for {name} failed for an unrelated reason: {err}")
        return "FAILED (good)"

    outcome = {}
    for name, key in signers.items():
        extra = [] if key.public == payer.public else [key]
        outcome[name] = verdict(name, rpc.simulate(payer, [sc.mint_to_ix(mint, destination, key.public, 1)], extra))
    for name, address in pda_authorities.items():
        ix = sc.Ix(sc.TOKEN_PROGRAM, (sc.Meta(mint, False, True), sc.Meta(destination, False, True),
                                      sc.Meta(address, False, False)), bytes([7]) + (1).to_bytes(8, "little"))
        outcome[name] = verdict(name, rpc.simulate(payer, [ix]))
    for name, address in (unsigned or {}).items():
        outcome[name] = verdict(name, rpc.simulate_unsigned(payer.public, [sc.mint_to_ix(mint, destination, address, 1)]))
    if any("BAD" in v for v in outcome.values()):
        raise ReleaseCheckFailed(f"additional mint possible: {outcome}")
    return outcome


def simulate_bounty(rpc: "sc.Rpc", program_id: bytes, mint: bytes, funder: bytes, amount: int, bounty_id: int) -> dict:
    """Simulate a bounty funded by `funder` (no key needed, nothing committed):
    supply must be unchanged (no burn) and the mining vault must grow by exactly 5%."""

    import base64

    lite = sc.LiteProgram(program_id, mint)
    supply_before = sc.parse_mint(rpc.account(mint)["raw"])["supply"]
    vault_before = sc.token_balance(rpc, lite.vault)
    ata = sc.associated_token_address(funder, mint)
    result = rpc.simulate_unsigned(funder, [lite.fund_bounty(funder, ata, bounty_id, amount)], watch=[mint, lite.vault])
    if result.get("err"):
        raise ReleaseCheckFailed(f"bounty simulation failed: {result['err']} {result.get('logs', [])[-3:]}")
    supply_after = sc.parse_mint(base64.b64decode(result["accounts"][0]["data"][0]))["supply"]
    vault_after = int.from_bytes(base64.b64decode(result["accounts"][1]["data"][0])[64:72], "little")
    fee, escrow = tk.bounty_split(amount)
    if supply_after != supply_before or vault_after - vault_before != fee:
        raise ReleaseCheckFailed(f"simulated bounty: supply {supply_before}->{supply_after}, vault +{vault_after - vault_before} != {fee}")
    return {"amount": amount, "recycled_fee": fee, "escrow": escrow, "supply_unchanged": True}
