# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/tokenomics.py — do not edit.
"""ARES Lite FROZEN economics (ARES_LITE_FINAL_ECONOMICS_SPEC_v1 + R1 + R2).

Integer mirror of lite/solana/program v4 (cross-checked in tests). All
amounts are base units (6 decimals). No floats are used for any amount.

- 100,000,000 ARES fixed; 10,000,000 founder (vesting PDA), 90,000,000 mining vault.
- 24 h epochs; cap(e) = floor(A * 379,735 / 1e9), A = V - P - O (available reserve).
- R1: the whole cap is HELD (P) from close until FINAL/EXPIRED; only FINAL
  depletes the reserve, by the awarded total.
- R2: one correction (withdraw -> republish) strictly inside the original
  verification window; total <= the original pinned cap.
- Bounties: 5% recycled into the mining vault, 95% escrowed, 0% burn.
- Founder vesting: 1-year cliff, then linear until year 5.
"""

from __future__ import annotations

from datetime import datetime, timezone

DECIMALS = 6
UNIT = 10**DECIMALS
MAX_SUPPLY = 100_000_000 * UNIT
FOUNDER_ALLOCATION = 10_000_000 * UNIT
MINING_ALLOCATION = 90_000_000 * UNIT
DECAY_NUM = 379_735
DECAY_DEN = 1_000_000_000
BOUNTY_FEE_DIVISOR = 20
MIN_BOUNTY = UNIT

DAY = 86_400
YEAR_EPOCHS = 365
YEAR = YEAR_EPOCHS * DAY
COMMIT_END = 72_000
REVEAL_END = 79_200
CLOSE_GRACE = 21_600
PUBLISH_WINDOW = 172_800
CLAIM_DELAY = 259_200
HALF_LIFE_EPOCHS = 1_825

STATUSES = ("OPEN", "CLOSED", "PUBLISHED", "WITHDRAWN", "CORRECTED", "FINAL", "EXPIRED")
HOLDING = ("CLOSED", "PUBLISHED", "WITHDRAWN", "CORRECTED")

assert FOUNDER_ALLOCATION + MINING_ALLOCATION == MAX_SUPPLY
assert FOUNDER_ALLOCATION * 10 == MAX_SUPPLY


def epoch_cap(available: int) -> int:
    return available * DECAY_NUM // DECAY_DEN


def available(vault_balance: int, pending: int, outstanding: int) -> int:
    a = vault_balance - pending - outstanding
    if a < 0:
        raise ValueError("reserve underflow: V < P + O")
    return a


def scaled(production_seconds: int, epoch_seconds: int = DAY) -> int:
    return production_seconds * epoch_seconds // DAY


def epoch_start(genesis_ts: int, epoch: int, epoch_seconds: int = DAY) -> int:
    return genesis_ts + epoch * epoch_seconds


def close_window(genesis_ts: int, epoch: int, epoch_seconds: int = DAY) -> tuple[int, int]:
    """[start + REVEAL_END, start + EPOCH + CLOSE_GRACE)"""

    s = epoch_start(genesis_ts, epoch, epoch_seconds)
    return s + scaled(REVEAL_END, epoch_seconds), s + epoch_seconds + scaled(CLOSE_GRACE, epoch_seconds)


def epoch_index(genesis_ts: int, now_ts: int, epoch_seconds: int = DAY) -> int:
    return max(0, now_ts - genesis_ts) // epoch_seconds


def vested(genesis_ts: int, now_ts: int, epoch_seconds: int = DAY) -> int:
    year = YEAR_EPOCHS * epoch_seconds
    cliff, end = genesis_ts + year, genesis_ts + 5 * year
    if now_ts < cliff:
        return 0
    if now_ts >= end:
        return FOUNDER_ALLOCATION
    return FOUNDER_ALLOCATION * (now_ts - cliff) // (end - cliff)


def bounty_split(amount: int) -> tuple[int, int]:
    """(fee recycled into the mining vault, escrow for the solver)."""

    fee = amount // BOUNTY_FEE_DIVISOR
    return fee, amount - fee


def reserve_after(successful_full_epochs: int, start: int = MINING_ALLOCATION) -> int:
    a = start
    for _ in range(successful_full_epochs):
        a -= epoch_cap(a)
    return a


def iso(ts: int) -> str:
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def decay_table(years: int = 10) -> list[dict]:
    """Reserve and per-epoch cap at each year boundary, assuming every epoch is
    successful and pays its full cap (the fastest possible release)."""

    rows, a = [], MINING_ALLOCATION
    for y in range(years + 1):
        rows.append({"year": y, "successful_epochs": y * YEAR_EPOCHS, "reserve_base_units": a,
                     "next_epoch_cap_base_units": epoch_cap(a)})
        for _ in range(YEAR_EPOCHS):
            a -= epoch_cap(a)
    return rows
