# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/tooling.py — do not edit.
"""Season workdir helpers shared by the CLI, backend and tests."""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
from pathlib import Path

from . import LITE_ROOT
from .season import Beacon, SeasonManifest, render_solver_constants, season_challenge
from .submission import ReceiptLog
from ares_lite._core.code_synth.generator import GeneratedChallenge
from ares_lite._core.code_synth.verifier.wasm_binary import decode_module, encode_module

SOLVER_CRATE = LITE_ROOT / "solvers" / "graph_route"
SOLVER_SOURCE = SOLVER_CRATE / "src" / "lib.rs"


def source_sha256(path: Path = SOLVER_SOURCE) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def canonicalize_module(raw: bytes) -> bytes:
    """Re-encode with the frozen codec (wasm-ld pads LEB128 integers)."""

    return encode_module(decode_module(raw))


def build_solver(
    difficulty: int,
    season_rs: str,
    features: list[str] | None = None,
    crate: Path = SOLVER_CRATE,
    target_tag: str = "",
) -> bytes:
    """Build the starter crate for a season and return canonical module bytes.

    The crate's committed `season.rs` is left untouched: a scratch copy of the
    crate is built with the season constants written into it.
    """

    import shutil
    import tempfile

    features = features or []
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "crate"
        shutil.copytree(crate, work, ignore=shutil.ignore_patterns("target"))
        (work / "src" / "season.rs").write_text(season_rs)
        env = dict(os.environ)
        cache = Path(os.environ.get("ARES_LITE_CACHE", Path.home() / ".cache" / "ares-lite")) / "graph_route" / f"cache{target_tag}"
        env["CARGO_TARGET_DIR_OVERRIDE"] = str(cache)
        out = subprocess.run(
            ["bash", str(work / "build.sh"), str(difficulty), *features],
            check=True,
            capture_output=True,
            text=True,
            env=env,
        ).stdout.strip().splitlines()[-1]
        return canonicalize_module(Path(out).read_bytes())


class Workdir:
    """Files of one season run. Never contains private keys."""

    def __init__(self, path: Path) -> None:
        self.path = Path(path)

    manifest_file = property(lambda self: self.path / "manifest.json")
    challenge_file = property(lambda self: self.path / "challenge.json")
    beacon_file = property(lambda self: self.path / "challenge_beacon.json")
    log_file = property(lambda self: self.path / "receipts.jsonl")
    baseline_file = property(lambda self: self.path / "baseline.wasm")
    season_rs_file = property(lambda self: self.path / "season.rs")
    results_file = property(lambda self: self.path / "results.json")
    reward_beacon_file = property(lambda self: self.path / "reward_beacon.json")
    chain_file = property(lambda self: self.path / "chain.json")
    # Non-consensus participant metadata (pool, AI agents); never scored.
    metadata_file = property(lambda self: self.path / "submission_metadata.jsonl")
    # Ratchet references: builds of manifest.reference_features for this season.
    references_dir = property(lambda self: self.path / "references")

    def reference_modules(self) -> list[bytes]:
        return [(self.references_dir / f"{name}.wasm").read_bytes() for name in self.manifest().reference_features]

    def manifest(self) -> SeasonManifest:
        return SeasonManifest.load(self.manifest_file)

    def challenge_beacon(self) -> Beacon:
        return Beacon(**json.loads(self.beacon_file.read_text()))

    def challenge(self) -> GeneratedChallenge:
        return season_challenge(self.manifest(), self.challenge_beacon())

    def log(self) -> ReceiptLog:
        manifest, challenge = self.manifest(), self.challenge()
        if not self.log_file.exists():
            return ReceiptLog(manifest, challenge)
        return ReceiptLog.load(self.log_file, manifest, challenge)

    def write_public_challenge(self, challenge: GeneratedChallenge) -> None:
        from ares_lite._core.canonical import encode

        data = {
            "challenge_id": challenge.challenge_id.hex(),
            "ticket_id": challenge.context.ticket_id.hex(),
            "mode": "GRAPH-ROUTE",
            "difficulty_index": challenge.context.difficulty_index,
            "task_spec": challenge.task_spec,
            "task_spec_fields": [
                "mode_id", "mode_version", "vertex_min", "vertex_max", "edge_min", "edge_max",
                "cost_max", "resource_max", "resource_budget", "hop_limit", "class_count",
                "required_mask", "forbidden_mask",
            ],
            "public_examples": challenge.public_examples,
        }
        if getattr(challenge, "is_scaled", False):
            data["profile"] = "lite-L1 (ARES Lite scaled GRAPH-ROUTE; not CODE-SYNTH v0 conformance)"
            data["scaled_config"] = challenge.config.as_list()
            data["fuel_per_test"] = challenge.config.fuel_per_test
            data["memory_pages"] = challenge.profile.memory_pages
        else:
            data["profile"] = "code-synth-v0"
            data["challenge_bytes_hex"] = challenge.challenge_bytes.hex()
            assert encode(challenge.value) == challenge.challenge_bytes
        self.challenge_file.write_text(json.dumps(data, indent=2) + "\n")
        self.season_rs_file.write_text(render_solver_constants(challenge))
