# GENERATED by lite/release/build_sdk.py from the frozen private module lite/ares_lite/transparency.py — do not edit.
"""Signed receipts and transparency checks for the Lite receipt log.

Not a consensus system, just cheap auditability:

- Every accepted entry gets a receipt signed by the season's receipt key
  (Ed25519; the public key is pinned in the season manifest, whose hash is
  committed on Solana). The signature covers (manifest_hash, seq, head), and
  because `head` chains every earlier entry, one signature commits the
  operator to the entire prefix.
- Checkpoints (the latest signed receipt) are published periodically.
- Anyone holding receipts/checkpoints can detect deletion, insertion,
  reordering, equivocation (two signed heads for one seq), forks and
  late insertion after close by comparing them against the published log.
"""

from __future__ import annotations

from dataclasses import dataclass

from ares_lite._core.canonical import hash_bytes, u64_be

from .submission import CLOSE_COMMITS, CLOSE_REVEALS, COMMIT, KIND_NAMES, REVEAL, verify_chain

RECEIPT_SIGNATURE = "ARES-LITE/RECEIPT-SIGNATURE/v0"


@dataclass(frozen=True)
class SignedReceipt:
    manifest_hash: bytes
    seq: int
    kind: str
    head: bytes
    signature: bytes

    def message(self) -> bytes:
        return receipt_message(self.manifest_hash, self.seq, self.head)

    def to_json(self) -> dict:
        return {"manifest_hash": self.manifest_hash.hex(), "seq": self.seq, "kind": self.kind,
                "head": self.head.hex(), "signature": self.signature.hex()}

    @classmethod
    def from_json(cls, data: dict) -> "SignedReceipt":
        return cls(bytes.fromhex(data["manifest_hash"]), data["seq"], data["kind"],
                   bytes.fromhex(data["head"]), bytes.fromhex(data["signature"]))


def receipt_message(manifest_hash: bytes, seq: int, head: bytes) -> bytes:
    return hash_bytes(RECEIPT_SIGNATURE, (manifest_hash, u64_be(seq), head))


def sign_receipt(keypair, manifest_hash: bytes, entry) -> SignedReceipt:
    signature = keypair.sign(receipt_message(manifest_hash, entry.seq, entry.head))
    return SignedReceipt(manifest_hash, entry.seq, KIND_NAMES[entry.kind], entry.head, signature)


def verify_receipt(public_key: bytes, receipt: SignedReceipt) -> bool:
    from Crypto.Signature import eddsa

    try:
        eddsa.new(eddsa.import_public_key(public_key), "rfc8032").verify(receipt.message(), receipt.signature)
        return True
    except (ValueError, TypeError):
        return False


class TransparencyViolation(ValueError):
    """Publicly verifiable evidence that the operator misbehaved."""


def check_receipt_against_log(public_key: bytes, receipt: SignedReceipt, entries: list[dict]) -> None:
    """Raise TransparencyViolation if a validly signed receipt is not honoured
    by the published log (deletion, insertion, reordering, fork, omission)."""

    if not verify_receipt(public_key, receipt):
        raise ValueError("receipt signature invalid (not evidence against the operator)")
    verify_chain(entries)  # the published log must at least be internally consistent
    if receipt.seq >= len(entries):
        raise TransparencyViolation(f"signed entry {receipt.seq} missing from published log (truncation/omission)")
    if entries[receipt.seq]["head"] != receipt.head.hex():
        raise TransparencyViolation(f"published head at seq {receipt.seq} differs from signed receipt (rewrite/fork)")


def detect_equivocation(public_key: bytes, receipts: list[SignedReceipt]) -> tuple[SignedReceipt, SignedReceipt] | None:
    """Two validly signed, different heads for the same seq prove a fork."""

    by_seq: dict[int, SignedReceipt] = {}
    for receipt in receipts:
        if not verify_receipt(public_key, receipt):
            continue
        prior = by_seq.get(receipt.seq)
        if prior and prior.head != receipt.head and prior.manifest_hash == receipt.manifest_hash:
            return prior, receipt
        by_seq.setdefault(receipt.seq, receipt)
    return None


def check_closed_log(entries: list[dict]) -> None:
    """Structural rules of a final log: no commit after CLOSE_COMMITS, nothing
    after CLOSE_REVEALS, exactly one of each close marker."""

    verify_chain(entries)
    kinds = [KIND_NAMES.index(e["kind"]) for e in entries]
    if kinds.count(CLOSE_COMMITS) != 1 or kinds.count(CLOSE_REVEALS) != 1:
        raise TransparencyViolation("final log must contain exactly one close of each kind")
    close_c, close_r = kinds.index(CLOSE_COMMITS), kinds.index(CLOSE_REVEALS)
    if close_r != len(kinds) - 1:
        raise TransparencyViolation("entries after CLOSE_REVEALS (late insertion)")
    if any(k == COMMIT for k in kinds[close_c:]):
        raise TransparencyViolation("commit after CLOSE_COMMITS (late insertion)")
    if any(k == REVEAL for k in kinds[close_r:]):
        raise TransparencyViolation("reveal after CLOSE_REVEALS (late insertion)")
