# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/commit_reveal/model.py — do not edit.
"""Immutable state and protocol values for Commit/Reveal research v0.

This module models only state needed to validate and record Commit and Reveal
Submissions. Lane Round transitions, ticket accounting, verification, and
reward selection remain separate roadmap components. Previous snapshots are
retained by value so a caller can restore a surviving canonical state after a
simulated reorganization without mutating or compensating the reverted state.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, IntEnum

from ares_lite._core.canonical import CanonicalTranscriptError, lane_round_key
from ares_lite._core.canonical.hashing import u8


class ResultCode(IntEnum):
    """Frozen P0-T03 state-machine result bytes."""

    APPLIED = 0
    OBJECT_TOO_LARGE = 1
    MALFORMED_OBJECT = 2
    UNSUPPORTED_VERSION = 3
    UNKNOWN_ROUND = 4
    INVALID_TRANSITION = 5
    EARLY_OBJECT = 6
    LATE_OBJECT = 7
    WRONG_BINDING = 8
    UNKNOWN_TICKET = 9
    TICKET_INELIGIBLE = 10
    UNAUTHORIZED = 11
    ALREADY_COMMITTED = 12
    ALREADY_REVEALED = 13
    COMMITMENT_MISMATCH = 14
    FAMILY_HASH_ERROR = 15
    SET_NOT_FINAL = 16
    INVALID_SEED_EVIDENCE = 17
    DUPLICATE_ISSUANCE = 18
    INTERNAL_INCONSISTENCY = 255

    @property
    def encoded(self) -> bytes:
        return u8(self.value)


class LaneRoundPhase(IntEnum):
    """Frozen P0-T03 Lane Round phase codes."""

    CONFIGURED = 0
    RESERVATION_OPEN = 1
    ALLOCATION_PENDING = 2
    CHALLENGE_SEED_PENDING = 3
    CHALLENGE_NOTICE = 4
    COMMIT_OPEN = 5
    VERIFICATION_SEED_PENDING = 6
    REVEAL_NOTICE = 7
    REVEAL_OPEN = 8
    POST_REVEAL = 9
    SELECTION_READY = 10
    SETTLEMENT_PENDING = 11
    FINALIZED = 12
    ABORTED_PRE_CHALLENGE = 128
    ABORTED_POST_CHALLENGE = 129

    @property
    def terminal(self) -> bool:
        return self in {
            LaneRoundPhase.FINALIZED,
            LaneRoundPhase.ABORTED_PRE_CHALLENGE,
            LaneRoundPhase.ABORTED_POST_CHALLENGE,
        }


class TicketAdmission(Enum):
    """Research placeholder for the P0-T04 admission/challenge component."""

    CHALLENGE_READY_BURNED = "CHALLENGE_READY_BURNED"
    CHALLENGE_FAILED_BURNED = "CHALLENGE_FAILED_BURNED"
    ALLOCATED_ESCROWED = "ALLOCATED_ESCROWED"


class StateInvariantError(ValueError):
    """An immutable reference snapshot violates canonical record invariants."""


@dataclass(frozen=True, slots=True)
class SlotWindow:
    """A nonempty half-open consensus-slot interval."""

    open_slot: int
    close_slot: int

    def __post_init__(self) -> None:
        _require_uint(self.open_slot, 64, "open_slot")
        _require_uint(self.close_slot, 64, "close_slot")
        if self.open_slot >= self.close_slot:
            raise ValueError("slot window must be nonempty and increasing")


@dataclass(frozen=True, slots=True)
class TicketBinding:
    """The immutable P0-T03 Ticket Binding fields used by this task."""

    lane_round_key: tuple[object, ...]
    ticket_id: bytes
    mining_key_ref: bytes
    reward_address: bytes
    family_config_ref: bytes
    difficulty_index: int

    def __post_init__(self) -> None:
        _require_lane_round_key(self.lane_round_key)
        _require_bytes(self.ticket_id, 32, 32, "ticket_id")
        _require_bytes(self.mining_key_ref, 32, 32, "mining_key_ref")
        _require_bytes(self.reward_address, 1, 128, "reward_address")
        _require_bytes(self.family_config_ref, 32, 32, "family_config_ref")
        _require_uint(self.difficulty_index, 32, "difficulty_index")

    @property
    def canonical_value(self) -> list[object]:
        return [
            0,
            list(self.lane_round_key),
            self.ticket_id,
            self.mining_key_ref,
            self.reward_address,
            self.family_config_ref,
            self.difficulty_index,
        ]


@dataclass(frozen=True, slots=True)
class TicketContext:
    """Test-only ticket eligibility and Challenge binding supplied to P1."""

    binding: TicketBinding
    admission: TicketAdmission
    challenge_id: bytes | None
    expired: bool = False

    def __post_init__(self) -> None:
        if self.challenge_id is not None:
            _require_bytes(self.challenge_id, 32, 32, "challenge_id")
        if type(self.expired) is not bool:
            raise ValueError("expired must be a bool")
        if (
            self.admission is TicketAdmission.CHALLENGE_READY_BURNED
            and self.challenge_id is None
        ):
            raise ValueError("Challenge-ready ticket must have a Challenge ID")
        if (
            self.admission is not TicketAdmission.CHALLENGE_READY_BURNED
            and self.challenge_id is not None
        ):
            raise ValueError("non-ready ticket cannot have a Challenge ID")


@dataclass(frozen=True, slots=True)
class RoundContext:
    """Immutable Host-derived context required by Commit/Reveal validation.

    The configuration reference and adjustment epoch are intentionally not
    copied into the commitment preimage. They remain fixed in this context and
    are bound indirectly through the frozen Lane Round, Ticket Binding, and
    ticket-specific Challenge ID construction.
    """

    lane_round_key: tuple[object, ...]
    lane_round_config_ref: bytes
    adjustment_epoch: int
    family_config_ref: bytes
    difficulty_index: int
    phase: LaneRoundPhase
    commit_window: SlotWindow | None
    reveal_window: SlotWindow | None
    tickets: tuple[TicketContext, ...]

    def __post_init__(self) -> None:
        _require_lane_round_key(self.lane_round_key)
        _require_bytes(
            self.lane_round_config_ref, 32, 32, "lane_round_config_ref"
        )
        _require_uint(self.adjustment_epoch, 64, "adjustment_epoch")
        _require_bytes(self.family_config_ref, 32, 32, "family_config_ref")
        _require_uint(self.difficulty_index, 32, "difficulty_index")
        if not isinstance(self.phase, LaneRoundPhase):
            raise ValueError("phase must be a LaneRoundPhase")
        if self.commit_window is not None and not isinstance(
            self.commit_window, SlotWindow
        ):
            raise ValueError("commit_window must be SlotWindow or None")
        if self.reveal_window is not None and not isinstance(
            self.reveal_window, SlotWindow
        ):
            raise ValueError("reveal_window must be SlotWindow or None")
        if not isinstance(self.tickets, tuple):
            raise ValueError("tickets must be an immutable tuple")
        if any(not isinstance(ticket, TicketContext) for ticket in self.tickets):
            raise ValueError("tickets must contain only TicketContext values")
        ordered = tuple(sorted(self.tickets, key=lambda item: item.binding.ticket_id))
        if any(
            left.binding.ticket_id == right.binding.ticket_id
            for left, right in zip(ordered, ordered[1:])
        ):
            raise ValueError("round context contains a duplicate Ticket ID")
        object.__setattr__(self, "tickets", ordered)

    @property
    def configuration_bindings_consistent(self) -> bool:
        return all(
            ticket.binding.lane_round_key == self.lane_round_key
            and ticket.binding.family_config_ref == self.family_config_ref
            and ticket.binding.difficulty_index == self.difficulty_index
            for ticket in self.tickets
        )

    def ticket(self, ticket_id: bytes) -> TicketContext | None:
        for ticket in self.tickets:
            if ticket.binding.ticket_id == ticket_id:
                return ticket
        return None


@dataclass(frozen=True, slots=True)
class CommitRecord:
    ticket_id: bytes
    challenge_id: bytes
    commitment: bytes
    commit_slot: int

    def __post_init__(self) -> None:
        _require_bytes(self.ticket_id, 32, 32, "ticket_id")
        _require_bytes(self.challenge_id, 32, 32, "challenge_id")
        _require_bytes(self.commitment, 32, 32, "commitment")
        _require_uint(self.commit_slot, 64, "commit_slot")

    @property
    def canonical_value(self) -> list[object]:
        return [self.ticket_id, self.challenge_id, self.commitment, self.commit_slot]


@dataclass(frozen=True, slots=True)
class RevealRecord:
    ticket_id: bytes
    challenge_id: bytes
    reveal_hash: bytes
    solution_hash: bytes
    reveal_slot: int

    def __post_init__(self) -> None:
        _require_bytes(self.ticket_id, 32, 32, "ticket_id")
        _require_bytes(self.challenge_id, 32, 32, "challenge_id")
        _require_bytes(self.reveal_hash, 32, 32, "reveal_hash")
        _require_bytes(self.solution_hash, 32, 32, "solution_hash")
        _require_uint(self.reveal_slot, 64, "reveal_slot")

    @property
    def canonical_value(self) -> list[object]:
        return [
            self.ticket_id,
            self.challenge_id,
            self.reveal_hash,
            self.solution_hash,
            self.reveal_slot,
        ]


@dataclass(frozen=True, slots=True)
class CommitRevealSnapshot:
    """Canonical immutable Commit and Reveal Record sets for one Lane Round."""

    commits: tuple[CommitRecord, ...] = ()
    reveals: tuple[RevealRecord, ...] = ()

    def __post_init__(self) -> None:
        commits = _ordered_unique(self.commits, "Commit")
        reveals = _ordered_unique(self.reveals, "Reveal")
        commit_ids = {record.ticket_id for record in commits}
        if any(record.ticket_id not in commit_ids for record in reveals):
            raise StateInvariantError("Reveal Record has no Commit Record")
        object.__setattr__(self, "commits", commits)
        object.__setattr__(self, "reveals", reveals)

    def commit(self, ticket_id: bytes) -> CommitRecord | None:
        return _find_record(self.commits, ticket_id)

    def reveal(self, ticket_id: bytes) -> RevealRecord | None:
        return _find_record(self.reveals, ticket_id)

    def with_commit(self, record: CommitRecord) -> CommitRevealSnapshot:
        if self.commit(record.ticket_id) is not None:
            raise StateInvariantError("Commit Record key already exists")
        return CommitRevealSnapshot(self.commits + (record,), self.reveals)

    def with_reveal(self, record: RevealRecord) -> CommitRevealSnapshot:
        if self.commit(record.ticket_id) is None:
            raise StateInvariantError("Reveal Record has no Commit Record")
        if self.reveal(record.ticket_id) is not None:
            raise StateInvariantError("Reveal Record key already exists")
        return CommitRevealSnapshot(self.commits, self.reveals + (record,))


@dataclass(frozen=True, slots=True)
class ValidationResult:
    """One canonical result and the resulting immutable snapshot."""

    code: ResultCode
    snapshot: CommitRevealSnapshot
    record: CommitRecord | RevealRecord | None = None

    @property
    def result_bytes(self) -> bytes:
        return self.code.encoded


def _ordered_unique(
    records: tuple[CommitRecord, ...] | tuple[RevealRecord, ...],
    kind: str,
) -> tuple:
    if not isinstance(records, tuple):
        raise StateInvariantError(f"{kind} Records must be an immutable tuple")
    ordered = tuple(sorted(records, key=lambda record: record.ticket_id))
    if any(
        left.ticket_id == right.ticket_id
        for left, right in zip(ordered, ordered[1:])
    ):
        raise StateInvariantError(f"{kind} Record set contains a duplicate Ticket ID")
    return ordered


def _find_record(records: tuple, ticket_id: bytes):
    for record in records:
        if record.ticket_id == ticket_id:
            return record
    return None


def _require_bytes(
    value: bytes, minimum: int, maximum: int, name: str
) -> None:
    if not isinstance(value, bytes) or not minimum <= len(value) <= maximum:
        if minimum == maximum:
            raise ValueError(f"{name} must contain exactly {minimum} bytes")
        raise ValueError(f"{name} must contain {minimum} through {maximum} bytes")


def _require_uint(value: int, bits: int, name: str) -> None:
    if type(value) is not int or not 0 <= value < 1 << bits:
        raise ValueError(f"{name} must be an unsigned {bits}-bit integer")


def _require_lane_round_key(value: tuple[object, ...]) -> None:
    if not isinstance(value, tuple) or len(value) != 6:
        raise ValueError("lane_round_key must be an immutable six-field tuple")
    try:
        canonical = tuple(
            lane_round_key(value[1], value[2], value[3], value[4], value[5])
        )
    except (CanonicalTranscriptError, IndexError) as exc:
        raise ValueError("lane_round_key is malformed") from exc
    if value != canonical:
        raise ValueError("lane_round_key is not the frozen v0 canonical key")
