# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/commit_reveal/transcripts.py — do not edit.
"""Canonical Commit/Reveal schemas and domain-separated transcripts."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable

from ares_lite._core.canonical import decode, encode, hash_bytes
from ares_lite._core.canonical.codec import CanonicalDecodingError
from ares_lite._core.canonical.domains import (
    CODE_SYNTH_SOLUTION_HASH,
    RACE_COMMITMENT,
    RACE_COMMITMENT_SET,
    RACE_REVEAL,
    RACE_REVEAL_SET,
)

from .model import CommitRecord, RevealRecord, TicketBinding


class SubmissionMalformed(ValueError):
    """Raw submission bytes do not match the frozen canonical schema."""


@dataclass(frozen=True, slots=True)
class CommitSubmission:
    schema_version: int
    lane_round_key: tuple[object, ...]
    ticket_id: bytes
    challenge_id: bytes
    commitment: bytes

    @property
    def canonical_value(self) -> list[object]:
        return [
            self.schema_version,
            list(self.lane_round_key),
            self.ticket_id,
            self.challenge_id,
            self.commitment,
        ]


@dataclass(frozen=True, slots=True)
class RevealSubmission:
    schema_version: int
    lane_round_key: tuple[object, ...]
    ticket_id: bytes
    challenge_id: bytes
    canonical_solution_bytes: bytes
    salt: bytes

    @property
    def canonical_value(self) -> list[object]:
        return [
            self.schema_version,
            list(self.lane_round_key),
            self.ticket_id,
            self.challenge_id,
            self.canonical_solution_bytes,
            self.salt,
        ]


@dataclass(frozen=True, slots=True)
class CommitmentArtifacts:
    solution_hash: bytes
    preimage: list[object]
    preimage_bytes: bytes
    commitment: bytes


def parse_commit_submission(data: bytes) -> CommitSubmission:
    value = _decode_canonical(data)
    if not isinstance(value, list) or len(value) != 5:
        raise SubmissionMalformed("Commit Submission must be a five-field array")
    schema_version = _uint(value[0], 8, "commit schema version")
    lane_key = _lane_round_key(value[1])
    return CommitSubmission(
        schema_version,
        lane_key,
        _fixed_bytes(value[2], 32, "ticket_id"),
        _fixed_bytes(value[3], 32, "challenge_id"),
        _fixed_bytes(value[4], 32, "commitment"),
    )


def parse_reveal_submission(data: bytes) -> RevealSubmission:
    value = _decode_canonical(data)
    if not isinstance(value, list) or len(value) != 6:
        raise SubmissionMalformed("Reveal Submission must be a six-field array")
    schema_version = _uint(value[0], 8, "reveal schema version")
    lane_key = _lane_round_key(value[1])
    solution_bytes = value[4]
    if not isinstance(solution_bytes, bytes):
        raise SubmissionMalformed("canonical_solution_bytes must be a byte string")
    return RevealSubmission(
        schema_version,
        lane_key,
        _fixed_bytes(value[2], 32, "ticket_id"),
        _fixed_bytes(value[3], 32, "challenge_id"),
        solution_bytes,
        _fixed_bytes(value[5], 32, "salt"),
    )


def solution_hash(canonical_solution_bytes: bytes) -> bytes:
    if not isinstance(canonical_solution_bytes, bytes):
        raise ValueError("canonical_solution_bytes must be bytes")
    return hash_bytes(CODE_SYNTH_SOLUTION_HASH, (canonical_solution_bytes,))


def commitment_artifacts(
    binding: TicketBinding,
    challenge_id: bytes,
    canonical_solution_bytes: bytes,
    salt: bytes,
) -> CommitmentArtifacts:
    digest = solution_hash(canonical_solution_bytes)
    return commitment_from_solution_hash(binding, challenge_id, digest, salt)


def commitment_from_solution_hash(
    binding: TicketBinding,
    challenge_id: bytes,
    digest: bytes,
    salt: bytes,
) -> CommitmentArtifacts:
    """Construct the frozen preimage without re-hashing a revealed solution."""

    challenge_id = _fixed_bytes(challenge_id, 32, "challenge_id")
    digest = _fixed_bytes(digest, 32, "solution_hash")
    salt = _fixed_bytes(salt, 32, "salt")
    preimage = [
        0,
        list(binding.lane_round_key),
        binding.ticket_id,
        challenge_id,
        digest,
        binding.mining_key_ref,
        binding.reward_address,
        salt,
    ]
    preimage_bytes = encode(preimage)
    return CommitmentArtifacts(
        digest,
        preimage,
        preimage_bytes,
        hash_bytes(RACE_COMMITMENT, (preimage_bytes,)),
    )


def encode_commit_submission(
    lane_round_key: tuple[object, ...],
    ticket_id: bytes,
    challenge_id: bytes,
    commitment: bytes,
    *,
    schema_version: int = 0,
) -> bytes:
    return encode(
        CommitSubmission(
            _uint(schema_version, 8, "commit schema version"),
            _lane_round_key(list(lane_round_key)),
            _fixed_bytes(ticket_id, 32, "ticket_id"),
            _fixed_bytes(challenge_id, 32, "challenge_id"),
            _fixed_bytes(commitment, 32, "commitment"),
        ).canonical_value
    )


def encode_reveal_submission(
    lane_round_key: tuple[object, ...],
    ticket_id: bytes,
    challenge_id: bytes,
    canonical_solution_bytes: bytes,
    salt: bytes,
    *,
    schema_version: int = 0,
) -> bytes:
    if not isinstance(canonical_solution_bytes, bytes):
        raise ValueError("canonical_solution_bytes must be bytes")
    return encode(
        RevealSubmission(
            _uint(schema_version, 8, "reveal schema version"),
            _lane_round_key(list(lane_round_key)),
            _fixed_bytes(ticket_id, 32, "ticket_id"),
            _fixed_bytes(challenge_id, 32, "challenge_id"),
            canonical_solution_bytes,
            _fixed_bytes(salt, 32, "salt"),
        ).canonical_value
    )


def reveal_hash(submission_bytes: bytes) -> bytes:
    # Hash only bytes already proven canonical under the exact Reveal schema.
    parse_reveal_submission(submission_bytes)
    return hash_bytes(RACE_REVEAL, (submission_bytes,))


def commit_record_set_bytes(records: Iterable[CommitRecord]) -> bytes:
    ordered = _ordered_records(records)
    return encode([record.canonical_value for record in ordered])


def reveal_record_set_bytes(records: Iterable[RevealRecord]) -> bytes:
    ordered = _ordered_records(records)
    return encode([record.canonical_value for record in ordered])


def commitment_set_digest(records: Iterable[CommitRecord]) -> bytes:
    return hash_bytes(RACE_COMMITMENT_SET, (commit_record_set_bytes(records),))


def reveal_set_digest(records: Iterable[RevealRecord]) -> bytes:
    return hash_bytes(RACE_REVEAL_SET, (reveal_record_set_bytes(records),))


def _decode_canonical(data: bytes) -> object:
    if not isinstance(data, bytes):
        raise SubmissionMalformed("submission must be bytes")
    try:
        value = decode(data)
    except CanonicalDecodingError as exc:
        raise SubmissionMalformed(str(exc)) from exc
    if encode(value) != data:
        raise SubmissionMalformed("submission does not use canonical encoding")
    return value


def _lane_round_key(value: object) -> tuple[object, ...]:
    if not isinstance(value, list) or len(value) != 6:
        raise SubmissionMalformed("lane_round_key must be a six-field array")
    schema_version = _uint(value[0], 8, "Lane Round Key schema version")
    chain_id = value[1]
    if not isinstance(chain_id, bytes) or not 1 <= len(chain_id) <= 64:
        raise SubmissionMalformed("chain_id must contain 1 through 64 bytes")
    protocol_version = _uint(value[2], 32, "protocol_version")
    round_id = _uint(value[3], 64, "round_id")
    family_id = value[4]
    if not isinstance(family_id, str):
        raise SubmissionMalformed("family_id must be CBOR text")
    try:
        family_bytes = family_id.encode("ascii", errors="strict")
    except UnicodeEncodeError as exc:
        raise SubmissionMalformed("family_id must contain only ASCII") from exc
    if not 1 <= len(family_bytes) <= 64:
        raise SubmissionMalformed("family_id must contain 1 through 64 ASCII bytes")
    family_version = _uint(value[5], 16, "family_version")
    return (
        schema_version,
        chain_id,
        protocol_version,
        round_id,
        family_id,
        family_version,
    )


def _fixed_bytes(value: object, length: int, name: str) -> bytes:
    if not isinstance(value, bytes) or len(value) != length:
        raise SubmissionMalformed(f"{name} must contain exactly {length} bytes")
    return value


def _uint(value: object, bits: int, name: str) -> int:
    if type(value) is not int or not 0 <= value < 1 << bits:
        raise SubmissionMalformed(f"{name} must be an unsigned {bits}-bit integer")
    return value


def _ordered_records(records: Iterable) -> tuple:
    ordered = tuple(sorted(records, key=lambda record: record.ticket_id))
    if any(
        left.ticket_id == right.ticket_id
        for left, right in zip(ordered, ordered[1:])
    ):
        raise ValueError("record set contains a duplicate Ticket ID")
    return ordered
