# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/commit_reveal/validation.py — do not edit.
"""Ordered Commit and Reveal validation for the P0-T03 research profile.

Validation consumes canonical Host inclusion slots and caller-supplied immutable
round/ticket context. It has no wall clock, network, provider, verifier, or
reward dependency. Each function returns exactly one frozen result code and a
new immutable snapshot only on success.
"""

from __future__ import annotations

import hmac

from .model import (
    CommitRecord,
    CommitRevealSnapshot,
    LaneRoundPhase,
    ResultCode,
    RevealRecord,
    RoundContext,
    StateInvariantError,
    TicketAdmission,
    ValidationResult,
)
from .transcripts import (
    SubmissionMalformed,
    commitment_from_solution_hash,
    parse_commit_submission,
    parse_reveal_submission,
    reveal_hash,
    solution_hash,
)


SUPPORTED_PROTOCOL_VERSION = 1
SUPPORTED_FAMILY_ID = "CODE-SYNTH"
SUPPORTED_FAMILY_VERSION = 0
SUPPORTED_KEY_SCHEMA_VERSION = 0
SUPPORTED_SUBMISSION_SCHEMA_VERSION = 0


def apply_commit(
    submission_bytes: bytes,
    *,
    object_cap: int,
    round_context: RoundContext | None,
    snapshot: CommitRevealSnapshot,
    inclusion_slot: int,
    authenticated_mining_key_ref: bytes,
) -> ValidationResult:
    """Apply all fourteen frozen Commit validation passes in order."""

    _require_runtime_inputs(object_cap, snapshot, inclusion_slot)

    if isinstance(submission_bytes, bytes) and len(submission_bytes) > object_cap:
        return _reject(ResultCode.OBJECT_TOO_LARGE, snapshot)
    try:
        submission = parse_commit_submission(submission_bytes)
    except (SubmissionMalformed, TypeError, ValueError):
        return _reject(ResultCode.MALFORMED_OBJECT, snapshot)
    if not _supported(submission.schema_version, submission.lane_round_key):
        return _reject(ResultCode.UNSUPPORTED_VERSION, snapshot)
    if round_context is None:
        return _reject(ResultCode.UNKNOWN_ROUND, snapshot)
    if round_context.phase.terminal or round_context.commit_window is None:
        return _reject(ResultCode.INVALID_TRANSITION, snapshot)

    timing = _timing_result(inclusion_slot, round_context.commit_window)
    if timing is not None:
        return _reject(timing, snapshot)
    if round_context.phase is not LaneRoundPhase.COMMIT_OPEN:
        return _reject(ResultCode.INVALID_TRANSITION, snapshot)
    if (
        submission.lane_round_key != round_context.lane_round_key
        or not round_context.configuration_bindings_consistent
    ):
        return _reject(ResultCode.WRONG_BINDING, snapshot)

    ticket = round_context.ticket(submission.ticket_id)
    if ticket is None:
        return _reject(ResultCode.UNKNOWN_TICKET, snapshot)
    if (
        ticket.admission is not TicketAdmission.CHALLENGE_READY_BURNED
        or ticket.expired
    ):
        return _reject(ResultCode.TICKET_INELIGIBLE, snapshot)
    if submission.challenge_id != ticket.challenge_id:
        return _reject(ResultCode.WRONG_BINDING, snapshot)
    if authenticated_mining_key_ref != ticket.binding.mining_key_ref:
        return _reject(ResultCode.UNAUTHORIZED, snapshot)
    if snapshot.commit(submission.ticket_id) is not None:
        return _reject(ResultCode.ALREADY_COMMITTED, snapshot)

    record = CommitRecord(
        submission.ticket_id,
        submission.challenge_id,
        submission.commitment,
        inclusion_slot,
    )
    try:
        next_snapshot = snapshot.with_commit(record)
    except (StateInvariantError, TypeError, ValueError):
        return _reject(ResultCode.INTERNAL_INCONSISTENCY, snapshot)
    return ValidationResult(ResultCode.APPLIED, next_snapshot, record)


def apply_reveal(
    submission_bytes: bytes,
    *,
    object_cap: int,
    round_context: RoundContext | None,
    snapshot: CommitRevealSnapshot,
    inclusion_slot: int,
    authenticated_mining_key_ref: bytes,
) -> ValidationResult:
    """Apply all sixteen frozen Reveal validation passes in order."""

    _require_runtime_inputs(object_cap, snapshot, inclusion_slot)

    if isinstance(submission_bytes, bytes) and len(submission_bytes) > object_cap:
        return _reject(ResultCode.OBJECT_TOO_LARGE, snapshot)
    try:
        submission = parse_reveal_submission(submission_bytes)
    except (SubmissionMalformed, TypeError, ValueError):
        return _reject(ResultCode.MALFORMED_OBJECT, snapshot)
    if not _supported(submission.schema_version, submission.lane_round_key):
        return _reject(ResultCode.UNSUPPORTED_VERSION, snapshot)
    if round_context is None:
        return _reject(ResultCode.UNKNOWN_ROUND, snapshot)
    if round_context.phase.terminal or round_context.reveal_window is None:
        return _reject(ResultCode.INVALID_TRANSITION, snapshot)

    timing = _timing_result(inclusion_slot, round_context.reveal_window)
    if timing is not None:
        return _reject(timing, snapshot)
    if round_context.phase is not LaneRoundPhase.REVEAL_OPEN:
        return _reject(ResultCode.INVALID_TRANSITION, snapshot)
    if (
        submission.lane_round_key != round_context.lane_round_key
        or not round_context.configuration_bindings_consistent
    ):
        return _reject(ResultCode.WRONG_BINDING, snapshot)

    ticket = round_context.ticket(submission.ticket_id)
    if ticket is None:
        return _reject(ResultCode.UNKNOWN_TICKET, snapshot)
    commit_record = snapshot.commit(submission.ticket_id)
    if (
        commit_record is None
        or ticket.expired
        or ticket.admission is not TicketAdmission.CHALLENGE_READY_BURNED
    ):
        return _reject(ResultCode.TICKET_INELIGIBLE, snapshot)
    if (
        submission.challenge_id != commit_record.challenge_id
        or submission.challenge_id != ticket.challenge_id
    ):
        return _reject(ResultCode.WRONG_BINDING, snapshot)
    if authenticated_mining_key_ref != ticket.binding.mining_key_ref:
        return _reject(ResultCode.UNAUTHORIZED, snapshot)
    if snapshot.reveal(submission.ticket_id) is not None:
        return _reject(ResultCode.ALREADY_REVEALED, snapshot)

    try:
        digest = solution_hash(submission.canonical_solution_bytes)
        if not isinstance(digest, bytes) or len(digest) != 32:
            raise ValueError("family solution hash must contain exactly 32 bytes")
    # A family hashing adapter has one fail-closed consensus result regardless
    # of its diagnostic exception. Process-control BaseExceptions still escape.
    except Exception:
        return _reject(ResultCode.FAMILY_HASH_ERROR, snapshot)

    try:
        opening = commitment_from_solution_hash(
            ticket.binding,
            submission.challenge_id,
            digest,
            submission.salt,
        )
    except (TypeError, ValueError):
        return _reject(ResultCode.INTERNAL_INCONSISTENCY, snapshot)
    if not hmac.compare_digest(opening.commitment, commit_record.commitment):
        return _reject(ResultCode.COMMITMENT_MISMATCH, snapshot)

    try:
        recorded_reveal_hash = reveal_hash(submission_bytes)
        record = RevealRecord(
            submission.ticket_id,
            submission.challenge_id,
            recorded_reveal_hash,
            digest,
            inclusion_slot,
        )
        next_snapshot = snapshot.with_reveal(record)
    except (StateInvariantError, TypeError, ValueError):
        return _reject(ResultCode.INTERNAL_INCONSISTENCY, snapshot)
    return ValidationResult(ResultCode.APPLIED, next_snapshot, record)


def _supported(schema_version: int, lane_round_key: tuple[object, ...]) -> bool:
    return (
        schema_version == SUPPORTED_SUBMISSION_SCHEMA_VERSION
        and lane_round_key[0] == SUPPORTED_KEY_SCHEMA_VERSION
        and lane_round_key[2] == SUPPORTED_PROTOCOL_VERSION
        and lane_round_key[4] == SUPPORTED_FAMILY_ID
        and lane_round_key[5] == SUPPORTED_FAMILY_VERSION
    )


def _timing_result(inclusion_slot: int, window) -> ResultCode | None:
    if inclusion_slot < window.open_slot:
        return ResultCode.EARLY_OBJECT
    if inclusion_slot >= window.close_slot:
        return ResultCode.LATE_OBJECT
    return None


def _require_runtime_inputs(
    object_cap: int,
    snapshot: CommitRevealSnapshot,
    inclusion_slot: int,
) -> None:
    if type(object_cap) is not int or not 0 <= object_cap < 1 << 32:
        raise ValueError("object_cap must be a u32")
    if not isinstance(snapshot, CommitRevealSnapshot):
        raise TypeError("snapshot must be CommitRevealSnapshot")
    if type(inclusion_slot) is not int or not 0 <= inclusion_slot < 1 << 64:
        raise ValueError("inclusion_slot must be a u64")


def _reject(
    code: ResultCode, snapshot: CommitRevealSnapshot
) -> ValidationResult:
    return ValidationResult(code, snapshot)
