# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/verifier/model.py — do not edit.
"""Consensus-observable values for the CODE-SYNTH v0 verifier prototype.

The verifier has one frozen soundness class.  Outcomes describe processing of
one artifact and must not be confused with the strength of the soundness
claim.  In particular, TEST_VALID means only that all bounded Policy-0 tests
passed; it is not a statement of universal semantic correctness.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import IntEnum

from ares_lite._core.canonical import encode, hash_bytes
from ares_lite._core.canonical.domains import CODE_SYNTH_VERIFICATION_SEED_REF


class SoundnessClass(IntEnum):
    BOUNDED_TEST = 0


class VerifierOutcome(IntEnum):
    TEST_INVALID = 0
    TEST_VALID = 1
    VERIFIER_ERROR = 2


class VerifierError(IntEnum):
    NONE = 0
    NON_CANONICAL_SOLUTION = 1
    WRONG_BINDING = 2
    MODULE_TOO_LARGE = 3
    MALFORMED_WASM = 4
    NON_CANONICAL_WASM = 5
    DISALLOWED_FEATURE = 6
    INVALID_IMPORT_EXPORT = 7
    RESOURCE_PROFILE_VIOLATION = 8
    EXECUTION_TRAP = 9
    FUEL_EXHAUSTED = 10
    MEMORY_VIOLATION = 11
    INVALID_RETURN = 12
    NON_CANONICAL_OUTPUT = 13
    WRONG_OUTPUT = 14
    CALL_DEPTH_EXHAUSTED = 15
    TEST_GENERATION_FAILED = 128
    REFERENCE_EVALUATOR_FAILED = 129
    VERIFIER_INTERNAL_INCONSISTENCY = 130


@dataclass(frozen=True, slots=True)
class ResourceProfile:
    profile_id: int
    module_bytes: int
    memory_pages: int
    type_count: int
    function_count: int
    global_count: int
    locals_per_function: int
    control_nesting: int
    static_value_stack: int
    runtime_calls: int
    decoded_instructions: int
    input_bytes: int
    output_bytes: int
    fuel_per_test: int
    fuel_per_reveal: int
    reference_steps: int


RESOURCE_PROFILES: tuple[ResourceProfile, ...] = (
    ResourceProfile(0, 65_536, 2, 64, 64, 32, 256, 64, 512, 64, 50_000, 16_384, 4_096, 250_000, 5_000_000, 1_000_000),
    ResourceProfile(1, 98_304, 4, 96, 96, 64, 512, 96, 1_024, 96, 100_000, 16_384, 4_096, 500_000, 10_000_000, 2_000_000),
    ResourceProfile(2, 131_072, 8, 128, 128, 64, 1_024, 128, 2_048, 128, 200_000, 16_384, 4_096, 1_000_000, 20_000_000, 4_000_000),
)


STRATUM_TOTALS = (4, 4, 8, 4)


@dataclass(frozen=True, slots=True)
class VerifierResult:
    """The exact thirteen-field CODE-SYNTH v0 Verifier Result."""

    challenge_id: bytes
    solution_hash: bytes
    outcome: VerifierOutcome
    error: VerifierError
    verification_seed_ref: bytes
    completed_by_stratum: tuple[int, int, int, int] = (0, 0, 0, 0)
    fuel_charged: int = 0
    memory_pages: int = 0

    def __post_init__(self) -> None:
        _fixed_bytes(self.challenge_id, 32, "challenge_id")
        _fixed_bytes(self.solution_hash, 32, "solution_hash")
        _fixed_bytes(self.verification_seed_ref, 32, "verification_seed_ref")
        if not isinstance(self.outcome, VerifierOutcome):
            raise ValueError("outcome must be a VerifierOutcome")
        if not isinstance(self.error, VerifierError):
            raise ValueError("error must be a VerifierError")
        if (
            not isinstance(self.completed_by_stratum, tuple)
            or len(self.completed_by_stratum) != 4
        ):
            raise ValueError("completed_by_stratum must be an immutable four-item tuple")
        for value, maximum in zip(self.completed_by_stratum, STRATUM_TOTALS):
            _uint(value, 16, "completed stratum count")
            if value > maximum:
                raise ValueError("completed stratum count exceeds Policy 0")
        _uint(self.fuel_charged, 64, "fuel_charged")
        _uint(self.memory_pages, 32, "memory_pages")
        if not _is_hidden_test_prefix(self.completed_by_stratum):
            raise ValueError("completed stratum counts must describe one ordered prefix")
        if (self.fuel_charged or any(self.completed_by_stratum)) and not self.memory_pages:
            raise ValueError("executed work requires a nonzero fixed-memory page count")

        if self.outcome is VerifierOutcome.TEST_VALID:
            if self.error is not VerifierError.NONE:
                raise ValueError("TEST_VALID requires error NONE")
            if self.completed_by_stratum != STRATUM_TOTALS:
                raise ValueError("TEST_VALID requires all Policy-0 comparisons")
        elif self.outcome is VerifierOutcome.TEST_INVALID:
            if not 1 <= self.error.value <= 15:
                raise ValueError("TEST_INVALID requires a miner-invalidity error")
            if self.error.value <= 8 and (
                any(self.completed_by_stratum)
                or self.fuel_charged
                or self.memory_pages
            ):
                raise ValueError("static invalidity cannot contain execution counters")
            if self.error.value >= 9 and not self.memory_pages:
                raise ValueError("runtime invalidity requires instantiated memory")
        elif not 128 <= self.error.value <= 130:
            raise ValueError("VERIFIER_ERROR requires a verifier-family error")

    @property
    def canonical_value(self) -> list[object]:
        return [
            0,
            0,
            0,
            self.challenge_id,
            self.solution_hash,
            SoundnessClass.BOUNDED_TEST.value,
            self.outcome.value,
            self.error.value,
            0,
            self.verification_seed_ref,
            list(self.completed_by_stratum),
            self.fuel_charged,
            self.memory_pages,
        ]

    @property
    def canonical_bytes(self) -> bytes:
        return encode(self.canonical_value)


def verification_seed_reference(verification_seed: bytes) -> bytes:
    """Return the frozen seed reference, or zero for the Pass-0 length failure."""

    if not isinstance(verification_seed, bytes) or len(verification_seed) != 32:
        return bytes(32)
    return hash_bytes(CODE_SYNTH_VERIFICATION_SEED_REF, (verification_seed,))


def outcome_for(error: VerifierError) -> VerifierOutcome:
    if error is VerifierError.NONE:
        return VerifierOutcome.TEST_VALID
    if 1 <= error.value <= 15:
        return VerifierOutcome.TEST_INVALID
    return VerifierOutcome.VERIFIER_ERROR


def _fixed_bytes(value: bytes, length: int, name: str) -> None:
    if not isinstance(value, bytes) or len(value) != length:
        raise ValueError(f"{name} must contain exactly {length} bytes")


def _uint(value: int, bits: int, name: str) -> None:
    if type(value) is not int or not 0 <= value < 1 << bits:
        raise ValueError(f"{name} must be an unsigned {bits}-bit integer")


def _is_hidden_test_prefix(counts: tuple[int, int, int, int]) -> bool:
    partial_seen = False
    for count, maximum in zip(counts, STRATUM_TOTALS):
        if partial_seen and count:
            return False
        if count < maximum:
            partial_seen = True
    return True
