# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/verifier/runtime.py — do not edit.
"""Explicit-stack deterministic interpreter for the frozen ARES-WASM-V0 subset.

This is a research reference engine, not a production process-isolation claim.
It never invokes native module code and exposes no host functions.  All Wasm
integer semantics, bounds checks, traps, call frames, and fuel transitions are
implemented explicitly so Python arithmetic and recursion are not consensus
inputs.
"""

from __future__ import annotations

from dataclasses import dataclass

from .model import ResourceProfile, VerifierError
from .wasm_binary import FunctionBody, Instruction, WasmModule
from .wasm_validation import I32, I64


PAGE_BYTES = 65_536
MASK32 = (1 << 32) - 1
MASK64 = (1 << 64) - 1


class RuntimeFailure(Exception):
    """A deterministic miner-attributable execution result."""

    def __init__(self, error: VerifierError, fuel_charged: int) -> None:
        super().__init__(error.name)
        self.error = error
        self.fuel_charged = fuel_charged


@dataclass(frozen=True, slots=True)
class RuntimeResult:
    return_value: int
    memory: bytes
    fuel_charged: int
    reveal_fuel_remaining: int


@dataclass(slots=True)
class _Fuel:
    test_remaining: int
    reveal_remaining: int
    charged: int = 0

    def charge(self, amount: int) -> None:
        if amount and (self.test_remaining < amount or self.reveal_remaining < amount):
            raise RuntimeFailure(VerifierError.FUEL_EXHAUSTED, self.charged)
        self.test_remaining -= amount
        self.reveal_remaining -= amount
        self.charged += amount


@dataclass(slots=True)
class _Control:
    kind: int
    start: int
    end: int
    else_index: int | None
    stack_height: int
    result_count: int

    @property
    def branch_count(self) -> int:
        return 0 if self.kind == 0x03 else self.result_count


@dataclass(slots=True)
class _Frame:
    function_index: int
    locals: list[int]
    stack: list[int]
    controls: list[_Control]
    pc: int
    matches: dict[int, tuple[int | None, int]]


def execute(
    module: WasmModule,
    solve_index: int,
    profile: ResourceProfile,
    input_bytes: bytes,
    output_ptr: int,
    output_cap: int,
    reveal_fuel_remaining: int,
) -> RuntimeResult:
    """Instantiate one fresh module and invoke solve under exact fuel limits."""

    memory = bytearray(profile.memory_pages * PAGE_BYTES)
    if len(input_bytes) > len(memory) or output_ptr < len(input_bytes):
        raise ValueError("host ABI placement is inconsistent")
    if output_ptr + output_cap > len(memory):
        raise ValueError("host output region exceeds fixed memory")
    memory[: len(input_bytes)] = input_bytes
    memory[output_ptr : output_ptr + output_cap] = bytes(output_cap)
    globals_ = [
        _wrap(global_.initializer[0].immediate, 32 if global_.value_type == I32 else 64)
        for global_ in module.globals
    ]
    fuel = _Fuel(profile.fuel_per_test, reveal_fuel_remaining)
    frames = [
        _new_frame(
            module,
            solve_index,
            (0, len(input_bytes), output_ptr, output_cap),
        )
    ]

    try:
        while frames:
            frame = frames[-1]
            body = module.bodies[frame.function_index]
            if frame.pc >= len(body.instructions):
                _trap(fuel)
            instruction = body.instructions[frame.pc]
            opcode = instruction.opcode
            fuel.charge(0 if opcode in (0x05, 0x0B) else 1)
            frame.pc += 1

            if opcode == 0x00:
                _trap(fuel)
            elif opcode == 0x01:
                pass
            elif opcode in (0x02, 0x03, 0x04):
                _enter_control(frame, instruction)
            elif opcode == 0x05:
                control = frame.controls[-1]
                if control.kind != 0x04 or control.else_index != frame.pc - 1:
                    _trap(fuel)
                frame.pc = control.end
            elif opcode == 0x0B:
                returned = _end_control(frames)
                if returned is not None:
                    return RuntimeResult(
                        returned, bytes(memory), fuel.charged, fuel.reveal_remaining
                    )
            elif opcode == 0x0C:
                _branch(frame, instruction.immediate)
            elif opcode == 0x0D:
                condition = _pop(frame) & MASK32
                if condition:
                    _branch(frame, instruction.immediate)
            elif opcode == 0x0E:
                labels, default = instruction.immediate
                selector = _pop(frame) & MASK32
                _branch(frame, labels[selector] if selector < len(labels) else default)
            elif opcode == 0x0F:
                returned = _return_frame(frames)
                if returned is not None:
                    return RuntimeResult(
                        returned, bytes(memory), fuel.charged, fuel.reveal_remaining
                    )
            elif opcode == 0x10:
                callee = instruction.immediate
                callee_type = module.types[module.function_type_indices[callee]]
                arguments = tuple(
                    reversed([_pop(frame) for _ in reversed(callee_type.params)])
                )
                if len(frames) >= profile.runtime_calls:
                    raise RuntimeFailure(
                        VerifierError.CALL_DEPTH_EXHAUSTED, fuel.charged
                    )
                frames.append(_new_frame(module, callee, arguments))
            elif opcode == 0x1A:
                _pop(frame)
            elif opcode == 0x1B:
                condition = _pop(frame) & MASK32
                second = _pop(frame)
                first = _pop(frame)
                frame.stack.append(first if condition else second)
            elif opcode == 0x20:
                frame.stack.append(frame.locals[instruction.immediate])
            elif opcode == 0x21:
                frame.locals[instruction.immediate] = _pop(frame)
            elif opcode == 0x22:
                value = _pop(frame)
                frame.locals[instruction.immediate] = value
                frame.stack.append(value)
            elif opcode == 0x23:
                frame.stack.append(globals_[instruction.immediate])
            elif opcode == 0x24:
                globals_[instruction.immediate] = _pop(frame)
            elif 0x28 <= opcode <= 0x3E and opcode not in (0x2A, 0x2B, 0x38, 0x39):
                _memory_instruction(frame, instruction, memory, fuel)
            elif opcode == 0x3F:
                frame.stack.append(profile.memory_pages & MASK32)
            elif opcode == 0x41:
                frame.stack.append(instruction.immediate & MASK32)
            elif opcode == 0x42:
                frame.stack.append(instruction.immediate & MASK64)
            elif 0x45 <= opcode <= 0x5A:
                _comparison(frame, opcode)
            elif 0x67 <= opcode <= 0x8A:
                _integer_operation(frame, opcode, fuel)
            elif opcode == 0xA7:
                frame.stack.append(_pop(frame) & MASK32)
            elif opcode == 0xAC:
                frame.stack.append(_signed(_pop(frame), 32) & MASK64)
            elif opcode == 0xAD:
                frame.stack.append(_pop(frame) & MASK32)
            else:
                _trap(fuel)
    except IndexError:
        _trap(fuel)
    raise AssertionError("interpreter exited without returning")


def _new_frame(module: WasmModule, function_index: int, arguments: tuple[int, ...]) -> _Frame:
    function_type = module.types[module.function_type_indices[function_index]]
    body = module.bodies[function_index]
    locals_ = [
        _wrap(value, 32 if value_type == I32 else 64)
        for value, value_type in zip(arguments, function_type.params)
    ]
    for count, value_type in body.local_groups:
        locals_.extend([0] * count)
    matches = _control_matches(body)
    return _Frame(
        function_index,
        locals_,
        [],
        [_Control(-1, 0, len(body.instructions) - 1, None, 0, len(function_type.results))],
        0,
        matches,
    )


def _control_matches(body: FunctionBody) -> dict[int, tuple[int | None, int]]:
    matches: dict[int, tuple[int | None, int]] = {}
    stack: list[tuple[int, int | None]] = []
    for index, instruction in enumerate(body.instructions):
        if instruction.opcode in (0x02, 0x03, 0x04):
            stack.append((index, None))
        elif instruction.opcode == 0x05:
            if not stack:
                raise ValueError("validated function has unmatched else")
            opening, _ = stack[-1]
            stack[-1] = (opening, index)
        elif instruction.opcode == 0x0B and stack:
            opening, else_index = stack.pop()
            matches[opening] = (else_index, index)
    if stack:
        raise ValueError("validated function has unmatched control")
    return matches


def _enter_control(frame: _Frame, instruction: Instruction) -> None:
    opening = frame.pc - 1
    else_index, end = frame.matches[opening]
    result_count = 0 if instruction.immediate == -64 else 1
    if instruction.opcode == 0x04:
        condition = _pop(frame) & MASK32
    else:
        condition = 1
    control = _Control(
        instruction.opcode,
        frame.pc,
        end,
        else_index,
        len(frame.stack),
        result_count,
    )
    frame.controls.append(control)
    if instruction.opcode == 0x04 and not condition:
        frame.pc = else_index + 1 if else_index is not None else end


def _end_control(frames: list[_Frame]) -> int | None:
    frame = frames[-1]
    control = frame.controls.pop()
    values = _pop_results(frame, control.result_count)
    del frame.stack[control.stack_height:]
    frame.stack.extend(values)
    if control.kind != -1:
        return None
    result = frame.stack[-1] if control.result_count else None
    frames.pop()
    if frames:
        if result is not None:
            frames[-1].stack.append(result)
        return None
    return result


def _return_frame(frames: list[_Frame]) -> int | None:
    frame = frames[-1]
    outer = frame.controls[0]
    values = _pop_results(frame, outer.result_count)
    result = values[-1] if values else None
    frames.pop()
    if frames:
        if result is not None:
            frames[-1].stack.append(result)
        return None
    return result


def _branch(frame: _Frame, depth: int) -> None:
    target_index = len(frame.controls) - 1 - depth
    target = frame.controls[target_index]
    values = _pop_results(frame, target.branch_count)
    del frame.stack[target.stack_height:]
    frame.stack.extend(values)
    del frame.controls[target_index + 1 :]
    frame.pc = target.start if target.kind == 0x03 else target.end


def _pop_results(frame: _Frame, count: int) -> list[int]:
    if count == 0:
        return []
    if len(frame.stack) < count:
        raise IndexError("validated result stack underflow")
    return frame.stack[-count:]


def _pop(frame: _Frame) -> int:
    return frame.stack.pop()


def _memory_instruction(
    frame: _Frame,
    instruction: Instruction,
    memory: bytearray,
    fuel: _Fuel,
) -> None:
    opcode = instruction.opcode
    _, offset = instruction.immediate
    if opcode in _STORE:
        value = _pop(frame)
        address = (_pop(frame) & MASK32) + offset
        width, bits = _STORE[opcode]
        _memory_bounds(address, width, len(memory), fuel)
        memory[address : address + width] = (value & ((1 << bits) - 1)).to_bytes(
            width, "little"
        )
        return

    address = (_pop(frame) & MASK32) + offset
    width, result_bits, signed = _LOAD[opcode]
    _memory_bounds(address, width, len(memory), fuel)
    value = int.from_bytes(memory[address : address + width], "little")
    if signed:
        value = _signed(value, width * 8)
    frame.stack.append(_wrap(value, result_bits))


def _memory_bounds(address: int, width: int, size: int, fuel: _Fuel) -> None:
    if address < 0 or address + width > size:
        raise RuntimeFailure(VerifierError.MEMORY_VIOLATION, fuel.charged)


def _comparison(frame: _Frame, opcode: int) -> None:
    if opcode == 0x45:
        frame.stack.append(int((_pop(frame) & MASK32) == 0))
        return
    if opcode == 0x50:
        frame.stack.append(int((_pop(frame) & MASK64) == 0))
        return
    bits = 32 if opcode < 0x50 else 64
    base = 0x46 if bits == 32 else 0x51
    operation = opcode - base
    right = _pop(frame) & ((1 << bits) - 1)
    left = _pop(frame) & ((1 << bits) - 1)
    if operation == 0:
        result = left == right
    elif operation == 1:
        result = left != right
    elif operation == 2:
        result = _signed(left, bits) < _signed(right, bits)
    elif operation == 3:
        result = left < right
    elif operation == 4:
        result = _signed(left, bits) > _signed(right, bits)
    elif operation == 5:
        result = left > right
    elif operation == 6:
        result = _signed(left, bits) <= _signed(right, bits)
    elif operation == 7:
        result = left <= right
    elif operation == 8:
        result = _signed(left, bits) >= _signed(right, bits)
    else:
        result = left >= right
    frame.stack.append(int(result))


def _integer_operation(frame: _Frame, opcode: int, fuel: _Fuel) -> None:
    if 0x67 <= opcode <= 0x78:
        bits, base = 32, 0x67
    else:
        bits, base = 64, 0x79
    mask = (1 << bits) - 1
    operation = opcode - base
    if operation <= 2:
        value = _pop(frame) & mask
        if operation == 0:
            result = bits if value == 0 else bits - value.bit_length()
        elif operation == 1:
            result = bits if value == 0 else (value & -value).bit_length() - 1
        else:
            result = value.bit_count()
        frame.stack.append(result & mask)
        return

    right = _pop(frame) & mask
    left = _pop(frame) & mask
    if operation == 3:
        result = left + right
    elif operation == 4:
        result = left - right
    elif operation == 5:
        result = left * right
    elif operation == 6:
        result = _signed_div(left, right, bits, fuel)
    elif operation == 7:
        if right == 0:
            _trap(fuel)
        result = left // right
    elif operation == 8:
        result = _signed_rem(left, right, bits, fuel)
    elif operation == 9:
        if right == 0:
            _trap(fuel)
        result = left % right
    elif operation == 10:
        result = left & right
    elif operation == 11:
        result = left | right
    elif operation == 12:
        result = left ^ right
    elif operation == 13:
        result = left << (right % bits)
    elif operation == 14:
        result = _signed(left, bits) >> (right % bits)
    elif operation == 15:
        result = left >> (right % bits)
    elif operation == 16:
        count = right % bits
        result = left if count == 0 else (left << count) | (left >> (bits - count))
    else:
        count = right % bits
        result = left if count == 0 else (left >> count) | (left << (bits - count))
    frame.stack.append(result & mask)


def _signed_div(left: int, right: int, bits: int, fuel: _Fuel) -> int:
    dividend = _signed(left, bits)
    divisor = _signed(right, bits)
    if divisor == 0 or (dividend == -(1 << (bits - 1)) and divisor == -1):
        _trap(fuel)
    quotient = abs(dividend) // abs(divisor)
    return -quotient if (dividend < 0) != (divisor < 0) else quotient


def _signed_rem(left: int, right: int, bits: int, fuel: _Fuel) -> int:
    dividend = _signed(left, bits)
    divisor = _signed(right, bits)
    if divisor == 0:
        _trap(fuel)
    quotient = abs(dividend) // abs(divisor)
    if (dividend < 0) != (divisor < 0):
        quotient = -quotient
    return dividend - quotient * divisor


def _trap(fuel: _Fuel) -> None:
    raise RuntimeFailure(VerifierError.EXECUTION_TRAP, fuel.charged)


def _signed(value: int, bits: int) -> int:
    value &= (1 << bits) - 1
    sign = 1 << (bits - 1)
    return value - (1 << bits) if value & sign else value


def _wrap(value: int, bits: int) -> int:
    return value & ((1 << bits) - 1)


_LOAD = {
    0x28: (4, 32, False), 0x29: (8, 64, False),
    0x2C: (1, 32, True), 0x2D: (1, 32, False),
    0x2E: (2, 32, True), 0x2F: (2, 32, False),
    0x30: (1, 64, True), 0x31: (1, 64, False),
    0x32: (2, 64, True), 0x33: (2, 64, False),
    0x34: (4, 64, True), 0x35: (4, 64, False),
}
_STORE = {
    0x36: (4, 32), 0x37: (8, 64), 0x3A: (1, 8), 0x3B: (2, 16),
    0x3C: (1, 8), 0x3D: (2, 16), 0x3E: (4, 32),
}
