# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/verifier/verification.py — do not edit.
"""Ordered CODE-SYNTH v0 verification over one accepted Reveal.

The pipeline accepts only finalized P1-T03 records and never mutates the
Commit/Reveal state machine. It reconstructs challenge and hidden-test
material locally, applies frozen first-failure precedence, and emits one
canonical result. TEST_VALID is deliberately limited to the BOUNDED-TEST
soundness claim; it is not universal semantic correctness.
"""

from __future__ import annotations

from dataclasses import dataclass

from ares_lite._core.canonical import CanonicalDecodingError, decode, encode, hash_bytes
from ares_lite._core.canonical.domains import CODE_SYNTH_HIDDEN_CASE, CODE_SYNTH_TEST_ROOT
from ares_lite._core.canonical.hashing import u16_be, u32_be
from ares_lite._core.code_synth.evaluators import reference_evaluate
from ares_lite._core.code_synth.generator import (
    FAMILY_ID,
    GeneratedChallenge,
    construct_input,
    generate_challenge,
)
from ares_lite._core.code_synth.model import GenerationFailed, ReferenceEvaluationFailed
from ares_lite._core.commit_reveal import (
    RevealRecord,
    RevealSubmission,
    reveal_hash,
    solution_hash,
)

from .model import (
    RESOURCE_PROFILES,
    ResourceProfile,
    VerifierError,
    VerifierResult,
    outcome_for,
    verification_seed_reference,
)
from .runtime import RuntimeFailure, execute
from .wasm_binary import WasmStructuralError, decode_module, encode_module
from .wasm_validation import (
    WasmCoreValidationError,
    WasmFeatureError,
    WasmHostSurfaceError,
    WasmResourceError,
    validate_core,
    validate_feature_profile,
    validate_host_surface,
    validate_resources,
)


@dataclass(frozen=True, slots=True)
class VerificationInput:
    """Finalized host context passed to the family verifier.

    Reveal validity and commitment opening are established by P1-T03 before
    this object is constructed.  The verifier checks that those immutable
    records remain mutually consistent, but does not mutate Commit/Reveal state.
    """

    challenge: GeneratedChallenge
    reveal: RevealSubmission
    reveal_record: RevealRecord
    verification_seed: bytes


@dataclass(frozen=True, slots=True)
class _Solution:
    schema_version: int
    family_id: str
    family_version: int
    challenge_id: bytes
    execution_profile_id: int
    module_bytes: bytes


def verify_reveal(request: VerificationInput) -> VerifierResult:
    """Execute the frozen ten-pass pipeline and bounded hidden tests."""

    if not isinstance(request, VerificationInput):
        raise TypeError("verify_reveal requires VerificationInput")
    if not isinstance(request.challenge, GeneratedChallenge):
        raise TypeError("VerificationInput challenge must be GeneratedChallenge")
    if not isinstance(request.reveal, RevealSubmission):
        raise TypeError("VerificationInput reveal must be RevealSubmission")
    if not isinstance(request.reveal_record, RevealRecord):
        raise TypeError("VerificationInput reveal_record must be RevealRecord")

    challenge_id = request.challenge.challenge_id
    bound_solution_hash = request.reveal_record.solution_hash
    if not isinstance(challenge_id, bytes) or len(challenge_id) != 32:
        raise ValueError("finalized Challenge ID must contain exactly 32 bytes")
    if not isinstance(bound_solution_hash, bytes) or len(bound_solution_hash) != 32:
        raise ValueError("bound solution hash must contain exactly 32 bytes")

    seed_ref = verification_seed_reference(request.verification_seed)
    if not _host_context_consistent(request):
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.VERIFIER_INTERNAL_INCONSISTENCY,
            seed_ref,
        )

    try:
        solution = _parse_solution(request.reveal.canonical_solution_bytes)
    except (CanonicalDecodingError, ValueError):
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.NON_CANONICAL_SOLUTION,
            seed_ref,
        )

    if (
        solution.family_id != FAMILY_ID
        or solution.family_version != 0
        or solution.challenge_id != challenge_id
        or solution.execution_profile_id != 0
    ):
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.WRONG_BINDING,
            seed_ref,
        )

    profile = RESOURCE_PROFILES[request.challenge.context.difficulty_index]
    if len(solution.module_bytes) > profile.module_bytes:
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.MODULE_TOO_LARGE,
            seed_ref,
        )

    try:
        module = decode_module(solution.module_bytes)
    except WasmStructuralError:
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.MALFORMED_WASM,
            seed_ref,
        )

    if encode_module(module) != solution.module_bytes:
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.NON_CANONICAL_WASM,
            seed_ref,
        )

    try:
        validate_feature_profile(module)
    except WasmFeatureError:
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.DISALLOWED_FEATURE,
            seed_ref,
        )

    try:
        solve_index = validate_host_surface(module, profile)
    except WasmHostSurfaceError:
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.INVALID_IMPORT_EXPORT,
            seed_ref,
        )

    try:
        metrics = validate_core(module)
    except WasmCoreValidationError:
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.MALFORMED_WASM,
            seed_ref,
        )

    try:
        validate_resources(module, metrics, profile)
    except WasmResourceError:
        return _result(
            challenge_id,
            bound_solution_hash,
            VerifierError.RESOURCE_PROFILE_VIOLATION,
            seed_ref,
        )

    return _execute_hidden_tests(
        request,
        profile,
        module,
        solve_index,
        challenge_id,
        bound_solution_hash,
        seed_ref,
    )


def _host_context_consistent(request: VerificationInput) -> bool:
    challenge = request.challenge
    reveal = request.reveal
    record = request.reveal_record
    try:
        regenerated = generate_challenge(challenge.context, challenge.challenge_seed)
        lane_key = reveal.lane_round_key
        return (
            isinstance(request.verification_seed, bytes)
            and len(request.verification_seed) == 32
            and challenge == regenerated
            and challenge.context.difficulty_index in range(len(RESOURCE_PROFILES))
            and len(challenge.value) == 18
            and challenge.value[15] == 0
            and challenge.value[16] == challenge.context.difficulty_index
            and challenge.value[17] == 0
            and reveal.schema_version == 0
            and lane_key[0] == 0
            and reveal.ticket_id == challenge.context.ticket_id == record.ticket_id
            and reveal.challenge_id == challenge.challenge_id == record.challenge_id
            and solution_hash(reveal.canonical_solution_bytes) == record.solution_hash
            and reveal_hash(encode(reveal.canonical_value)) == record.reveal_hash
            and len(lane_key) == 6
            and lane_key[1] == challenge.context.chain_id
            and lane_key[2] == challenge.context.protocol_version
            and lane_key[3] == challenge.context.round_id
            and lane_key[4] == FAMILY_ID
            and lane_key[5] == challenge.context.family_version
        )
    except (GenerationFailed, IndexError, TypeError, ValueError):
        return False


def _parse_solution(data: bytes) -> _Solution:
    if not isinstance(data, bytes):
        raise ValueError("solution artifact must be bytes")
    value = decode(data)
    if encode(value) != data or not isinstance(value, list) or len(value) != 6:
        raise ValueError("solution is not the exact canonical six-field array")
    schema_version = _uint(value[0], 16, "solution_schema_version")
    if schema_version != 0:
        raise ValueError("CODE-SYNTH v0 requires solution_schema_version 0")
    if not isinstance(value[1], str):
        raise ValueError("family_id must be text")
    family_version = _uint(value[2], 16, "family_version")
    challenge_id = _fixed_bytes(value[3], 32, "challenge_id")
    execution_profile_id = _uint(value[4], 16, "execution_profile_id")
    if not isinstance(value[5], bytes):
        raise ValueError("module_bytes must be bytes")
    return _Solution(
        schema_version,
        value[1],
        family_version,
        challenge_id,
        execution_profile_id,
        value[5],
    )


def _execute_hidden_tests(
    request: VerificationInput,
    profile: ResourceProfile,
    module,
    solve_index: int,
    challenge_id: bytes,
    bound_solution_hash: bytes,
    seed_ref: bytes,
) -> VerifierResult:
    challenge = request.challenge
    test_root = hash_bytes(
        CODE_SYNTH_TEST_ROOT,
        (
            request.verification_seed,
            challenge_id,
            challenge.context.ticket_id,
            bound_solution_hash,
            u16_be(0),
        ),
    )
    completed = [0, 0, 0, 0]
    total_fuel = 0
    reveal_fuel_remaining = profile.fuel_per_reveal
    memory_pages = 0

    for ordinal in range(20):
        stratum, stratum_index = _stratum(ordinal)
        case_root = hash_bytes(
            CODE_SYNTH_HIDDEN_CASE,
            (
                test_root,
                u16_be(stratum),
                u32_be(stratum_index),
                u32_be(ordinal),
            ),
        )
        try:
            case_input = construct_input(
                challenge.mode_id, challenge.task_spec, case_root, ordinal
            )
        except GenerationFailed:
            return _result(
                challenge_id,
                bound_solution_hash,
                VerifierError.TEST_GENERATION_FAILED,
                seed_ref,
                tuple(completed),
                total_fuel,
                memory_pages,
            )
        try:
            expected = reference_evaluate(
                challenge.task_spec,
                case_input,
                step_limit=profile.reference_steps,
            )
        except ReferenceEvaluationFailed:
            return _result(
                challenge_id,
                bound_solution_hash,
                VerifierError.REFERENCE_EVALUATOR_FAILED,
                seed_ref,
                tuple(completed),
                total_fuel,
                memory_pages,
            )

        input_bytes = encode(case_input)
        output_ptr = 16 * ((len(input_bytes) + 15) // 16)
        output_cap = min(
            profile.output_bytes,
            profile.memory_pages * 65_536 - output_ptr,
        )
        if (
            len(input_bytes) > profile.input_bytes
            or output_ptr < len(input_bytes)
            or output_cap < 0
            or output_ptr + output_cap > profile.memory_pages * 65_536
        ):
            return _result(
                challenge_id,
                bound_solution_hash,
                VerifierError.VERIFIER_INTERNAL_INCONSISTENCY,
                seed_ref,
                tuple(completed),
                total_fuel,
                memory_pages,
            )

        memory_pages = profile.memory_pages
        try:
            execution = execute(
                module,
                solve_index,
                profile,
                input_bytes,
                output_ptr,
                output_cap,
                reveal_fuel_remaining,
            )
        except RuntimeFailure as failure:
            return _result(
                challenge_id,
                bound_solution_hash,
                failure.error,
                seed_ref,
                tuple(completed),
                total_fuel + failure.fuel_charged,
                memory_pages,
            )
        except ValueError:
            return _result(
                challenge_id,
                bound_solution_hash,
                VerifierError.VERIFIER_INTERNAL_INCONSISTENCY,
                seed_ref,
                tuple(completed),
                total_fuel,
                memory_pages,
            )
        total_fuel += execution.fuel_charged
        reveal_fuel_remaining = execution.reveal_fuel_remaining

        returned = _signed_i32(execution.return_value)
        if returned < 0 or returned > output_cap:
            return _result(
                challenge_id,
                bound_solution_hash,
                VerifierError.INVALID_RETURN,
                seed_ref,
                tuple(completed),
                total_fuel,
                memory_pages,
            )
        output_bytes = execution.memory[output_ptr : output_ptr + returned]
        try:
            actual = decode(output_bytes)
            if encode(actual) != output_bytes or not _matches_type(
                actual, challenge.output_type
            ):
                raise ValueError("output does not match the frozen type")
        except (CanonicalDecodingError, ValueError):
            return _result(
                challenge_id,
                bound_solution_hash,
                VerifierError.NON_CANONICAL_OUTPUT,
                seed_ref,
                tuple(completed),
                total_fuel,
                memory_pages,
            )
        if actual != expected:
            return _result(
                challenge_id,
                bound_solution_hash,
                VerifierError.WRONG_OUTPUT,
                seed_ref,
                tuple(completed),
                total_fuel,
                memory_pages,
            )
        completed[stratum] += 1

    return _result(
        challenge_id,
        bound_solution_hash,
        VerifierError.NONE,
        seed_ref,
        tuple(completed),
        total_fuel,
        memory_pages,
    )


def _matches_type(value: object, descriptor: object) -> bool:
    if descriptor == 0:
        return type(value) is int and value in (0, 1)
    if descriptor == 1:
        return type(value) is int and -(1 << 63) <= value < 1 << 63
    if descriptor == 2:
        return type(value) is int and 0 <= value < 1 << 64
    if not isinstance(descriptor, list) or not descriptor:
        return False
    if descriptor[0] == 3 and len(descriptor) == 2:
        return isinstance(value, bytes) and type(descriptor[1]) is int and len(value) <= descriptor[1]
    if descriptor[0] == 4 and len(descriptor) == 3:
        return (
            isinstance(value, list)
            and type(descriptor[2]) is int
            and len(value) <= descriptor[2]
            and all(_matches_type(item, descriptor[1]) for item in value)
        )
    if descriptor[0] == 5:
        return (
            isinstance(value, list)
            and len(value) == len(descriptor) - 1
            and all(
                _matches_type(item, item_type)
                for item, item_type in zip(value, descriptor[1:])
            )
        )
    return False


def _stratum(ordinal: int) -> tuple[int, int]:
    if ordinal < 4:
        return 0, ordinal
    if ordinal < 8:
        return 1, ordinal - 4
    if ordinal < 16:
        return 2, ordinal - 8
    return 3, ordinal - 16


def _result(
    challenge_id: bytes,
    bound_solution_hash: bytes,
    error: VerifierError,
    seed_ref: bytes,
    completed: tuple[int, int, int, int] = (0, 0, 0, 0),
    fuel: int = 0,
    memory_pages: int = 0,
) -> VerifierResult:
    return VerifierResult(
        challenge_id,
        bound_solution_hash,
        outcome_for(error),
        error,
        seed_ref,
        completed,
        fuel,
        memory_pages,
    )


def _signed_i32(value: int) -> int:
    value &= (1 << 32) - 1
    return value - (1 << 32) if value & (1 << 31) else value


def _fixed_bytes(value: object, length: int, name: str) -> bytes:
    if not isinstance(value, bytes) or len(value) != length:
        raise ValueError(f"{name} must contain exactly {length} bytes")
    return value


def _uint(value: object, bits: int, name: str) -> int:
    if type(value) is not int or not 0 <= value < 1 << bits:
        raise ValueError(f"{name} must be an unsigned {bits}-bit integer")
    return value
