# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/verifier/wasm_validation.py — do not edit.
"""Pass-separated ARES-WASM-V0 feature, Core, and resource validation.

Each public pass corresponds to one frozen verifier error class. Keeping
structural decoding, feature selection, host-surface checks, Core typing, and
resource accounting separate is consensus-critical: a module that violates
several rules must still produce the same first error everywhere. This module
validates programs but never executes miner-controlled code.
"""

from __future__ import annotations

from dataclasses import dataclass

from .model import ResourceProfile
from .wasm_binary import FunctionBody, FunctionType, Instruction, Limits, WasmModule


I32 = 0x7F
I64 = 0x7E
EMPTY_BLOCK = -64
UNKNOWN_TYPE = -1

ALLOWED_SECTIONS = frozenset({1, 2, 3, 6, 7, 10})
REQUIRED_FEATURE_SECTIONS = frozenset({1, 3, 10})
ALLOWED_OPCODES = frozenset(
    {*range(0x00, 0x06), *range(0x0B, 0x11), 0x1A, 0x1B,
     *range(0x20, 0x25), 0x28, 0x29, *range(0x2C, 0x38),
     *range(0x3A, 0x40), 0x41, 0x42, *range(0x45, 0x5B),
     *range(0x67, 0x8B), 0xA7, 0xAC, 0xAD}
)

NATURAL_ALIGNMENT = {
    0x28: 2, 0x29: 3,
    0x2C: 0, 0x2D: 0, 0x2E: 1, 0x2F: 1,
    0x30: 0, 0x31: 0, 0x32: 1, 0x33: 1, 0x34: 2, 0x35: 2,
    0x36: 2, 0x37: 3, 0x3A: 0, 0x3B: 1,
    0x3C: 0, 0x3D: 1, 0x3E: 2,
}


class WasmFeatureError(ValueError):
    """A structurally decoded feature lies outside ARES-WASM-V0."""


class WasmHostSurfaceError(ValueError):
    """The sole memory import or solve export is not exact."""


class WasmCoreValidationError(ValueError):
    """An allowed-profile module violates WebAssembly Core typing or indices."""


class WasmResourceError(ValueError):
    """A Core-valid module exceeds its selected research Resource Profile."""


@dataclass(frozen=True, slots=True)
class FunctionMetrics:
    locals_count: int
    control_nesting: int
    static_value_stack: int
    instructions: int


@dataclass(frozen=True, slots=True)
class ModuleMetrics:
    functions: tuple[FunctionMetrics, ...]
    decoded_instructions: int


@dataclass(slots=True)
class _Control:
    kind: int
    result_types: tuple[int, ...]
    branch_types: tuple[int, ...]
    height: int
    unreachable: bool = False
    else_seen: bool = False


def validate_feature_profile(module: WasmModule) -> None:
    ids = set(module.section_ids)
    if not REQUIRED_FEATURE_SECTIONS.issubset(ids):
        raise WasmFeatureError("required ARES-WASM-V0 section is absent")
    if any(section_id not in ALLOWED_SECTIONS for section_id in module.section_ids):
        raise WasmFeatureError("section is forbidden by ARES-WASM-V0")

    for function_type in module.types:
        if any(value not in (I32, I64) for value in (*function_type.params, *function_type.results)):
            raise WasmFeatureError("forbidden WebAssembly value type")
        if len(function_type.results) > 1:
            raise WasmFeatureError("multi-value function result is forbidden")

    for entry in module.imports:
        if entry.kind not in (0, 1, 2, 3):
            raise WasmFeatureError("proposal import descriptor is forbidden")
        if entry.kind in (1, 2):
            limits = entry.descriptor[1] if entry.kind == 1 else entry.descriptor
            if not isinstance(limits, Limits) or limits.flags not in (0, 1):
                raise WasmFeatureError("proposal-specific limits are forbidden")
        if entry.kind == 1:
            element_type = entry.descriptor[0]
            if element_type != 0x70:
                raise WasmFeatureError("proposal table element type is forbidden")
        if entry.kind == 3:
            value_type, mutable = entry.descriptor
            if value_type not in (I32, I64) or mutable not in (0, 1):
                raise WasmFeatureError("proposal global import type is forbidden")

    if any(entry.kind not in (0, 1, 2, 3) for entry in module.exports):
        raise WasmFeatureError("proposal export descriptor is forbidden")

    for global_ in module.globals:
        if global_.value_type not in (I32, I64) or global_.mutable not in (0, 1):
            raise WasmFeatureError("global type is outside ARES-WASM-V0")
        if len(global_.initializer) != 2 or global_.initializer[-1].opcode != 0x0B:
            raise WasmFeatureError("global initializer is outside ARES-WASM-V0")
        expected = 0x41 if global_.value_type == I32 else 0x42
        if global_.initializer[0].opcode != expected:
            raise WasmFeatureError("global initializer type is outside ARES-WASM-V0")

    for body in module.bodies:
        if any(value_type not in (I32, I64) for _, value_type in body.local_groups):
            raise WasmFeatureError("local type is outside ARES-WASM-V0")
        _validate_feature_instructions(body.instructions)


def _validate_feature_instructions(instructions: tuple[Instruction, ...]) -> None:
    for instruction in instructions:
        opcode = instruction.opcode
        if opcode not in ALLOWED_OPCODES:
            raise WasmFeatureError("opcode is outside the frozen whitelist")
        if opcode in (0x02, 0x03, 0x04) and instruction.immediate not in (
            EMPTY_BLOCK, -1, -2
        ):
            raise WasmFeatureError("block type is outside the single-result profile")
        if opcode == 0x3F and instruction.immediate != 0:
            raise WasmFeatureError("reserved memory immediate must be zero")


def validate_host_surface(module: WasmModule, profile: ResourceProfile) -> int:
    if 2 not in module.section_ids or 7 not in module.section_ids:
        raise WasmHostSurfaceError("Import and Export sections are required")
    if len(module.imports) != 1:
        raise WasmHostSurfaceError("exactly one memory import is required")
    imported = module.imports[0]
    expected_limits = Limits(1, profile.memory_pages, profile.memory_pages)
    if (
        imported.module != "ares"
        or imported.name != "memory"
        or imported.kind != 2
        or imported.descriptor != expected_limits
    ):
        raise WasmHostSurfaceError("memory import does not match ares.memory")

    if len(module.exports) != 1:
        raise WasmHostSurfaceError("exactly one solve export is required")
    exported = module.exports[0]
    if exported.name != "solve" or exported.kind != 0:
        raise WasmHostSurfaceError("sole export must be the solve function")
    if exported.index >= len(module.function_type_indices):
        raise WasmHostSurfaceError("solve does not refer to a defined function")
    type_index = module.function_type_indices[exported.index]
    if type_index >= len(module.types):
        raise WasmHostSurfaceError("solve has an out-of-range type index")
    if module.types[type_index] != FunctionType((I32, I32, I32, I32), (I32,)):
        raise WasmHostSurfaceError("solve has the wrong function signature")
    return exported.index


def validate_core(module: WasmModule) -> ModuleMetrics:
    if len(module.function_type_indices) != len(module.bodies):
        raise WasmCoreValidationError("Function and Code vector counts differ")
    for index in module.function_type_indices:
        if index >= len(module.types):
            raise WasmCoreValidationError("function type index is out of range")

    for global_ in module.globals:
        if global_.mutable not in (0, 1):
            raise WasmCoreValidationError("global mutability is invalid")

    metrics: list[FunctionMetrics] = []
    instruction_total = sum(len(global_.initializer) for global_ in module.globals)
    for function_index, (type_index, body) in enumerate(
        zip(module.function_type_indices, module.bodies)
    ):
        function_type = module.types[type_index]
        function_metrics = _validate_function(
            module, function_index, function_type, body
        )
        metrics.append(function_metrics)
        instruction_total += function_metrics.instructions
    return ModuleMetrics(tuple(metrics), instruction_total)


def validate_resources(
    module: WasmModule, metrics: ModuleMetrics, profile: ResourceProfile
) -> None:
    if len(module.types) > profile.type_count:
        raise WasmResourceError("type-count limit exceeded")
    if len(module.bodies) > profile.function_count:
        raise WasmResourceError("function-count limit exceeded")
    if len(module.globals) > profile.global_count:
        raise WasmResourceError("global-count limit exceeded")
    for metric in metrics.functions:
        if metric.locals_count > profile.locals_per_function:
            raise WasmResourceError("locals-per-function limit exceeded")
    for metric in metrics.functions:
        if metric.control_nesting > profile.control_nesting:
            raise WasmResourceError("control-nesting limit exceeded")
    for metric in metrics.functions:
        if metric.static_value_stack > profile.static_value_stack:
            raise WasmResourceError("static-value-stack limit exceeded")
    if metrics.decoded_instructions > profile.decoded_instructions:
        raise WasmResourceError("decoded-instruction limit exceeded")


def _validate_function(
    module: WasmModule,
    function_index: int,
    function_type: FunctionType,
    body: FunctionBody,
) -> FunctionMetrics:
    local_count = len(function_type.params) + sum(count for count, _ in body.local_groups)
    stack: list[int] = []
    controls = [_Control(-1, function_type.results, function_type.results, 0)]
    maximum_stack = 0
    maximum_nesting = 1

    def push(value_type: int) -> None:
        nonlocal maximum_stack
        stack.append(value_type)
        maximum_stack = max(maximum_stack, len(stack))

    def pop(expected: int | None = None) -> int | None:
        frame = controls[-1]
        if len(stack) == frame.height and frame.unreachable:
            return UNKNOWN_TYPE if expected is None else expected
        if len(stack) <= frame.height:
            raise WasmCoreValidationError("operand stack underflow")
        actual = stack.pop()
        if (
            expected is not None
            and expected != UNKNOWN_TYPE
            and actual not in (expected, UNKNOWN_TYPE)
        ):
            raise WasmCoreValidationError("operand type mismatch")
        if actual == UNKNOWN_TYPE and expected not in (None, UNKNOWN_TYPE):
            return expected
        return actual

    def pop_types(types: tuple[int, ...]) -> None:
        for value_type in reversed(types):
            pop(value_type)

    def make_unreachable() -> None:
        frame = controls[-1]
        del stack[frame.height:]
        frame.unreachable = True

    for instruction_index, instruction in enumerate(body.instructions):
        opcode = instruction.opcode
        if opcode == 0x00:
            make_unreachable()
        elif opcode == 0x01:
            pass
        elif opcode in (0x02, 0x03, 0x04):
            if opcode == 0x04:
                pop(I32)
            result = _block_result(instruction.immediate)
            controls.append(
                _Control(opcode, result, () if opcode == 0x03 else result, len(stack))
            )
            maximum_nesting = max(maximum_nesting, len(controls))
        elif opcode == 0x05:
            if len(controls) == 1 or controls[-1].kind != 0x04 or controls[-1].else_seen:
                raise WasmCoreValidationError("else does not match one open if")
            frame = controls[-1]
            pop_types(frame.result_types)
            if len(stack) != frame.height:
                raise WasmCoreValidationError("then branch leaves extra values")
            del stack[frame.height:]
            frame.unreachable = False
            frame.else_seen = True
        elif opcode == 0x0B:
            if not controls:
                raise WasmCoreValidationError("end has no control frame")
            frame = controls[-1]
            if frame.kind == 0x04 and frame.result_types and not frame.else_seen:
                raise WasmCoreValidationError("result-producing if requires else")
            pop_types(frame.result_types)
            if len(stack) != frame.height:
                raise WasmCoreValidationError("control frame leaves extra values")
            controls.pop()
            if controls:
                for value_type in frame.result_types:
                    push(value_type)
            elif instruction_index != len(body.instructions) - 1:
                raise WasmCoreValidationError("instructions follow the function end")
        elif opcode in (0x0C, 0x0D):
            target = _label(controls, instruction.immediate)
            if opcode == 0x0D:
                pop(I32)
                pop_types(target.branch_types)
                for value_type in target.branch_types:
                    push(value_type)
            else:
                pop_types(target.branch_types)
                make_unreachable()
        elif opcode == 0x0E:
            labels, default = instruction.immediate
            targets = [_label(controls, value) for value in (*labels, default)]
            expected = targets[-1].branch_types
            if any(target.branch_types != expected for target in targets):
                raise WasmCoreValidationError("br_table target types differ")
            pop(I32)
            pop_types(expected)
            make_unreachable()
        elif opcode == 0x0F:
            pop_types(function_type.results)
            make_unreachable()
        elif opcode == 0x10:
            callee = instruction.immediate
            if callee >= len(module.function_type_indices):
                raise WasmCoreValidationError("call function index is out of range")
            callee_type_index = module.function_type_indices[callee]
            if callee_type_index >= len(module.types):
                raise WasmCoreValidationError("callee type index is out of range")
            callee_type = module.types[callee_type_index]
            pop_types(callee_type.params)
            for value_type in callee_type.results:
                push(value_type)
        elif opcode == 0x1A:
            pop()
        elif opcode == 0x1B:
            pop(I32)
            second = pop()
            first = pop(second)
            if first == UNKNOWN_TYPE:
                push(second if second is not None else UNKNOWN_TYPE)
            else:
                push(first if first is not None else UNKNOWN_TYPE)
        elif 0x20 <= opcode <= 0x22:
            local_type = _local_type(function_type, body, instruction.immediate)
            if opcode == 0x20:
                push(local_type)
            elif opcode == 0x21:
                pop(local_type)
            else:
                pop(local_type)
                push(local_type)
        elif opcode in (0x23, 0x24):
            if instruction.immediate >= len(module.globals):
                raise WasmCoreValidationError("global index is out of range")
            global_ = module.globals[instruction.immediate]
            if opcode == 0x23:
                push(global_.value_type)
            else:
                if not global_.mutable:
                    raise WasmCoreValidationError("global.set targets immutable global")
                pop(global_.value_type)
        elif opcode in NATURAL_ALIGNMENT:
            alignment, _ = instruction.immediate
            if alignment > NATURAL_ALIGNMENT[opcode]:
                raise WasmCoreValidationError("memory alignment exceeds natural alignment")
            if opcode in _LOAD_RESULT:
                pop(I32)
                push(_LOAD_RESULT[opcode])
            else:
                pop(_STORE_VALUE[opcode])
                pop(I32)
        elif opcode == 0x3F:
            push(I32)
        elif opcode in (0x41, 0x42):
            push(I32 if opcode == 0x41 else I64)
        elif opcode in _I32_UNARY:
            pop(I32)
            push(I32)
        elif opcode in _I64_EQZ:
            pop(I64)
            push(I32)
        elif opcode in _I32_COMPARE:
            pop(I32); pop(I32); push(I32)
        elif opcode in _I64_COMPARE:
            pop(I64); pop(I64); push(I32)
        elif opcode in _I32_BINARY:
            pop(I32); pop(I32); push(I32)
        elif opcode in _I64_UNARY:
            pop(I64); push(I64)
        elif opcode in _I64_BINARY:
            pop(I64); pop(I64); push(I64)
        elif opcode == 0xA7:
            pop(I64); push(I32)
        elif opcode in (0xAC, 0xAD):
            pop(I32); push(I64)
        else:
            raise WasmCoreValidationError("profile instruction lacks Core validation")

    if controls:
        raise WasmCoreValidationError("function expression is not closed")
    return FunctionMetrics(local_count, maximum_nesting, maximum_stack, len(body.instructions))


def _block_result(block_type: int) -> tuple[int, ...]:
    if block_type == EMPTY_BLOCK:
        return ()
    if block_type == -1:
        return (I32,)
    if block_type == -2:
        return (I64,)
    raise WasmCoreValidationError("invalid block type")


def _label(controls: list[_Control], depth: int) -> _Control:
    if type(depth) is not int or depth < 0 or depth >= len(controls):
        raise WasmCoreValidationError("branch label depth is out of range")
    return controls[-1 - depth]


def _local_type(function_type: FunctionType, body: FunctionBody, index: int) -> int:
    if index < len(function_type.params):
        return function_type.params[index]
    remaining = index - len(function_type.params)
    for count, value_type in body.local_groups:
        if remaining < count:
            return value_type
        remaining -= count
    raise WasmCoreValidationError("local index is out of range")


_LOAD_RESULT = {
    0x28: I32, 0x29: I64, 0x2C: I32, 0x2D: I32, 0x2E: I32,
    0x2F: I32, 0x30: I64, 0x31: I64, 0x32: I64, 0x33: I64,
    0x34: I64, 0x35: I64,
}
_STORE_VALUE = {0x36: I32, 0x37: I64, 0x3A: I32, 0x3B: I32, 0x3C: I64, 0x3D: I64, 0x3E: I64}
_I32_UNARY = frozenset({0x45, 0x67, 0x68, 0x69})
_I64_EQZ = frozenset({0x50})
_I32_COMPARE = frozenset(range(0x46, 0x50))
_I64_COMPARE = frozenset(range(0x51, 0x5B))
_I32_BINARY = frozenset(range(0x6A, 0x79))
_I64_UNARY = frozenset(range(0x79, 0x7C))
_I64_BINARY = frozenset(range(0x7C, 0x8B))
