# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/code_synth/verifier/wasm_binary.py — do not edit.
"""Bounded structural decoder and canonical encoder for ARES-WASM-V0.

Structural decoding deliberately accepts bounded non-shortest LEB128 values.
The verifier's following pass re-encodes the parsed module and classifies those
aliases as NON_CANONICAL_WASM.  Unknown framing remains MALFORMED_WASM, while
recognized but forbidden WebAssembly features survive to the feature pass.
"""

from __future__ import annotations

from dataclasses import dataclass


MAGIC_VERSION = b"\x00asm\x01\x00\x00\x00"
KNOWN_SECTION_IDS = frozenset(range(13))


class WasmStructuralError(ValueError):
    """The byte stream cannot be framed as a bounded WebAssembly module."""


@dataclass(frozen=True, slots=True)
class FunctionType:
    params: tuple[int, ...]
    results: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class Limits:
    flags: int
    minimum: int
    maximum: int | None


@dataclass(frozen=True, slots=True)
class ImportEntry:
    module: str
    name: str
    kind: int
    descriptor: object


@dataclass(frozen=True, slots=True)
class ExportEntry:
    name: str
    kind: int
    index: int


@dataclass(frozen=True, slots=True)
class Instruction:
    opcode: int
    immediate: object = None


@dataclass(frozen=True, slots=True)
class GlobalEntry:
    value_type: int
    mutable: int
    initializer: tuple[Instruction, ...]


@dataclass(frozen=True, slots=True)
class ElementSegment:
    flags: int
    fields: tuple[object, ...]


@dataclass(frozen=True, slots=True)
class DataSegment:
    flags: int
    memory_index: int | None
    offset: tuple[Instruction, ...] | None
    data: bytes


@dataclass(frozen=True, slots=True)
class FunctionBody:
    local_groups: tuple[tuple[int, int], ...]
    instructions: tuple[Instruction, ...]

    @property
    def local_types(self) -> tuple[int, ...]:
        values: list[int] = []
        for count, value_type in self.local_groups:
            values.extend((value_type,) * count)
        return tuple(values)


@dataclass(frozen=True, slots=True)
class Section:
    section_id: int
    content: object


@dataclass(frozen=True, slots=True)
class WasmModule:
    sections: tuple[Section, ...]
    types: tuple[FunctionType, ...]
    imports: tuple[ImportEntry, ...]
    function_type_indices: tuple[int, ...]
    globals: tuple[GlobalEntry, ...]
    exports: tuple[ExportEntry, ...]
    bodies: tuple[FunctionBody, ...]

    @property
    def section_ids(self) -> tuple[int, ...]:
        return tuple(section.section_id for section in self.sections)


class _Reader:
    __slots__ = ("data", "offset")

    def __init__(self, data: bytes) -> None:
        self.data = data
        self.offset = 0

    @property
    def remaining(self) -> int:
        return len(self.data) - self.offset

    def byte(self) -> int:
        if self.offset >= len(self.data):
            raise WasmStructuralError("unexpected end of WebAssembly input")
        value = self.data[self.offset]
        self.offset += 1
        return value

    def take(self, count: int) -> bytes:
        if count < 0 or count > self.remaining:
            raise WasmStructuralError("WebAssembly field is truncated")
        end = self.offset + count
        value = self.data[self.offset:end]
        self.offset = end
        return value

    def u(self, bits: int = 32) -> int:
        maximum_bytes = (bits + 6) // 7
        value = 0
        shift = 0
        for index in range(maximum_bytes):
            byte = self.byte()
            value |= (byte & 0x7F) << shift
            if not byte & 0x80:
                if value >= 1 << bits:
                    raise WasmStructuralError("unsigned LEB128 value overflows its field")
                return value
            shift += 7
        raise WasmStructuralError("unsigned LEB128 exceeds its bounded width")

    def s(self, bits: int) -> int:
        maximum_bytes = (bits + 6) // 7
        value = 0
        shift = 0
        final = 0
        for _ in range(maximum_bytes):
            final = self.byte()
            value |= (final & 0x7F) << shift
            shift += 7
            if not final & 0x80:
                if final & 0x40:
                    value -= 1 << shift
                if not -(1 << (bits - 1)) <= value < 1 << (bits - 1):
                    raise WasmStructuralError("signed LEB128 value overflows its field")
                return value
        raise WasmStructuralError("signed LEB128 exceeds its bounded width")

    def name(self) -> str:
        payload = self.take(self.u(32))
        try:
            return payload.decode("utf-8", errors="strict")
        except UnicodeDecodeError as exc:
            raise WasmStructuralError("WebAssembly name is not valid UTF-8") from exc

    def finish(self, field: str) -> None:
        if self.remaining:
            raise WasmStructuralError(f"trailing bytes remain in {field}")


def decode_module(module_bytes: bytes) -> WasmModule:
    if not isinstance(module_bytes, bytes):
        raise WasmStructuralError("WebAssembly module must be bytes")
    if not module_bytes.startswith(MAGIC_VERSION):
        raise WasmStructuralError("wrong WebAssembly magic or version")

    reader = _Reader(module_bytes[len(MAGIC_VERSION) :])
    sections: list[Section] = []
    previous_standard_id = 0
    while reader.remaining:
        section_id = reader.byte()
        if section_id not in KNOWN_SECTION_IDS:
            raise WasmStructuralError("unknown WebAssembly section ID")
        # Core permits Custom sections at any position and more than once.
        # They must survive structural framing so the frozen feature pass, not
        # the malformed-binary pass, classifies their profile prohibition.
        if section_id != 0:
            if section_id <= previous_standard_id:
                raise WasmStructuralError(
                    "standard WebAssembly sections repeat or are out of order"
                )
            previous_standard_id = section_id
        payload = _Reader(reader.take(reader.u(32)))
        content = _decode_section(section_id, payload)
        payload.finish(f"section {section_id}")
        sections.append(Section(section_id, content))

    types = _section_content(sections, 1, ())
    imports = _section_content(sections, 2, ())
    functions = _section_content(sections, 3, ())
    globals_ = _section_content(sections, 6, ())
    exports = _section_content(sections, 7, ())
    bodies = _section_content(sections, 10, ())
    return WasmModule(
        tuple(sections),
        tuple(types),
        tuple(imports),
        tuple(functions),
        tuple(globals_),
        tuple(exports),
        tuple(bodies),
    )


def encode_module(module: WasmModule) -> bytes:
    encoded = bytearray(MAGIC_VERSION)
    for section in module.sections:
        payload = _encode_section(section.section_id, section.content)
        encoded.append(section.section_id)
        encoded.extend(_u_leb(len(payload)))
        encoded.extend(payload)
    return bytes(encoded)


def _section_content(sections: list[Section], section_id: int, default: object) -> object:
    for section in sections:
        if section.section_id == section_id:
            return section.content
    return default


def _decode_section(section_id: int, reader: _Reader) -> object:
    if section_id == 0:
        return (reader.name(), reader.take(reader.remaining))
    if section_id == 1:
        return tuple(_decode_function_type(reader) for _ in range(reader.u(32)))
    if section_id == 2:
        return tuple(_decode_import(reader) for _ in range(reader.u(32)))
    if section_id == 3:
        return tuple(reader.u(32) for _ in range(reader.u(32)))
    if section_id == 4:
        return tuple(_decode_table_type(reader) for _ in range(reader.u(32)))
    if section_id == 5:
        return tuple(_decode_limits(reader) for _ in range(reader.u(32)))
    if section_id == 6:
        return tuple(_decode_global(reader) for _ in range(reader.u(32)))
    if section_id == 7:
        return tuple(_decode_export(reader) for _ in range(reader.u(32)))
    if section_id == 8:
        return reader.u(32)
    if section_id == 9:
        return tuple(_decode_element_segment(reader) for _ in range(reader.u(32)))
    if section_id == 10:
        return tuple(_decode_body(reader) for _ in range(reader.u(32)))
    if section_id == 11:
        return tuple(_decode_data_segment(reader) for _ in range(reader.u(32)))
    if section_id == 12:
        return reader.u(32)
    raise WasmStructuralError("unsupported standard section framing")


def _decode_function_type(reader: _Reader) -> FunctionType:
    if reader.byte() != 0x60:
        raise WasmStructuralError("unknown WebAssembly function type form")
    params = tuple(reader.byte() for _ in range(reader.u(32)))
    results = tuple(reader.byte() for _ in range(reader.u(32)))
    return FunctionType(params, results)


def _decode_import(reader: _Reader) -> ImportEntry:
    module = reader.name()
    name = reader.name()
    kind = reader.byte()
    if kind == 0:
        descriptor: object = reader.u(32)
    elif kind == 1:
        descriptor = _decode_table_type(reader)
    elif kind == 2:
        descriptor = _decode_limits(reader)
    elif kind == 3:
        descriptor = (reader.byte(), reader.byte())
    elif kind == 4:
        # Exception-handling tag imports have a known index-shaped framing.
        # They remain forbidden and are classified by the feature pass.
        descriptor = reader.u(32)
    else:
        raise WasmStructuralError("unknown WebAssembly import descriptor")
    return ImportEntry(module, name, kind, descriptor)


def _decode_table_type(reader: _Reader) -> tuple[int, Limits]:
    return reader.byte(), _decode_limits(reader)


def _decode_limits(reader: _Reader) -> Limits:
    flags = reader.u(32)
    minimum = reader.u(64 if flags & 0x04 else 32)
    maximum = reader.u(64 if flags & 0x04 else 32) if flags & 0x01 else None
    return Limits(flags, minimum, maximum)


def _decode_global(reader: _Reader) -> GlobalEntry:
    value_type = reader.byte()
    mutable = reader.byte()
    initializer = _decode_expression(reader)
    return GlobalEntry(value_type, mutable, initializer)


def _decode_export(reader: _Reader) -> ExportEntry:
    return ExportEntry(reader.name(), reader.byte(), reader.u(32))


def _decode_element_segment(reader: _Reader) -> ElementSegment:
    flags = reader.u(32)
    if flags == 0:
        fields = (_decode_expression(reader), _u32_vector(reader))
    elif flags == 1:
        fields = (reader.byte(), _u32_vector(reader))
    elif flags == 2:
        fields = (reader.u(32), _decode_expression(reader), reader.byte(), _u32_vector(reader))
    elif flags == 3:
        fields = (reader.byte(), _u32_vector(reader))
    elif flags == 4:
        fields = (_decode_expression(reader), _expression_vector(reader))
    elif flags == 5:
        fields = (reader.byte(), _expression_vector(reader))
    elif flags == 6:
        fields = (reader.u(32), _decode_expression(reader), reader.byte(), _expression_vector(reader))
    elif flags == 7:
        fields = (reader.byte(), _expression_vector(reader))
    else:
        raise WasmStructuralError("unknown element-segment flags")
    return ElementSegment(flags, fields)


def _decode_data_segment(reader: _Reader) -> DataSegment:
    flags = reader.u(32)
    if flags == 0:
        memory_index = 0
        offset = _decode_expression(reader)
    elif flags == 1:
        memory_index = None
        offset = None
    elif flags == 2:
        memory_index = reader.u(32)
        offset = _decode_expression(reader)
    else:
        raise WasmStructuralError("unknown data-segment flags")
    return DataSegment(flags, memory_index, offset, reader.take(reader.u(32)))


def _u32_vector(reader: _Reader) -> tuple[int, ...]:
    return tuple(reader.u(32) for _ in range(reader.u(32)))


def _expression_vector(reader: _Reader) -> tuple[tuple[Instruction, ...], ...]:
    return tuple(_decode_expression(reader) for _ in range(reader.u(32)))


def _decode_body(reader: _Reader) -> FunctionBody:
    body_reader = _Reader(reader.take(reader.u(32)))
    groups = tuple(
        (body_reader.u(32), body_reader.byte())
        for _ in range(body_reader.u(32))
    )
    instructions = _decode_expression(body_reader)
    body_reader.finish("function body")
    return FunctionBody(groups, instructions)


def _decode_expression(reader: _Reader) -> tuple[Instruction, ...]:
    instructions: list[Instruction] = []
    depth = 1
    while depth:
        instruction = _decode_instruction(reader)
        instructions.append(instruction)
        if instruction.opcode in (0x02, 0x03, 0x04, 0x06):
            depth += 1
        elif instruction.opcode in (0x0B, 0x18):
            depth -= 1
    return tuple(instructions)


def _decode_instruction(reader: _Reader) -> Instruction:
    opcode = reader.byte()
    immediate: object = None
    if opcode in (0x02, 0x03, 0x04, 0x06):
        immediate = reader.s(33)
    elif opcode in (
        0x07, 0x08, 0x09, 0x0C, 0x0D, 0x10, 0x12, 0x14, 0x15, 0x18,
        0x20, 0x21, 0x22, 0x23, 0x24,
    ):
        immediate = reader.u(32)
    elif opcode == 0x0E:
        immediate = (tuple(reader.u(32) for _ in range(reader.u(32))), reader.u(32))
    elif opcode in (0x11, 0x13):
        immediate = (reader.u(32), reader.u(32))
    elif opcode == 0x1C:
        immediate = tuple(reader.byte() for _ in range(reader.u(32)))
    elif 0x28 <= opcode <= 0x3E:
        immediate = (reader.u(32), reader.u(32))
    elif opcode in (0x3F, 0x40):
        immediate = reader.u(32)
    elif opcode == 0x41:
        immediate = reader.s(32)
    elif opcode == 0x42:
        immediate = reader.s(64)
    elif opcode == 0x43:
        immediate = reader.take(4)
    elif opcode == 0x44:
        immediate = reader.take(8)
    elif opcode == 0xD0:
        immediate = reader.s(33)
    elif opcode == 0xD2:
        immediate = reader.u(32)
    elif opcode in (0xFB, 0xFC, 0xFD, 0xFE):
        subopcode = reader.u(32)
        extra: tuple[int, ...] = ()
        if opcode == 0xFC:
            if subopcode == 8:
                extra = (reader.u(32), reader.u(32))
            elif subopcode in (9, 11, 13, 15, 16, 17):
                extra = (reader.u(32),)
            elif subopcode in (10, 12, 14):
                extra = (reader.u(32), reader.u(32))
        immediate = (subopcode, extra)
    elif not _known_no_immediate_opcode(opcode):
        raise WasmStructuralError("unknown or unframed WebAssembly opcode")
    return Instruction(opcode, immediate)


def _known_no_immediate_opcode(opcode: int) -> bool:
    return (
        opcode in {0x00, 0x01, 0x05, 0x0A, 0x0B, 0x0F, 0x19, 0x1A, 0x1B, 0xD1}
        or 0x45 <= opcode <= 0xBF
        or 0xC0 <= opcode <= 0xC4
    )


def _encode_section(section_id: int, content: object) -> bytes:
    if section_id == 0:
        name, suffix = content
        return _name(name) + suffix
    if section_id == 1:
        values = tuple(content)
        return _vector(values, _encode_function_type)
    if section_id == 2:
        return _vector(tuple(content), _encode_import)
    if section_id == 3:
        return _vector(tuple(content), _u_leb)
    if section_id == 4:
        return _vector(tuple(content), _encode_table_type)
    if section_id == 5:
        return _vector(tuple(content), _encode_limits)
    if section_id == 6:
        return _vector(tuple(content), _encode_global)
    if section_id == 7:
        return _vector(tuple(content), _encode_export)
    if section_id == 8:
        return _u_leb(content)
    if section_id == 9:
        return _vector(tuple(content), _encode_element_segment)
    if section_id == 10:
        return _vector(tuple(content), _encode_body)
    if section_id == 11:
        return _vector(tuple(content), _encode_data_segment)
    if section_id == 12:
        return _u_leb(content)
    raise WasmStructuralError("cannot encode unknown WebAssembly section")


def _vector(values: tuple, item_encoder) -> bytes:
    return _u_leb(len(values)) + b"".join(item_encoder(value) for value in values)


def _encode_function_type(value: FunctionType) -> bytes:
    return b"\x60" + _bytes_vector(value.params) + _bytes_vector(value.results)


def _bytes_vector(values: tuple[int, ...]) -> bytes:
    return _u_leb(len(values)) + bytes(values)


def _encode_import(value: ImportEntry) -> bytes:
    encoded = bytearray(_name(value.module) + _name(value.name) + bytes((value.kind,)))
    if value.kind == 0:
        encoded.extend(_u_leb(value.descriptor))
    elif value.kind == 1:
        encoded.extend(_encode_table_type(value.descriptor))
    elif value.kind == 2:
        encoded.extend(_encode_limits(value.descriptor))
    elif value.kind == 3:
        value_type, mutable = value.descriptor
        encoded.extend((value_type, mutable))
    elif value.kind == 4:
        encoded.extend(_u_leb(value.descriptor))
    else:
        raise WasmStructuralError("unknown WebAssembly import descriptor")
    return bytes(encoded)


def _encode_table_type(value: tuple[int, Limits]) -> bytes:
    return bytes((value[0],)) + _encode_limits(value[1])


def _encode_limits(value: Limits) -> bytes:
    encoded = bytearray(_u_leb(value.flags) + _u_leb(value.minimum))
    if value.flags & 0x01:
        if value.maximum is None:
            raise WasmStructuralError("bounded limits omit a maximum")
        encoded.extend(_u_leb(value.maximum))
    return bytes(encoded)


def _encode_global(value: GlobalEntry) -> bytes:
    return bytes((value.value_type, value.mutable)) + _encode_instructions(value.initializer)


def _encode_export(value: ExportEntry) -> bytes:
    return _name(value.name) + bytes((value.kind,)) + _u_leb(value.index)


def _encode_element_segment(value: ElementSegment) -> bytes:
    encoded = bytearray(_u_leb(value.flags))
    fields = value.fields
    if value.flags == 0:
        encoded.extend(_encode_instructions(fields[0]))
        encoded.extend(_vector(tuple(fields[1]), _u_leb))
    elif value.flags in (1, 3):
        encoded.append(fields[0])
        encoded.extend(_vector(tuple(fields[1]), _u_leb))
    elif value.flags == 2:
        encoded.extend(_u_leb(fields[0]))
        encoded.extend(_encode_instructions(fields[1]))
        encoded.append(fields[2])
        encoded.extend(_vector(tuple(fields[3]), _u_leb))
    elif value.flags == 4:
        encoded.extend(_encode_instructions(fields[0]))
        encoded.extend(_expression_vector_bytes(fields[1]))
    elif value.flags in (5, 7):
        encoded.append(fields[0])
        encoded.extend(_expression_vector_bytes(fields[1]))
    elif value.flags == 6:
        encoded.extend(_u_leb(fields[0]))
        encoded.extend(_encode_instructions(fields[1]))
        encoded.append(fields[2])
        encoded.extend(_expression_vector_bytes(fields[3]))
    return bytes(encoded)


def _encode_data_segment(value: DataSegment) -> bytes:
    encoded = bytearray(_u_leb(value.flags))
    if value.flags == 0:
        encoded.extend(_encode_instructions(value.offset))
    elif value.flags == 2:
        encoded.extend(_u_leb(value.memory_index))
        encoded.extend(_encode_instructions(value.offset))
    encoded.extend(_u_leb(len(value.data)))
    encoded.extend(value.data)
    return bytes(encoded)


def _expression_vector_bytes(values: tuple[tuple[Instruction, ...], ...]) -> bytes:
    return _u_leb(len(values)) + b"".join(_encode_instructions(value) for value in values)


def _encode_body(value: FunctionBody) -> bytes:
    groups = _u_leb(len(value.local_groups)) + b"".join(
        _u_leb(count) + bytes((value_type,))
        for count, value_type in value.local_groups
    )
    body = groups + _encode_instructions(value.instructions)
    return _u_leb(len(body)) + body


def _encode_instructions(instructions: tuple[Instruction, ...]) -> bytes:
    encoded = bytearray()
    for instruction in instructions:
        opcode = instruction.opcode
        immediate = instruction.immediate
        encoded.append(opcode)
        if opcode in (0x02, 0x03, 0x04, 0x06):
            encoded.extend(_s_leb(immediate, 33))
        elif opcode in (
            0x07, 0x08, 0x09, 0x0C, 0x0D, 0x10, 0x12, 0x14, 0x15, 0x18,
            0x20, 0x21, 0x22, 0x23, 0x24,
        ):
            encoded.extend(_u_leb(immediate))
        elif opcode == 0x0E:
            labels, default = immediate
            encoded.extend(_vector(tuple(labels), _u_leb))
            encoded.extend(_u_leb(default))
        elif opcode in (0x11, 0x13):
            encoded.extend(_u_leb(immediate[0]))
            encoded.extend(_u_leb(immediate[1]))
        elif opcode == 0x1C:
            encoded.extend(_bytes_vector(tuple(immediate)))
        elif 0x28 <= opcode <= 0x3E:
            encoded.extend(_u_leb(immediate[0]))
            encoded.extend(_u_leb(immediate[1]))
        elif opcode in (0x3F, 0x40):
            encoded.extend(_u_leb(immediate))
        elif opcode == 0x41:
            encoded.extend(_s_leb(immediate, 32))
        elif opcode == 0x42:
            encoded.extend(_s_leb(immediate, 64))
        elif opcode in (0x43, 0x44):
            encoded.extend(immediate)
        elif opcode == 0xD0:
            encoded.extend(_s_leb(immediate, 33))
        elif opcode == 0xD2:
            encoded.extend(_u_leb(immediate))
        elif opcode in (0xFB, 0xFC, 0xFD, 0xFE):
            subopcode, extra = immediate
            encoded.extend(_u_leb(subopcode))
            for value in extra:
                encoded.extend(_u_leb(value))
    return bytes(encoded)


def _name(value: str) -> bytes:
    encoded = value.encode("utf-8", errors="strict")
    return _u_leb(len(encoded)) + encoded


def _u_leb(value: int) -> bytes:
    if type(value) is not int or value < 0:
        raise WasmStructuralError("unsigned LEB128 value is negative")
    encoded = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            byte |= 0x80
        encoded.append(byte)
        if not value:
            return bytes(encoded)


def _s_leb(value: int, bits: int) -> bytes:
    if type(value) is not int or not -(1 << (bits - 1)) <= value < 1 << (bits - 1):
        raise WasmStructuralError("signed LEB128 value is out of range")
    encoded = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        done = (value == 0 and not byte & 0x40) or (value == -1 and byte & 0x40)
        encoded.append(byte if done else byte | 0x80)
        if done:
            return bytes(encoded)
