"""Domain-separation tags of ARES Lite (every tag starts with `ARES-LITE/`)."""

SEASON_MANIFEST = "ARES-LITE/SEASON-MANIFEST/v0"
SEASON_TICKET = "ARES-LITE/SEASON-TICKET/v0"
CHALLENGE_SEED = "ARES-LITE/CHALLENGE-SEED/v0"
VERIFICATION_SEED = "ARES-LITE/VERIFICATION-SEED/v0"
PRACTICE_SEED = "ARES-LITE/PRACTICE-SEED/v0"
BENCHMARK_SEED = "ARES-LITE/BENCHMARK-SEED/v0"
BENCHMARK_CASE = "ARES-LITE/BENCHMARK-CASE/v0"
MINING_KEY_REF = "ARES-LITE/MINING-KEY-REF/v0"
FAMILY_CONFIG_REF = "ARES-LITE/FAMILY-CONFIG-REF/v0"
RECEIPT = "ARES-LITE/RECEIPT/v0"
EVALUATION = "ARES-LITE/EVALUATION/v0"
REWARD_TABLE = "ARES-LITE/REWARD-TABLE/v0"

# The claim Merkle tree is verified on Solana, which exposes SHA-256 (not
# SHA3) as a syscall. These tags are prefixed to SHA-256 inputs together with a
# one-byte node kind; see ares_lite.merkle and solana/program.
CLAIM_LEAF_TAG = b"ARES-LITE/CLAIM-LEAF/v0"
CLAIM_NODE_TAG = b"ARES-LITE/CLAIM-NODE/v0"
