# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/canonical/__init__.py — do not edit.
"""Shared canonical serialization and hashing for ARES research v0."""

from .codec import (
    CanonicalDecodingError,
    CanonicalEncodingError,
    decode,
    encode,
)
from .hashing import (
    TranscriptHashingError,
    frame,
    hash_bytes,
    u8,
    u16_be,
    u32_be,
    u64_be,
)
from .transcripts import (
    CanonicalTranscriptError,
    hash_canonical,
    lane_round_key,
    option,
    ordered_set,
    parse_option,
    set_digest,
)

__all__ = [
    "CanonicalDecodingError",
    "CanonicalEncodingError",
    "CanonicalTranscriptError",
    "TranscriptHashingError",
    "decode",
    "encode",
    "frame",
    "hash_bytes",
    "hash_canonical",
    "lane_round_key",
    "option",
    "ordered_set",
    "parse_option",
    "set_digest",
    "u8",
    "u16_be",
    "u32_be",
    "u64_be",
]
