# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/canonical/codec.py — do not edit.
"""Restricted deterministic CBOR for ARES research transcripts.

The codec implements only the value grammar frozen by the accepted P0
specifications. It intentionally has no maps, tags, floating-point values,
simple values, or indefinite-length forms. Protocol modules remain responsible
for validating the field count, field type, and bounds of each decoded array.

Decoding accepts exactly one complete value and rejects alternate encodings of
the same value. This prevents distinct byte strings from acquiring the same
consensus interpretation.
"""

from __future__ import annotations


MAX_CBOR_ARGUMENT = (1 << 64) - 1
MIN_CBOR_INTEGER = -(1 << 64)


class CanonicalEncodingError(ValueError):
    """A value cannot be represented by the restricted ARES profile."""


class CanonicalDecodingError(ValueError):
    """Input is malformed, forbidden, truncated, or non-canonical."""


def encode(value: object) -> bytes:
    """Encode one value using the restricted deterministic CBOR profile."""

    if type(value) is int:
        return _encode_integer(value)
    if isinstance(value, bytes):
        return _head(2, len(value)) + value
    if isinstance(value, str):
        try:
            encoded = value.encode("utf-8", errors="strict")
        except UnicodeEncodeError as exc:
            raise CanonicalEncodingError("text contains an invalid Unicode scalar") from exc
        return _head(3, len(encoded)) + encoded
    if isinstance(value, (list, tuple)):
        return _head(4, len(value)) + b"".join(encode(item) for item in value)
    raise CanonicalEncodingError(
        f"unsupported canonical value type: {type(value).__name__}"
    )


def decode(data: bytes) -> object:
    """Decode one complete canonical value and reject trailing bytes."""

    if not isinstance(data, bytes):
        raise CanonicalDecodingError("canonical input must be bytes")
    if not data:
        raise CanonicalDecodingError("canonical input is empty")

    offset = 0
    stack: list[list[object]] = []
    value: object | None = None
    have_value = False

    while True:
        if not have_value:
            initial = data[offset]
            offset += 1
            major = initial >> 5
            additional = initial & 0x1F
            argument, offset = _decode_argument(data, offset, additional)

            if major == 0:
                value = argument
                have_value = True
            elif major == 1:
                value = -1 - argument
                have_value = True
            elif major in (2, 3):
                end = offset + argument
                if end > len(data):
                    raise CanonicalDecodingError("byte or text string is truncated")
                payload = data[offset:end]
                offset = end
                if major == 2:
                    value = payload
                else:
                    try:
                        value = payload.decode("utf-8", errors="strict")
                    except UnicodeDecodeError as exc:
                        raise CanonicalDecodingError("text string is not valid UTF-8") from exc
                have_value = True
            elif major == 4:
                if argument == 0:
                    value = []
                    have_value = True
                else:
                    stack.append([argument, []])
            else:
                raise CanonicalDecodingError(
                    f"CBOR major type {major} is forbidden by the ARES profile"
                )

        if have_value:
            if not stack:
                if offset != len(data):
                    raise CanonicalDecodingError("trailing bytes follow the canonical value")
                return value

            remaining, items = stack[-1]
            assert isinstance(remaining, int)
            assert isinstance(items, list)
            items.append(value)
            remaining -= 1
            if remaining == 0:
                stack.pop()
                value = items
                have_value = True
            else:
                stack[-1][0] = remaining
                have_value = False

        if not have_value and offset >= len(data):
            raise CanonicalDecodingError("array is truncated")


def _encode_integer(value: int) -> bytes:
    if value >= 0:
        if value > MAX_CBOR_ARGUMENT:
            raise CanonicalEncodingError("unsigned CBOR integer exceeds u64")
        return _head(0, value)
    if value < MIN_CBOR_INTEGER:
        raise CanonicalEncodingError("negative CBOR integer is below -2^64")
    return _head(1, -1 - value)


def _head(major: int, argument: int) -> bytes:
    if not 0 <= argument <= MAX_CBOR_ARGUMENT:
        raise CanonicalEncodingError("CBOR length or argument exceeds u64")
    prefix = major << 5
    if argument < 24:
        return bytes((prefix | argument,))
    if argument <= 0xFF:
        return bytes((prefix | 24, argument))
    if argument <= 0xFFFF:
        return bytes((prefix | 25,)) + argument.to_bytes(2, "big")
    if argument <= 0xFFFFFFFF:
        return bytes((prefix | 26,)) + argument.to_bytes(4, "big")
    return bytes((prefix | 27,)) + argument.to_bytes(8, "big")


def _decode_argument(data: bytes, offset: int, additional: int) -> tuple[int, int]:
    if additional < 24:
        return additional, offset
    if additional == 24:
        width, minimum = 1, 24
    elif additional == 25:
        width, minimum = 2, 1 << 8
    elif additional == 26:
        width, minimum = 4, 1 << 16
    elif additional == 27:
        width, minimum = 8, 1 << 32
    elif additional == 31:
        raise CanonicalDecodingError("indefinite-length values are forbidden")
    else:
        raise CanonicalDecodingError("reserved CBOR additional information is forbidden")

    end = offset + width
    if end > len(data):
        raise CanonicalDecodingError("CBOR argument is truncated")
    argument = int.from_bytes(data[offset:end], "big")
    if argument < minimum:
        raise CanonicalDecodingError("CBOR argument does not use its shortest form")
    return argument, end
