# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/canonical/hashing.py — do not edit.
"""Fixed-width and domain-separated hashing primitives for ARES research v0.

The framing construction is consensus-observable. Every domain and part is
length-prefixed so field concatenation cannot create an alternate transcript.
Callers must supply an explicit versioned domain; this module has no default or
fallback domain.
"""

from __future__ import annotations

import hashlib
from collections.abc import Iterable


UINT32_MAX = (1 << 32) - 1


class TranscriptHashingError(ValueError):
    """A transcript component cannot be represented by the frozen framing."""


def u8(value: int) -> bytes:
    return _fixed_width(value, 1, "u8")


def u16_be(value: int) -> bytes:
    return _fixed_width(value, 2, "u16")


def u32_be(value: int) -> bytes:
    return _fixed_width(value, 4, "u32")


def u64_be(value: int) -> bytes:
    return _fixed_width(value, 8, "u64")


def frame(domain: str, parts: Iterable[bytes]) -> bytes:
    """Return the exact length-prefixed v0 transcript for a domain and parts."""

    if not isinstance(domain, str):
        raise TranscriptHashingError("hash domain must be text")
    try:
        encoded_domain = domain.encode("ascii", errors="strict")
    except UnicodeEncodeError as exc:
        raise TranscriptHashingError("hash domain must contain only ASCII") from exc
    if len(encoded_domain) > UINT32_MAX:
        raise TranscriptHashingError("hash domain exceeds u32 length")

    framed = bytearray(u32_be(len(encoded_domain)))
    framed.extend(encoded_domain)
    for part in parts:
        if not isinstance(part, bytes):
            raise TranscriptHashingError("hash frame parts must be bytes")
        if len(part) > UINT32_MAX:
            raise TranscriptHashingError("hash frame part exceeds u32 length")
        framed.extend(u32_be(len(part)))
        framed.extend(part)
    return bytes(framed)


def hash_bytes(domain: str, parts: Iterable[bytes]) -> bytes:
    """Compute SHA3-256 over the exact frozen FRAME construction."""

    return hashlib.sha3_256(frame(domain, parts)).digest()


def _fixed_width(value: int, width: int, name: str) -> bytes:
    if type(value) is not int or not 0 <= value < 1 << (8 * width):
        raise TranscriptHashingError(f"{name} value is out of range")
    return value.to_bytes(width, "big")
