# GENERATED by lite/release/build_sdk.py from the frozen private module ares_protocol/canonical/transcripts.py — do not edit.
"""Pure canonical transcript helpers shared by ARES research components.

These functions construct bytes and hashes only. They do not decide whether a
ticket is eligible, a phase transition is valid, an allocation succeeds, a
reward is due, or a controller update is correct.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable

from .codec import encode
from .hashing import hash_bytes


class CanonicalTranscriptError(ValueError):
    """A transcript violates an ordering or option representation invariant."""


def lane_round_key(
    chain_id: bytes,
    protocol_version: int,
    round_id: int,
    family_id: str,
    family_version: int,
) -> list[object]:
    """Construct the shared P0-T03 Lane Round Key canonical array.

    ``family_id`` is deliberately text, not bytes. Keeping this constraint in
    the shared constructor prevents an importing schema from creating a second
    wire representation for the same Lane Round Key.
    """

    if not isinstance(chain_id, bytes) or not 1 <= len(chain_id) <= 64:
        raise CanonicalTranscriptError("chain_id must contain 1 through 64 bytes")
    _require_uint(protocol_version, 32, "protocol_version")
    _require_uint(round_id, 64, "round_id")
    if not isinstance(family_id, str):
        raise CanonicalTranscriptError("family_id must be CBOR text")
    try:
        encoded_family = family_id.encode("ascii", errors="strict")
    except UnicodeEncodeError as exc:
        raise CanonicalTranscriptError("family_id must contain only ASCII") from exc
    if not 1 <= len(encoded_family) <= 64:
        raise CanonicalTranscriptError("family_id must contain 1 through 64 ASCII bytes")
    _require_uint(family_version, 16, "family_version")
    return [0, chain_id, protocol_version, round_id, family_id, family_version]


def hash_canonical(domain: str, value: object) -> bytes:
    """Hash the canonical bytes of one value under an explicit domain."""

    return hash_bytes(domain, (encode(value),))


def option(value: object = ...) -> list[object]:
    """Construct the frozen option representation: [] or [value]."""

    return [] if value is ... else [value]


def parse_option(value: object) -> tuple[bool, object | None]:
    """Validate and unpack a canonical option without interpreting its payload."""

    if not isinstance(value, list):
        raise CanonicalTranscriptError("canonical option must be an array")
    if not value:
        return False, None
    if len(value) == 1:
        return True, value[0]
    raise CanonicalTranscriptError("canonical option must contain zero or one value")


def ordered_set(
    records: Iterable[object],
    *,
    key: Callable[[object], bytes],
) -> list[object]:
    """Sort records by their schema-defined byte key and reject duplicates."""

    keyed: list[tuple[bytes, object]] = []
    for record in records:
        record_key = key(record)
        if not isinstance(record_key, bytes):
            raise CanonicalTranscriptError("ordered-set keys must be bytes")
        keyed.append((record_key, record))
    keyed.sort(key=lambda item: item[0])
    for previous, current in zip(keyed, keyed[1:]):
        if previous[0] == current[0]:
            raise CanonicalTranscriptError("ordered set contains a duplicate key")
    return [record for _, record in keyed]


def set_digest(
    domain: str,
    records: Iterable[object],
    *,
    key: Callable[[object], bytes],
) -> bytes:
    """Hash a schema-keyed record array using the P0-T03 SET_DIGEST rule."""

    return hash_canonical(domain, ordered_set(records, key=key))


def _require_uint(value: int, bits: int, name: str) -> None:
    if type(value) is not int or not 0 <= value < 1 << bits:
        raise CanonicalTranscriptError(
            f"{name} must be an unsigned {bits}-bit integer"
        )
